### ISSUE TITLE
Import YGTC theme settings into Lily

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1020]
Get theme settings into OpenY

https://github.com/ymcatwincities/ymca/pull/2861

@ymcagtc could you add this to OpenY roadmap?

User story
As OpenY user I want to have same color and theme settings for OpenY Lily theme as used my YMCA of Greater Twin Cities
![image](https://user-images.githubusercontent.com/563412/39517713-532cb0d4-4e09-11e8-8ea8-0c6bc5b3e8a3.png)

**Comment by YMCA-GTC** [comment]
@podarok Adding this to roadmap per your request

**Comment by paige-kiecker** [comment]
Closing this out to clean up redundancy. It was added to roadmap (https://trello.com/c/B7VXJ0Ng/126-backport-ygtc-theme-settings-into-lily-score-7) with a link back to this ticket.
