### ISSUE TITLE
Incorporate all Open Y settings in one place

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1045]
Currently, there are many settings that Open Y modules provide and all of them are in different places. For instance: 
- `OpenY upgrade dashboard`: Home -> Administration -> Configuration -> Development -> OpenY upgrade dashboard
- `openy map settings`: Home -> Administration -> Configuration -> Web services -> openy map settings
- `Daxko Programs Search settings`: Home -> Administration  -> Configuration ->  Web services  -> Daxko settings -> Programs Search settings
- `Session Instances Listing`: Home -> Administration -> Structure  -> Session Instances Listing
- etc...

For people who familiar with Drupal will not be difficult to find all these settings, but for new in Drupal, it's kind of a challenge. 
I suggest to create a top-level menu item which will be called `Open Y` and it will contain all the Open Y settings, mapping, and dev tools under in one place. 
Here is an example how it can look:
![session instances listing 7c site-install f0 9f 94 8a 2018-05-16 13-01-36](https://user-images.githubusercontent.com/6285570/40110767-8d56ef3a-5909-11e8-892c-791af0069d3a.png)

cc @podarok , @YMCA-GTC , @Sanchiz , @ygerasimov

**Comment by YMCA-GTC** [comment]
This is a REALLY good idea @ddrozdik ! I'll be pulling this into the roadmap. We can't use the Y logo due to copyrights, but just a cachet "Y" could suffice for the icon.

**Comment by ddrozdik** [comment]
the first steps to implement this idea were made in this PR https://github.com/ymcatwincities/openy/pull/1268

**Comment by ddrozdik** [comment]
![openy-active](https://user-images.githubusercontent.com/6285570/45306046-54259780-b524-11e8-9244-abacb93b3010.png)  ![openy-inactive](https://user-images.githubusercontent.com/6285570/45306047-54259780-b524-11e8-8fb9-16299dd56488.png)

@YMCA-GTC can we use such images as icons for the menu ? cc @podarok

**Comment by podarok** [comment]
@ddrozdik where they will be placed specifically?

**Comment by ddrozdik** [comment]
@podarok in the admin menu, see my very first screenshot in this issue. Intead of colored YMCA logo we would like to use this Y icon.

**Comment by YMCA-GTC** [comment]
We can't use the YMCA logo, unfortunately. We will soon have an Open Y specific logo. The reason is that Open Y is not owned by the YMCA and so we can't use the YMCA logo. Open Y is a separate entity.

**Comment by ddrozdik** [comment]
ok. then gear icon should be ok to use, at least for now.

**Comment by ddrozdik** [comment]
This is going to be implemented in the Open Y 2.0

**Comment by ddrozdik** [comment]
@podarok , @YMCA-GTC we've prepared a new structure with all the known menu items from all Open Y modules https://docs.google.com/document/d/1OoHpNe9A-Yy2eltPU0jviW5qTay4GKfNy-CzAuOxmsI/edit# . Please review and let us know if you would like to change anything.

**Comment by podarok** [comment]
Looks good. Just better naming for GroupEX Pro menu items for less confusion needed
Thanks a lot @ddrozdik

**Comment by YMCA-GTC** [comment]
Makes sense - but we for sure will want to have a tutorial video explaining the change, and some good documentation we can direct people to that's hosted on the message board at https://community.openymca.org because we have 26 sites as of Q3 2018 already using Open Y and need to ensure we aren't causing them significant confusion.
