### ISSUE TITLE
Render issue with the paragraph "Teaser"

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1046]
There is a paragraph which is called "Teaser". It has fields to enter link and link title. 
![edit landing page test 7c site-install f0 9f 94 8a 2018-05-16 13-36-59](https://user-images.githubusercontent.com/6285570/40112779-d7158040-590f-11e8-8094-43b469adaffb.png)
Currently, these fields are not required. In case you want to create just a teaser without the link, you will get the following issue, see screenshot: 
![test 7c site-install f0 9f 94 8a 2018-05-16 13-51-19](https://user-images.githubusercontent.com/6285570/40113007-9e39c0aa-5910-11e8-8ac8-64989fb25b28.png)

This issue could be easily fixed updating the template of the paragraph. 

cc @podarok, @YMCA-GTC

**Comment by YMCA-GTC** [comment]
Thanks @ddrozdik I am adding it to our backlog

**Comment by YMCA-GTC** [comment]
Resolved in next release - awaiting code review

**Comment by YMCA-GTC** [comment]
Resolved with 1.12
