### ISSUE TITLE
Remove "Search By Amenities" button and titlebar from location landing page

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1051]
Now that we have Amenities filtering in-line on the locations page, it is redundant to have "Search By Amenities". Please remove this blue bar area, button, and title from the Location pages for Rose and Lily

![image](https://user-images.githubusercontent.com/17653329/40327227-c56f4082-5d07-11e8-9cec-6ac1e59e1a4b.png)

**Comment by YMCA-GTC** [comment]
Resolved in next release - awaiting code review

**Comment by YMCA-GTC** [comment]
Resolved as of 1.12

**Comment by ddrozdik** [comment]
@YMCA-GTC , @podarok  I think this should be optional and configurable in the Admin interface. Many YMCAs asking about the possibility to hide filters but leave the button. It would be really great to have this configurable somewhere. 
cc @Sanchiz , @ygerasimov
