### ISSUE TITLE
Membership Calculator is not working - Ajax error

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1067]
Given I go to http://sandbox.openymca.org/join
And I click on "Select" button under Adult

When I click "Next" 
Then I should see Step 2 to select Primary Location
But nothing happens

And I see ajax error in console:
`
js_6UeFfITIG-y6xvuh2tuP_PNPgXUTDbApFZgD1CJLFGA.js:2918 Uncaught Drupal.AjaxError {message: "↵An AJAX HTTP error occurred.↵HTTP Result Code: 20…: /join?ajax_form=1↵StatusText: OK↵ResponseText: ", name: "AjaxError"}
`

**Comment by kolesnikoff** [comment]
This particular issue is fixed here https://github.com/ymcatwincities/openy/pull/1058.

**Comment by YMCA-GTC** [comment]
Resolved with 1.12
