### ISSUE TITLE
Can not edit Branch Or Camp node

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1068]
Check http://sandbox.openymca.org/locations
Result: Fatal error

Login as admin
Go to edit Branch or Camp node
Result: Fatal error

Error: Class 'CommerceGuys\Addressing\LocaleHelper' not found in Drupal\address\Element\Address::addressElements()

**Comment by kolesnikoff** [comment]
Solved into #1058.

**Comment by YMCA-GTC** [comment]
Resolved with 1.12
