### ISSUE TITLE
Add a step with entities list before any openy paragraph deleting

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#1069]
In this PR - https://github.com/ymcatwincities/openy/pull/1036 was implemented `openy_system` module with openy components page. Before component removing - would be nice to add a step with a list of entities and where they are used ( for paragraps ) to let content managers check all will be good after removal. Just a simple table with a list of view/edit.

We can proceed with this improvement only after further work on OpenY components page.

**Comment by ddrozdik** [comment]
I'm closing this since after switching to Open Y packages in the Open Y 2.0, this issue is not relevant anymore.
