### ISSUE TITLE
Menu in OpenY Rose squeezes after removing some menu items 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1078]
I decided that I do not need menu items :) and removed them and left only a few items. When I checked OpenY Rose after that I discovered that menu does not work correctly. See screenshot below:
![page not found site-install 2018-06-05 16-36-16](https://user-images.githubusercontent.com/6285570/40979630-fe3efab4-68de-11e8-83ca-7b2cb175a69d.png)

cc @podarok, @YMCA-GTC

**Comment by YMCA-GTC** [comment]
Upgrading the severity on this - we will go after this ASAP.
