### ISSUE TITLE
Lily: Breadcrumbs CSS is broken following 1.11 or 1.12

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1083]
See the attached screenshot. 
![image](https://user-images.githubusercontent.com/17653329/41065830-85d2b29c-69a5-11e8-90a3-72ef5e4817e2.png)

This happens on Location and Schedules pages (and likely others)

**Comment by taras-tsiuper** [comment]
@YMCA-GTC  @podarok 
Is I see current styles were made especially.
Do you know how it was before or how it should be ?

**Comment by ymcagtc** [comment]
Please copy the designs and implementation from the current YGTC site at https://www.ymcamn.org/locations 

![image](https://user-images.githubusercontent.com/17573526/41566456-27b9335e-7321-11e8-890a-2d52745f1009.png)

Again - this should **only** apply to the Lily theme. Thank you!

**Comment by taras-tsiuper** [comment]
I think we can close this issue as styles are fixed with the fix above:
![breadcrumbs](https://user-images.githubusercontent.com/1905435/41902652-a660543c-793c-11e8-8cb0-ea8396179cb3.jpg)
