### ISSUE TITLE
Improve Search filters on Locations page

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1096]
URL: /locations

1) Openy sandbox has no search filters
![image](https://user-images.githubusercontent.com/4558228/41288267-6854a4d4-6e4e-11e8-910f-9ab29ffb2859.png)

ymcamn.org has filters. Which is useful. (Map is hidden but that's OK, because it could be too small.)
![image](https://user-images.githubusercontent.com/4558228/41288305-841e753c-6e4e-11e8-9519-feb0d67a96ba.png)

2) Also still may be there is an UX ability to add map on mobile too. In a way, that most of the map is taken by map. And only some place at the bottom by filters.

3) If some YMCA not having Camps and Facilities. But only few YMCAs - nice to hide checkbox "YMCAs".

**Comment by ymcagtc** [comment]
Agreed, I'd like to backport some of this functionality in, in the future. If any other Y association wishes to take this work on first, please build it into the distribution (ask your agency for details, or connect with us here) so all may use it.

**Comment by podarok** [comment]
Carnation
![image](https://user-images.githubusercontent.com/563412/55614568-fabdd800-5795-11e9-8868-0971aed3f506.png)

**Comment by podarok** [comment]
Rose - needs fix
![image](https://user-images.githubusercontent.com/563412/55616796-4fb01d00-579b-11e9-80e1-65f2eac2ff76.png)

**Comment by podarok** [comment]
Lily - needs fix
![image](https://user-images.githubusercontent.com/563412/55616871-7c643480-579b-11e9-9a0f-9bffca219143.png)

**Comment by paige-kiecker** [comment]
@podarok let's add this to the list of May enhancements
