### ISSUE TITLE
Can't install using composer command

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#110]
When I try to run 

```
composer create-project ymcatwincities/openy-project MY_PROJECT --no-interaction
```

I get error

```
[InvalidArgumentException]                                                  
Could not find package ymcatwincities/openy-project with stability stable.
```

I am happy to write documentation if you provide instructions how to install the site.

**Comment by alexschedrov** [comment]
Thank you for a good catch!

Installation instructions has been updated:
- https://github.com/ymcatwincities/openy#installation
- https://www.drupal.org/project/openy

```
composer create-project ymcatwincities/openy-project:8.1.x-dev MY_PROJECT --no-interaction
```
