### ISSUE TITLE
Two columns with fixed sidebar (sticky) - sidebar not moving

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1101]
Given I create a landing page with Layout  "Two columns with fixed sidebar (sticky)"
And I add Simple content to the body
And a promo card into sidebar
And I save
When I scroll through the resulting page
Then I expect promo card in sidebar to be always displayed in the sidebar
But it is not sticky

**Comment by ymcagtc** [comment]
@AlexNetman Do you have a URL for a sample page we can test with? If not, no worries, it would just help us debug and resolve this one faster.

**Comment by podarok** [comment]
Confirmed in all 3 themes.
Looks like a regression, we had this working in the past

**Comment by paige-kiecker** [comment]
This was reported again via https://github.com/ymcatwincities/openy/issues/1403 and will be resolved on that ticket. Closing this one.
