### ISSUE TITLE
Blog Post Image Bug

### ISSUE THREAD

**Issue by kolesnikoff** [ymcatwincities/openy#1122]
Hey!
There is an issue with uploading Blog Post images.

*Steps to reproduce*
1. Log in to http://sandbox.openymca.org/
2. Start creating new Blog Post http://sandbox.openymca.org/node/add/blog
3. Try to add an image: Content Area - Image - Select Images - click Select Files - upload a file - fill in all required fields - click "Select images"
4. Nothing happens.

*Expected result*
An image should be uploaded.

**Comment by kolesnikoff** [comment]
@rotator please check this issue

**Comment by rotator** [comment]
The bug was because of this applied patch https://www.drupal.org/project/dropzonejs/issues/2833965#comment-12415711
