### ISSUE TITLE
Indent is not working for text blocks in WYSIWYG

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1130]
![image](https://user-images.githubusercontent.com/4558228/41973487-c7b5ee3a-7a1d-11e8-9e36-5cd985c831ae.png)
Those buttons are not working for usual text.
Only for lists.
So let's update button labels to "Increase Indent for list item", "Decrease Indent for list item".

https://stackoverflow.com/questions/28273487/ckeditor-outdent-icon-is-disabled-when-none-text

**Comment by ymcagtc** [comment]
Increasing severity one step to Normal, as I can see Y associations wanting to use this functionality.

**Comment by podarok** [comment]
fixed
