### ISSUE TITLE
Leverage date based block caching for Alert blocks for varnish issue

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1131]

**Comment by ymcagtc** [comment]
@podarok @danylevskyi Can you guys please add a 1 sentence description to this so others will know if they are experiencing similar issues? Also - is this a bug, or a feature request? I want to label it appropriately. Thank you!

**Comment by podarok** [comment]
IN OpenY 2.0 we have completely decoupled Alerts app which has no issue with caching at all.
Closing.
