### ISSUE TITLE
Improve UX for the help blocks

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1132]
Let's avoid of having placeholder texts in production of OpenY
I'd like to see some ideas about how it should look like.
Initial requiremens - height should be small, probably with some collapsible elements as Read More. We should avoid having links as a plain text.
![image](https://user-images.githubusercontent.com/563412/41987221-24620990-79fe-11e8-9171-28e18f0db76b.png)

**Comment by rotator** [comment]
Also, it will be good to add to OpenY such link modules:
1. [Link Attributes widget](https://www.drupal.org/project/link_attributes) to set classes and attributes for menu links 
2. [D8 Editor Advanced link](https://www.drupal.org/project/editor_advanced_link) to add the same for the link Dialog in D8 CKEditor

**Comment by ymcagtc** [comment]
This is a worthwhile enhancement, but an enhancement and not a bug. Changing the label, and pulling into the roadmap.

**Comment by paige-kiecker** [comment]
This is on the roadmap (https://trello.com/c/FWaeylFD/128-improve-tutorial-and-help-content-blocks-within-the-cms-editor-score-7) and so closing here until development begins
