### ISSUE TITLE
Make BRANCH AMENITIES fieldset collapsible 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1133]
Branch nodes have fieldset with fields to enter amenities. 
![edit branch downtown ymca site-install 2018-06-28 13-02-24](https://user-images.githubusercontent.com/6285570/42027948-9ac9070c-7ad3-11e8-8d3b-889a34f52c64.png)

Would be great to make this fieldset collapsible and collapsed by default .

**Comment by Fant0m771** [comment]
Hi @ddrozdik, 
I just commited fix https://github.com/ymcatwincities/openy/pull/1200

**Comment by paige-kiecker** [comment]
@Fant0m771 can you follow up on https://github.com/ymcatwincities/openy/pull/1200 so we can get that PR merged, please?

**Comment by ddrozdik** [comment]
the fix has been merged already here https://github.com/ymcatwincities/openy/pull/1925. Closing this issue as completed.
