### ISSUE TITLE
Demo content for News posts have missing data

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1134]
There are news posts created during installing demo content, and by default, they have no titles in some paragraphs like `Latest blog posts (camp)` & `Latest blog posts (branch)` while the title is required. 
![edit camp camp colman site-install 2018-06-28 13-23-44](https://user-images.githubusercontent.com/6285570/42028930-82501230-7ad6-11e8-847a-dd3e84a31d47.png)

**Comment by ymcagtc** [comment]
Assigning to IXM.

When in doubt, use the following naming:

- Demo _CONTENT TYPE NAME_ 1
- Demo _CONTENT TYPE NAME_ 2 (and so on)

For example, the above demo content would be "Demo Latest blog posts (camp) 1" or "Demo Latest blog posts (branch) 1"
