### ISSUE TITLE
Demo content should not be located in modules

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1135]
Currently, demo content is located in modules. In case we want to import demo content for some content types we just enable those modules. 

In terms of global Open Y architecture, it does not make sense to build demo content as a module, since we usually install them and do not think about removing in the future. In terms of Drupal architecture, we just leave unused modules that exist in the system. 

I think we can move all demo content configs into a specific folder inside Open Y profile, and just import those configs once needed demo content should be installed(checkbox is selected). And once demo content is imported and nodes are created we can just remove those `migrate` configs from the system. 

@YMCA-GTC, @podarok, @ygerasimov, @Sanchiz what do you think guys?

**Comment by ymcagtc** [comment]
@ddrozdik makes sense to me. I'd like @podarok to weigh in, so assigning it to him.

**Comment by podarok** [comment]
@ddrozdik as far as I know - demo content imported by migrations during installation.
Migration executed on Profile form step here https://github.com/ymcatwincities/openy/blob/8.x-1.x/openy.profile#L261
Which means we can easily disable and uninstall demo content modules if there is a requirement to All demo content modules are already decoupled as far as I see from our codebase and contain only migrations https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/openy_features/openy_demo_content/modules
Why should we move them somewhere else?
I guess having these modules as is means a lot for understanding how to do migrations and how we ship demo content for distribution

**Comment by ddrozdik** [comment]
Based on the latest changes in architecture the new demo content behavior has been introduced in the Open Y 2:0.
