### ISSUE TITLE
Membership calculator: Hide prices if not specified

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1143]
Given I create a new Membership type node but without price specification
And I go to /join
When I select my new membership type for some location
![image](https://user-images.githubusercontent.com/4558228/42173547-1b31d8b8-7e28-11e8-8982-fb3d2ade67e9.png)

Then I should not see prices specified on site
And I can click "Complete Registration" to see the most actual prices on external system

**Comment by ymcagtc** [comment]
I agree this would be a good enhancement. I will add to the backlog on Trello.

**Comment by paige-kiecker** [comment]
Closing this to reduce redundancies. It is on roadmap linking back here.
