### ISSUE TITLE
Social share icons do not display on landing page and some other content types

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1145]
I've enabled Social Share icons on a landing page and event page but they do not appear.  
![edit event fancon event _ site-install 2018-07-02 20-10-10](https://user-images.githubusercontent.com/6285570/42177105-220ae8b2-7e34-11e8-955b-510bc74c6c49.png)

Paragraph with Social Share icons still works well. Blogs and News work as well. The only issue with other content types. 
cc @YMCA-GTC , @podarok

**Comment by ymcagtc** [comment]
Assigning to IXM. Setting severity to Important.
