### ISSUE TITLE
Upgrade to 1.12.1 using PHP 5.6 is impossible 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1153]
There is an issue with the version of Open Y 1.12.1. After adding a fix for the `symfony/dom-crawler` https://github.com/ymcatwincities/openy/pull/1095 we’ve lost the possibility upgrade to this version if in case you are on PHP 5.6. That package requires PHP 7.1.3 and above. 
This happened in this commit https://github.com/ymcatwincities/openy/pull/1095/commits/ea3a5666785401e9a8696db687e1318bbc104ca7#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R270 for the issue https://github.com/ymcatwincities/openy/issues/687
cc @YMCA-GTC , @podarok

**Comment by YMCA-GTC** [comment]
I have notified Andrii and IXM. Agreed that this is critical and needs to be fixed ASAP.

**Comment by ddrozdik** [comment]
Fixed in https://github.com/ymcatwincities/openy/releases/tag/8.1.12.3 version
