### ISSUE TITLE
Fix "Secondary description and sidebar" for Rose theme 

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1157]
Page header area:
* Small banner paragraph
* "Secondary description and sidebar"  paragraph

![image](https://user-images.githubusercontent.com/4558228/42337808-7d8a34be-8090-11e8-97fa-7864a54996ca.png)

Example is setup at: http://sandbox.openymca.org/paragraphs

Here is how it looks in Lily theme:
![image](https://user-images.githubusercontent.com/4558228/42338008-1a10507a-8091-11e8-9f98-2f5ade286748.png)

Also I guess that inclined line in the "Secondary description and sidebar" shouldn't cross the text in the right column. 
And Inclined line should go between Left and right columns.

**Comment by ymcagtc** [comment]
Agreed - assigning to IXM

**Comment by SanyokMedved** [comment]
@AlexNetman Please explain how reproduce this issue. What kind of paragraphs are you using for this example? 

Thank you

**Comment by YMCA-GTC** [comment]
@AlexNetman Do you have an update to @SanyokMedved 's question above?

**Comment by AlexNetman** [comment]
@SanyokMedved I hoped it could be understood from screenshot.
"Small banner" and "Secondary description and sidebar"

**Comment by kolesnikoff** [comment]
Fixed by @SanyokMedved https://github.com/ymcatwincities/openy/pull/1313

**Comment by ddrozdik** [comment]
@AlexNetman please review and close if this is fixed.

**Comment by paige-kiecker** [comment]
@podarok can this be closed?
