### ISSUE TITLE
Small banner: Image is cut in unexpected manner

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1158]
http://sandbox.openymca.org/paragraphs
![image](https://user-images.githubusercontent.com/4558228/42369524-e55df350-8112-11e8-8c92-348de9835637.png)

Image can be located in same manner that is on Program Subcategory pages.
![image](https://user-images.githubusercontent.com/4558228/42369590-18e866b0-8113-11e8-9c3f-38955eb08701.png)
Which is much better. (but still head is cut in the example)
http://sandbox.openymca.org/programs/swimming/drop-swim?location=All

**Comment by ymcagtc** [comment]
@AlexNetman Have you tried using the Image Focal Point settings to see if you're able to resize and refocus the images appropriately?

**Comment by paige-kiecker** [comment]
This has been resolved with the enhanced Focal Point tool in 2.3.0
