### ISSUE TITLE
Add padding after Membership Calculator paragraph

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1159]
When I added a test paragraph under Membership Calculator
Then It appeared on the same level as button.
![image](https://user-images.githubusercontent.com/4558228/42396923-72a8cede-816c-11e8-9a5b-3452447f4a6a.png)

But "next" button shouldn't overlap with content below
Please, add some spacing 
so that nothing else is displayed in row with "Next" button

**Comment by ymcagtc** [comment]
Assigning to IXM for resolution

**Comment by kolesnikoff** [comment]
Fixed by @SanyokMedved https://github.com/ymcatwincities/openy/pull/1314
