### ISSUE TITLE
Local video player doesn't have border on table

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1164]
Video player for location doesn't have any border in Safari. Which looks strange on iPad.
![image](https://user-images.githubusercontent.com/1316234/42498828-ea062c44-8435-11e8-9e3e-a7c090a055d5.png)

**Comment by ymcagtc** [comment]
5% of traffic for most Y sites is on iPad and video usage as a percentage of pages is low. While important, the severity of this is normal. We will eventually resolve this.

**Comment by sarah-halby** [comment]
Due to the low volume of usage, we will keep this item in the backlog for now.
