### ISSUE TITLE
Membership type selection doesn't trigger scroll down

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1165]
I'm not quite sure if OpenY had that feature, but it will be nice to fix that.

When we select membership type on the Join page, it's not intuitive to scroll down manually to click "Next" button. Here's an example how UX may be improved - https://www.seattleymca.org/membership.

**Comment by ymcagtc** [comment]
Thanks, @Sanchiz I agree with you that this is a worthwhile change. It is not technically a bug, however. I will add it to the roadmap.

**Comment by ymcagtc** [comment]
FYI here is the roadmap item: https://trello.com/c/ALxhy5Iv/134-membership-selection-auto-focus-score-6

**Comment by paige-kiecker** [comment]
Closing out this enhancement request as it's on roadmap (https://trello.com/c/ALxhy5Iv/134-membership-selection-auto-focus-score-8)
