### ISSUE TITLE
Upload font during installation step

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1173]
It seems that custom module openy_font has been replaced with http://sandbox.openymca.org/admin/appearance/font.

Installation steps should be updated accordingly https://github.com/ymcatwincities/openy/blob/8.x-1.x/src/Form/UploadFontMessageForm.php#L28.

**Comment by ymcagtc** [comment]
Agreed - assigning to IXM.

**Comment by SanyokMedved** [comment]
@Sanchiz Please check if installation steps hasn't updated before. As I can see new link is correct and is linked as in Form. If it is not correct - let me know about it. Thank you.

**Comment by YMCA-GTC** [comment]
@Sanchiz Once you're fully back in the office and caught up, please give us an update on this one. Thank you!

**Comment by alexschedrov** [comment]
@SanyokMedved @YMCA-GTC Hi! The text and link have been updated, however, it still uses a screenshot from the legacy page for uploading fonts.

![image](https://user-images.githubusercontent.com/1316234/46871483-3c4e7580-ce3a-11e8-9fc0-a658adcfe7d5.png)

**Comment by YMCA-GTC** [comment]
Asking IXM for an estimate
