### ISSUE TITLE
Filter by miles

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1195]
It seems that filter by miles doesn't work correctly.

![image](https://user-images.githubusercontent.com/1316234/43464489-e5403c72-94e3-11e8-9ea2-37ecbaca3113.png)

**Comment by ymcagtc** [comment]
Updated the tutorial for Google Maps API for Open Y which resolves this issue: https://community.openymca.org/t/new-google-maps-api/134/10
