### ISSUE TITLE
Filter by ZIP or address doesn't work without Geocoding API

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1196]
When Google Maps API pricing has been changed, it seems that they've disconnected various services from each other. There's one additional step is required - enable Geocoding API. It may be enabled here - https://console.developers.google.com/apis/library.

![image](https://user-images.githubusercontent.com/1316234/43464701-6d1dd4d8-94e4-11e8-9479-ccade0114e27.png)

Video lesson for Google Maps should be extended - https://community.openymca.org/t/new-google-maps-api/134.

![image](https://user-images.githubusercontent.com/1316234/43464561-1722c764-94e4-11e8-929e-c21dd284fac3.png)

**Comment by ymcagtc** [comment]
Thank you - tutorial instructions have been updated to reflect this: https://community.openymca.org/t/new-google-maps-api/134/10
