### ISSUE TITLE
Header in Open Y Rose overlaps some elements on pages

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1201]
I noticed that in some situations I can't click on the Location title in the popup on the /locations page. 
![locations site-install 2018-08-08 18-00-07](https://user-images.githubusercontent.com/6285570/43845552-ee822cda-9b34-11e8-8d15-567ac329b6f3.png)
After an investigation, I found that the header section, where the main menu is placed, has a wrong height in the collapsed mode(when we scroll the page down)
![locations site-install 2018-08-08 18-01-20](https://user-images.githubusercontent.com/6285570/43845664-262682e4-9b35-11e8-87aa-0686f291d6a9.png)
It is set to be 165px when it actually should be about 50px. 
Due to this situation this header overlaps some area on the page and do not let to click on clickable elements 
![monosnap 2018-08-08 18-04-00](https://user-images.githubusercontent.com/6285570/43845847-9c005e0e-9b35-11e8-821a-9589c3b4e1f5.png)
cc @YMCA-GTC , @podarok

**Comment by ymcagtc** [comment]
Agreed - issue to be assigned to IXM. Thanks!

**Comment by YMCA-GTC** [comment]
@ddrozdik This should have been resolved with 1.13.1. If you find that it is still a problem, please let me know and I will reopen the ticket.
