### ISSUE TITLE
Decoupling issues:

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1211]
I tried disabling some modules from UI: 

/admin/modules/uninstall

1) It turns out that I can't easily to turn off  group of modules.
For example I need 5 iteration to uninstall "OpenY Demo ..." modules.
Because some of them have dependencies between each other.

2) Module Daxko should not have reference to Membership Calc module.

3) "OpenY camp" should not be required by "OpenY Paragraph Location Finder"

**Comment by ymcagtc** [comment]
Assigned @Sanchiz to resolve this

**Comment by anprok** [comment]
Issue fixed in referenced PRs.
