### ISSUE TITLE
Upgrade path for new carnation theme

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#1229]
I encountered a problem during the upgrade OpenY to 8.1.13.
Issue on `openy_update_8061 - Upgrade path for new carnation theme` -https://github.com/ymcatwincities/openy/blob/8.x-1.x/openy.install#L922

On our project not used news content type, so `openy_node_news` is disabled. But during this update was imported config `core.entity_view_display.node.news.teaser` from `openy_node_news/config/install/` directory. As result I got errors on any config import and failed rest of updates:

```
Drupal\Core\Config\ConfigImporterException: Configuration <em class="placeholder">core.entity_view_display.node.news.teaser</em> depends on configuration (<em class="placeholder">field.field.node.news.field_content, field.field.node.news.field_meta_tags, field.field.node.news.field_news_category, field.field.node.news.field_news_description, field.field.node.news.field_news_image, field.field.node.news.field_news_location, field.field.node.news.field_news_related, field.field.node.news.field_sidebar_content, node.type.news</em>) that will not exist after import. in Drupal\config_import\ConfigImporterService->import() (line 328 of /var/www/docroot/modules/contrib/confi/src/ConfigImporterService.php)
```

Proposed solution: Split update `openy_update_8061` and move to the appropriate modules.

**Comment by ymcagtc** [comment]
@Sanchiz Can this be part of the decoupling work you are doing? If so, let's assign this to you. If not, please let me know. Also, I need to know what we should do it the short-term to help @hamrant resolve this issue for his current build. Thanks!

**Comment by jediandrey** [comment]
https://github.com/ymcatwincities/openy/pull/1234

**Comment by anprok** [comment]
Issue fixed and merged to 8.x-1.x
