### ISSUE TITLE
Vuejs error invalid expression in openy_repeat

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#1232]
I have checked openy_repeat in new OpenY 8.1.13 version and `Repeat Schedules` paragraph was completely empty. After some investigation I have found reason:

```
- invalid expression: missing ) after argument list in

    { hidden: categoryExcluded('Parent's Night Out') }

  Raw expression: v-bind:class="{ hidden: categoryExcluded('Parent's Night Out') }"
```

Issue on this line in `openy-repeat-schedule-dashboard--sidebar.html.twig`:
```
<input type="checkbox" v-model="categories" v-bind:class="{ hidden: categoryExcluded('{{ category }}') }" value="{{ category }}" id="cb-{{ category|lower|replace(' ', '-') }}" class="box" {{ cat_checked }}>
```

If category contain `'` symbol this broke all vue app.

Steps for reproduce:
- Add category `Parent's Night Out`
- for debug use `openy_repeat/js/vue/vue.js` instead of `vue.min.js`

**Comment by hamrant** [comment]
As temporary quick fix I have used this code:
```
v-bind:class="{ hidden: categoryExcluded('{{ category|replace("'", '`') }}') }"
```

**Comment by ymcagtc** [comment]
Has been assigned to IXM to resolve
