### ISSUE TITLE
Property or method is not defined

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#1235]
During investigation of this issue - https://github.com/ymcatwincities/openy/issues/1232 I have found another one.

For debug I have switched from `vue.min.js` to `vue.js` and got this errors in console:
```
[Vue warn]: Property or method "addToCalendarDate" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```
```
[Vue warn]: Error in render: "TypeError: addToCalendarDate is not a function"
```

results component is empty with  `addToCalendarDate` error. I have commented this lines in `openy-repeat-schedule-dashboard--table.html.twig`

```
                <var class="atc_date_start">${ addToCalendarDate(item.time_start_calendar) }</var>
                <var class="atc_date_end">${ addToCalendarDate(item.time_end_calendar) }</var>
```

And then got next errors on class link click:
```
[Vue warn]: Property or method "populatePopupC" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

```
Uncaught TypeError: populatePopupC is not a function
```

Looks like functions from parent component unavailable inside results component. Anyway this works fine with `vue.min.js` file, but I think better to double check.

**Comment by ymcagtc** [comment]
@podarok Should this go to IXM or to you? Please let me know. Thanks!

**Comment by podarok** [comment]
On IMX

**Comment by kolesnikoff** [comment]
Fixed by @denisbilchenko in https://github.com/ymcatwincities/openy/pull/1321

**Comment by podarok** [comment]
Fixed
