### ISSUE TITLE
Repeat Schedules performance

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#1236]
I have tested new Repeat Schedules paragraph and it works very slow, even despite the fact that I have a small number of generated repeat entities.

I think this can be related to `RepeatController`. In `getClassesInfo` function loads all site classes, in my case - 3626 classes.

![screenshot from 2018-08-17 17-12-16](https://user-images.githubusercontent.com/13733670/44272090-8ead5480-a244-11e8-88ec-2d89f51fb158.png)

I think we can get list of classes ID's in `ajaxScheduler` from `$result` and load only this classes.

**Comment by ymcagtc** [comment]
@ygerasimov Was this the bug you just fixed? If so, hopefully, we can get this in a point release in a few days/week.

**Comment by hamrant** [comment]
Fixed in https://github.com/ymcatwincities/openy/pull/1241
