### ISSUE TITLE
Date filter cannot be deleted on the Schedules page

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#1251]
When I go to the Schedules page, a specific time is selected, so I see date chosen is displayed as a filter with an 'X' symbol next to it. 
https://cl.ly/422429c76254

Expected: I expect date filter to be deleted when 'X' is clicked.

Actual: Date filter doesn't get deleted when 'X' is clicked. Page refreshes and remains the same.

**Comment by YMCA-GTC** [comment]
Agree - important. Will assign to IXM to resolve

**Comment by YMCA-GTC** [comment]
This is the old schedules experience - @akaleMulder can you verify which version of Open Y this is on? This should be resolved with 1.13.

**Comment by YMCA-GTC** [comment]
Closing for now - will reopen if this is happening on 1.13 or later.
