### ISSUE TITLE
Location map icons save in config full site path with domain which brake path between environments

### ISSUE THREAD

**Issue by Fant0m771** [ymcatwincities/openy#1256]
Location map icons save in config full site path with domain which brake path between environments  - http://take.ms/2k8Y9

**Comment by Fant0m771** [comment]
PR with patch here - https://github.com/ymcatwincities/openy/pull/1257

**Comment by YMCA-GTC** [comment]
@podarok Could you help me with the next steps on this one, please?

**Comment by Fant0m771** [comment]
hi @podarok, 
Sure, what do you have for me?

**Comment by podarok** [comment]
@Fant0m771 
Could you please fix issue with storing absolute urls into config? Would be cool to store relative paths and check if it doesn't break functionality

**Comment by Fant0m771** [comment]
Hi @podarok , 
Provided patch https://github.com/ymcatwincities/openy/pull/1257 already fix storing relative url's into config. Do you mean storing paths on module install state ?

**Comment by anprok** [comment]
PR merged. Issue can be closed,
