### ISSUE TITLE
Cannot close modal window on mobile

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#1269]
On mobile, when you click on the class name the modal window appears but you can’t close it. This is frustrating for mobile users.
For example, open [this](https://www.ymcagbw.org/schedules/group-exercise?date=5%20Sep%202018&locations=West%20Chester%20Branch&categories=) link on mobile phone and click on Cycle 45 class.

**Comment by YMCA-GTC** [comment]
I consider this a critical bug. Will assign to IXM for fixing.

**Comment by jediandrey** [comment]
Bug related only to Brandywine theme. PR with a fix has been created in YGBW repo.

**Comment by akaleMulder** [comment]
Project Specific issue.
