### ISSUE TITLE
Bug on the new schedules pages with room filters

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#1270]
There seems to be a bug on the new schedules pages with room filters. See screenshots:
![image](https://user-images.githubusercontent.com/2506214/45161544-f3d5e380-b20d-11e8-88b3-e375f5226f69.png)
The default view for Kennett Group X classes (no room selected) would be this. ￼We select **Weigh in Wednesday** and the pop up appears as it should.
![image](https://user-images.githubusercontent.com/2506214/45161569-06501d00-b20e-11e8-90bd-08d2e6d6d8b7.png)
￼
When we filter by room...
![image](https://user-images.githubusercontent.com/2506214/45161610-17992980-b20e-11e8-9fda-56a9bb34160e.png)

And then click on Cycle, we receive the same Weigh in Wednesday wording. 
￼
![image](https://user-images.githubusercontent.com/2506214/45161628-1d8f0a80-b20e-11e8-8186-2cbec50b9351.png)

It doesn't seem to be happening with Categories but still happens when more than one branch are selected with rooms.

**Comment by YMCA-GTC** [comment]
Marked as important. Will assign to IXM

**Comment by SanyokMedved** [comment]
Cannot reproduce. Please retest. Checked on http://sandbox.openymca.org

**Comment by akaleMulder** [comment]
@SanyokMedved I just got a confirmation that this issue has been resolved. Sorry for bothering and thank you!
