### ISSUE TITLE
Add to Calendar on new Schedules has wrong timezone

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1272]
I’ve noticed that “Add to Calendar” has hardcoded timezone, so it works incorrectly when a website has timezone different from CT.

Code: https://github.com/ymcatwincities/openy/blob/8.x-1.x/modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--table.html.twig#L80

![image](https://user-images.githubusercontent.com/1316234/45166739-63dd6d00-b200-11e8-9a5e-752ff383fec2.png)

**Comment by jediandrey** [comment]
https://github.com/ymcatwincities/openy/pull/1274

**Comment by ygerasimov** [comment]
fixed
