### ISSUE TITLE
Header Image scaling issue on program pages in the Lily theme

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#1275]
Working further with the openy_lily theme, we found that most of the images on the program headers were appearing "squished" for users on smaller desktop screens.  This happens on both the program and program subcategory content types.

I believe it's because the height of the image is hard-coded while the width is set to 'auto', which causes the width of the image to scale for smaller desktop screens until it disappears for mobile screen sizes (around 990px).  Because the width is fluid and the height is static, it results in a "squished" image.

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/32372465/45244967-c47faf00-b2bf-11e8-9437-2719a76178e8.png">

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/32372465/45245169-dc0b6780-b2c0-11e8-9215-caf0b58de774.png">

**Comment by jwtechdesign** [comment]
After some troubleshooting, it looks like the image is inheriting a `max-width: 100%` from the `.img-responsive` class (to be expected).  But since we're hard-coding the height, that won't work.  I would suggest allowing the width of the image to go beyond the width of the container (to always fill the height of the header), then hide the overflow.  

Adding the following 2 lines to the `.program-header .content .image img` selector fixes it for me (overriding the max-width and keeping the image right aligned so that the overflow is always on the left toward the title bar):

`
.program-header .content .image img {
  max-width: none;
  float: right;
}
`

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/32372465/45245717-33aad280-b2c3-11e8-998c-c2cfbbd8a645.png">

The isn't a perfect fix, however, since it doesn't center the image as the screen scales.  So if there's other recommendations or solutions, please let me know!

**Comment by YMCA-GTC** [comment]
@jwtechdesign I'm good with your fix for now - are you willing to make a submission with this fix as a pull request? If you need any assistance or details, please let me or @podarok know. Thank you for catching this!

**Comment by YMCA-GTC** [comment]
@jwtechdesign Do you have an update on if you're able to take this on? If not, let us know and we can find a dev for it.

**Comment by jwtechdesign** [comment]
Sorry for the delay on this.  Submitted a PR a few moments ago ([here](https://github.com/ymcatwincities/openy/pull/1346)) - please let me know if I've done that correctly or if you need anything updated - will be glad to do so.  Thanks.

**Comment by podarok** [comment]
Thank you @jwtechdesign 
Fixed
