### ISSUE TITLE
Carnation location page map displays over the breadcrumbs

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1298]
To reproduce, go to the sandbox, set Carnation as the default theme, go to the location page, clear the alerts and notice that the breadcrumbs are covered (see attached)

![image](https://user-images.githubusercontent.com/17653329/45521943-eaa4c380-b785-11e8-8d13-69374142c999.png)

**Comment by kolesnikoff** [comment]
Fixed by @aaronjchristian in https://github.com/ymcatwincities/openy/pull/1303

**Comment by paige-kiecker** [comment]
@podarok can you confirm this fix?

**Comment by paige-kiecker** [comment]
This has been resolved. Closing out
