### ISSUE TITLE
Add to Calendar section showing errant data on Lily schedules

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1300]
Go to Sandbox and look at Group Exercise schedules on Lily. Note that the area near add to calendar has a lot of errant data that should not be displaying. Compare to Rose. See attached.

![image](https://user-images.githubusercontent.com/17653329/45523070-bd0f4880-b78c-11e8-9d6d-879fa020f30d.png)

**Comment by kolesnikoff** [comment]
Fixed by @denisbilchenko in https://github.com/ymcatwincities/openy/pull/1304

**Comment by podarok** [comment]
Fixed. Will be tagged in next point release
