### ISSUE TITLE
Errors when activating a child theme. References to assets are hard coded into the parent theme

### ISSUE THREAD

**Issue by mikemuller** [ymcatwincities/openy#1306]
When activating a child theme, there are references to assets that are hard coded into the parent theme, causing errors. Here is the error that occurs:
Twig_Error_Loader: Template "themes/custom/grymca/img/icons/quote_purple.svg" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "themes/custom/grymca/img/icons/quote_purple.svg" in the Drupal theme registry.) in "profiles/contrib/openy/themes/openy_themes/openy_lily/templates/node/node--blog--teaser.html.twig" at line 115. in Twig_Loader_Chain->getCacheKey() (line 129 of /Users/mikemuller/OpenY/GRYMCA/vendor/twig/twig/lib/Twig/Loader/Chain.php).

**Comment by YMCA-GTC** [comment]
Assigned to IXM for resolution

**Comment by SanyokMedved** [comment]
What parent theme is for grymca theme? I can't find it in branches. 
May be is could be good practice leave assets in child theme when user try create it?

**Comment by SanyokMedved** [comment]
In progress.

**Comment by kolesnikoff** [comment]
Fix is here https://github.com/ymcatwincities/openy/pull/1317

**Comment by podarok** [comment]
Thanks, fixed
