### ISSUE TITLE
GroupExPro integration. Drush command

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#1308]
We need to provide a way to run GroupExPro import as a drush command so it can be scheduled every day for example.

**Comment by YMCA-GTC** [comment]
@ygerasimov Is taking this issue that @ygerasimov reported :)

**Comment by YMCA-GTC** [comment]
@ygerasimov can we please get an update on this one? Thanks!

**Comment by ygerasimov** [comment]
Pull request with this request has been merged. So issue can be closed.
