### ISSUE TITLE
Line Above option doesn't connected to Carnation theme behavior

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1310]
![image](https://user-images.githubusercontent.com/563412/46006679-c4095580-c0c0-11e8-9130-136e08257b1a.png)
Line is rendering no matter if checkbox is set or no
![image](https://user-images.githubusercontent.com/563412/46006772-f61ab780-c0c0-11e8-8272-cb9a6efa4a80.png)

**Comment by YMCA-GTC** [comment]
Good catch - assigning to you to fix :)

**Comment by SanyokMedved** [comment]
in progress

**Comment by kolesnikoff** [comment]
Fixed by @SanyokMedved in https://github.com/ymcatwincities/openy/pull/1320

**Comment by ddrozdik** [comment]
@podarok, @kolesnikoff can it be closed?

**Comment by podarok** [comment]
done, thanks
