### ISSUE TITLE
Сan not uninstall the OpenY Faq module

### ISSUE THREAD

**Issue by anprok** [ymcatwincities/openy#1315]
The following reason prevents OpenY Faq (openy_prgf_faq) from being uninstalled:
- The Faq field type is used in the following field: paragraph.field_qa

https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/openy_features/openy_prgf/modules/openy_prgf_faq
Faq is custom field type that defined in openy_prgf_faq. Also in this module located configuration files for paragraph and a field that uses faq field type. It looks like this prevents the uninstallation of the module.
I propose to place the paragraph configuration files and source code for field type Faq in two different modules.

**Comment by YMCA-GTC** [comment]
@Sanchiz @ddrozdik Are you guys going to take this as part of the decoupling work?

**Comment by ddrozdik** [comment]
@YMCA-GTC yes. We posted it here just to be sure we will not forget about this issue.

**Comment by YMCA-GTC** [comment]
@ddrozdik Awesome! Thank you!

**Comment by anprok** [comment]
Fixed in 8.x-2.x.
