### ISSUE TITLE
Placeholders instead of data

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#1319]
When we open new Schedule, for a brief moment we see placeholders instead of data.

1. Go to [https://www.ymcagbw.org/schedules-beta](https://www.ymcagbw.org/schedules-beta)
2. Select any location, e.g. Kennett Branch: [https://www.ymcagbw.org/schedules/group-exercise/location](https://www.ymcagbw.org/schedules/group-exercise/location) and click Next
3. For a brief moment you will see placeholders instead of real data. See screenshot.
<img width="1271" alt="screen shot 2018-09-18" src="https://user-images.githubusercontent.com/2506214/46334501-2bd21a00-c646-11e8-9c30-9dc4679e390e.png">

**Comment by YMCA-GTC** [comment]
Assigning to IXM for resolution

**Comment by kolesnikoff** [comment]
Fixed by @denisbilchenko in https://github.com/ymcatwincities/openy/pull/1327

**Comment by AlexNetman** [comment]
retest this please

**Comment by akaleMulder** [comment]
Thank you. Works fine now.
