### ISSUE TITLE
Schedules display in Lily show errant info in the "Add to Calendar" area

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1322]
The Lily display of schedules has some text that displays improperly next to the Add to Calendar link. Compare Lily to Rose below. Rose is the correct display.

![image](https://user-images.githubusercontent.com/17653329/46375246-84121780-c658-11e8-94d4-9ed6f88c0197.png)

![image](https://user-images.githubusercontent.com/17653329/46375225-75c3fb80-c658-11e8-88af-9b9d382e61b5.png)

**Comment by kolesnikoff** [comment]
@YMCA-GTC isn't it the same issue as https://github.com/ymcatwincities/openy/issues/1300 ?

**Comment by YMCA-GTC** [comment]
Ah yes - thanks @kolesnikoff sorry about that. I'll close this.
