### ISSUE TITLE
New schedules: Improve date display

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1325]
On recently created schedules date period is unclear
URL: http://sandbox.openymca.org/swim
![image](https://user-images.githubusercontent.com/4558228/46461309-0fa9b680-c7c7-11e8-9d86-ace574d489c1.png)
Actual session time is set as 6AM to 7PM
But appear as 6:00 - 7:00 PM
Which makes me think it is from 6:00PM to 7:00PM

**Comment by YMCA-GTC** [comment]
Hi @AlexNetman Thank you for the feedback. We are trying to keep the display there as efficient as possible for mobile devices, and any additional characters makes it hard to display on a mobile device in portrait mode. This is why we added the "13h" under the time, to make it clear that the duration is 13 hours long, thus the 6:00 must be referring to AM vs PM. That said, I will leave this enhancement request open if anyone else wants to take a crack at changing it if they can get it to look good on mobile.

**Comment by YMCA-GTC** [comment]
Will be resolved with the v2 variation of schedules that is about to undergo AB testing. Hopefully in the distribution before Q2 next year. Closing for now.
