### ISSUE TITLE
New schedules: Hide placeholder

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#1326]
http://sandbox.openymca.org/swim

When page with schedules is loaded
I can see placeholder with code for a while
That makes me feel like error-blink

![image](https://user-images.githubusercontent.com/4558228/46463500-adec4b00-c7cc-11e8-8c2d-f5fc54cffbf3.png)
------------
Can we make it hidden in default template
And switching to visible only after actual value is loaded?
-------------

![image](https://user-images.githubusercontent.com/4558228/46463596-e9871500-c7cc-11e8-97f6-1412fc713531.png)

**Comment by kolesnikoff** [comment]
@AlexNetman this issue looks pretty the same as https://github.com/ymcatwincities/openy/issues/1319

**Comment by YMCA-GTC** [comment]
Agree - this is a duplication of https://github.com/ymcatwincities/openy/issues/1319 which will be fixed in the next release.
