### ISSUE TITLE
Schedules are not loading correctly in IE 11

### ISSUE THREAD

**Issue by jimparo** [ymcatwincities/openy#1332]
When viewing schedules in Internet Explorer 11 the page does not load correctly.

https://www.ymcagbw.org/schedules/lap-swim?date=8%20Oct%202018&locations=West%20Chester%20Branch&categories=

![image](https://user-images.githubusercontent.com/36908933/46621430-71cf2800-caf5-11e8-9270-847b19d12bb2.png)

**Comment by YMCA-GTC** [comment]
@jimparo Thank you. Assigning to 5J to fix.
