### ISSUE TITLE
User-friendly page title for PDF schedules

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#1335]
When a user wants to export a PDF, they see the tab name as 'get-pdf'. I suggest that we change it to a more user-friendly title like 'Download PDF schedule'

![image](https://user-images.githubusercontent.com/2506214/46806935-a90a3700-cd8a-11e8-93bf-f9dddf66cb15.png)

**Comment by YMCA-GTC** [comment]
Agreed. @paige-kiecker can you please add this to the roadmap?

**Comment by paige-kiecker** [comment]
Added to roadmap and linked here for reference. Closing out to reduce redundancies.
