### ISSUE TITLE
Empty page when no search results returned

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#1337]
When a user clicks on PDF link on a Schedules page with no results, they see an empty page without a table or anything else, just a blank page. It might be a good idea to disable the 'Weekly PDF Schedule' button when no results are returned.

**Comment by YMCA-GTC** [comment]
I agree - @paige-kiecker please add this to the roadmap.

**Comment by paige-kiecker** [comment]
Added to roadmap and linked here. Closing out the issue to reduce redundancies.
