### ISSUE TITLE
Google Translate: Issue with header when returning to original translation

### ISSUE THREAD

**Issue by jimparo** [ymcatwincities/openy#1338]
Steps to reproduce:

1. Translate the page into an alternative language:
![image](https://user-images.githubusercontent.com/36908933/46962676-bae12800-d071-11e8-8da0-56f4acdd09d8.png)
2. Click on the show original button in the header:
![image](https://user-images.githubusercontent.com/36908933/46962720-d2201580-d071-11e8-8d1c-0b4ec59666ce.png)
3. See the top portion of the header (login / select language) disappear behind the Google Translate toolbar:
![image](https://user-images.githubusercontent.com/36908933/46962777-fda30000-d071-11e8-8f59-42d91254dfc3.png)

**Comment by YMCA-GTC** [comment]
@jimparo We removed the Google Translate browser bar from the YGTC site. It resolves this issue and should be backported soon. Take a peek and let me know if you feel that this will work for you as the browser bar is redundant. https://ymcamn.org

**Comment by YMCA-GTC** [comment]
@podarok Let's get our feature of hiding the Google Translate browser bar backported into Carnation, Lily and Rose for the 1.14 release please.

**Comment by YMCA-GTC** [comment]
Also note the backport should include changing the design of the dropdown to what YGTC has so that it will work properly on mobile devices.

**Comment by paige-kiecker** [comment]
This has been resolved in the latest OY release, per @podarok
