### ISSUE TITLE
Setting Up Search Feature in Carnation Theme

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#1345]
After enabling the included `Search` module, the search feature in the main menu of Carnation & Rose (magnifying glass icon) still leads to a page 404.  After some research, here's how to fix it:

**[Step 1]**  Ensure that the "Search" module is enabled.  The D8 search module's default content search URL happens as `/search/node`, so ...

**[Step 2]**  I edited the code that placed that search icon in the main menu (file is located at `/templates/page/page.html.twig` for Carnation theme.  Change the `action` in Line 115 to `{{ base_path }}search/node`.

**[Step 3]** The current version of the Search module passes the "keys" parameter instead of "query".  This way the action request passes the correct search parameter, so I changed Line 117 from `<input type="search" name="query"...` to `<input type="search" name="keys"...`

Search functionality then works perfectly.  Hope that helps someone - if that's not the best practice, of course, please let me know and I'll update my solution.

**Comment by YMCA-GTC** [comment]
Assigning to IXM for resolution in Q1 2019

**Comment by SanyokMedved** [comment]
https://github.com/ymcatwincities/openy/pull/1698
