### ISSUE TITLE
Alerts visibility issues

### ISSUE THREAD

**Issue by nikitapogrebnyak** [ymcatwincities/openy#1351]
Limiting alerts visibility to certain pages doesn't work properly. If I open a page that is configured to show a particular alert immediately after I saved the alert node, I can see it appearing on the page. However, if I open another page which is not in the list and then I go back to allowed page, I don't see alert anymore.

**Comment by YMCA-GTC** [comment]
Marked as important. Assigned to IXM for resolution by the next release.

**Comment by anpolimus** [comment]
@nikitapogrebnyak this happens because there are no context filter logic at alerts view in case if reference field is not empty.

**Comment by anpolimus** [comment]
My first investigation results: this is totally caching issue.
Alert node update is not triggering update of view content.
We need to think a little bit about invalidation of views cache tags after node update.

**Comment by anpolimus** [comment]
My PR with fixes for this issue is merged here: https://github.com/ymcatwincities/openy/pull/1435
