### ISSUE TITLE
1.13.2 release issues

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#1353]
1. Wrong version in [openy.info.yml](https://github.com/ymcatwincities/openy/blob/8.1.13.2/openy.info.yml#L5)

2. Missed `openy_repeat.natsort` library (see [openy_repeat.libraries.yml](https://github.com/ymcatwincities/openy/blob/8.1.13.2/modules/custom/openy_repeat/openy_repeat.libraries.yml#L18))
```
openy_repeat.natsort:
  version: 1.0
  js:
    /libraries/alphanum/alphanum.js: {}
```
`library-davekoelle/alphanum` also should exist in composer.json:
```
    {
      "type": "package",
      "package": {
        "name": "library-davekoelle/alphanum",
        "version": "1.0.0",
        "type": "drupal-library",
        "dist": {
          "url": "https://github.com/AndreyMaximov/alphanum/archive/1.0.0.zip",
          "type": "zip"
        }
      }
    }
...
"require": {
  "library-davekoelle/alphanum": "1.0.0",


```
this fixed in https://github.com/ymcatwincities/openy/pull/1324

3. Composer.json has an incorrect version for the symfony/dom-crawler. Should be v4.1.3 instead of v3.4.12 - fixed https://github.com/ymcatwincities/openy/pull/1362

**Comment by YMCA-GTC** [comment]
@podarok Is this resolved?

**Comment by hamrant** [comment]
First item was fixed in next releases (8.x-1.14 and 8.x-2.0-beta.1).
2 and 3 items also fixed, so we can close this issue.
