### ISSUE TITLE
Project not supported (Message on Status Page)

### ISSUE THREAD

**Issue by algisinfo** [ymcatwincities/openy#1364]
Hello,

Why do I get this message, related to OpenY, on the update page of Drupal:
Project not supported: This project is no longer supported, and is no longer available for download. Disabling everything included by this project is strongly recommended!

Can I use OpenY with the latest stable version of Drupal (8.6.2 now)?

Thank you.
Sorry if this is not the place for this questions.
Can you point me to the right page to ask this questions if not here?

**Comment by podarok** [comment]
@algisinfo which project is not supported on your site, could you please provide more details?
Latest version of OpenY has no such message on Status Page, which I'm assuming you have some module/package outdated on your particular instance
We are work in progress for the updating Drupal Core from 8.4.x to 8.6.x and expecting it to be done Q1 next year. 8.4.x core still reliable and has LTS about security, so unless you need any features from 8.6 - we recommend to stay on current OpenY Drupal core for not fighting with regressions
![image](https://user-images.githubusercontent.com/563412/48050275-118ddd80-e1aa-11e8-8e16-d01d8c004d32.png)

**Comment by algisinfo** [comment]
OpenY appears as not supported on the updates page.
![openy_not_supported](https://user-images.githubusercontent.com/966364/48061132-9a1a7700-e1c6-11e8-93ec-3028dc74dd47.jpg)
Had just opened this page:
drupal_domain/admin/reports/updates

I have Drupal 8.3.2 now, as that is the one provided with the OpenY packadge.
Can you point to a page where I can find instructions on how to upgrate to 8.4.x and not go dirrectly to 8.6.2?

The 8.6.2 version of Drupal is presented as a security update:
https://www.drupal.org/project/drupal/releases/8.6.2
Sites on 8.5.x should update immediately to Drupal 8.5.8 instead, and plan to update to the latest 8.6.x release before May 2019.
Are the security problems solved by 8.6.2 implemented in 8.4.x somehow?

Thank you!

[later edit]
I can manually update Drupal to 8.4.8 but when updating the modules and then the database Drupal 8.6.0 is required.
When trying to update to Drupal 8.6.2 OpenY is not working anymore (as you mentioned already).
I don't understand how can you use OpenY.

**Comment by podarok** [comment]
Hi @algisinfo 
Please have a look in Wiki we have some helpful information for how to upgrade https://github.com/ymcatwincities/openy/wiki/OpenY-upgrade-how-to-for-Developers
I'd suggest to go version by version without skipping to get to latest OpenY
