### ISSUE TITLE
Promoting the Open Y community from within the Open Y distribution

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1367]
The idea came up after reading this blog post https://dri.es/promoting-the-drupal-community-from-within-the-drupal-software

I agree with Dries that this is a very good idea and this post has brought me to an idea create a similar thing in Open Y where will be a page `About Open Y`, its philosophy, key contacts, and list of key contributors(this could be a list of agencies and independent developers).

This idea has been discussed already between Five Jars and @YMCA-GTC some time ago. To make sure it will not be lost I post it here with an idea of how these pages could look like.

It does not make sense to invent a bicycle when there are good examples, which may be used in the Open Y distribution. See my vision how this could be done within the Open Y distribution. 

Open Y 2.0 brings a new unified menu structure for managing all Open Y Settings, see for details  https://github.com/ymcatwincities/openy/issues/1045, which may contain a new menu item `About Open Y` with 4 tabs on the page:

What's New
<img width="549" alt="open y - welcome to open y moqups 2018-11-07 13-56-41" src="https://user-images.githubusercontent.com/6285570/48127613-2eeba600-e295-11e8-8090-3437c5b4318e.png">

Credits
<img width="549" alt="open y - credits moqups 2018-11-07 13-57-09" src="https://user-images.githubusercontent.com/6285570/48127622-357a1d80-e295-11e8-98ca-268439799c82.png">

Open Source
<img width="549" alt="open y - open source moqups 2018-11-07 13-57-24" src="https://user-images.githubusercontent.com/6285570/48127636-3c089500-e295-11e8-9361-27197c7af1af.png">

Privacy
<img width="549" alt="open y - privacy moqups 2018-11-07 13-57-37" src="https://user-images.githubusercontent.com/6285570/48127646-43c83980-e295-11e8-8220-4eb44e8c829c.png">

_* all texts are just for example._ 

Any feedback is highly appreciated.

**Comment by ddrozdik** [comment]
cc @ygerasimov , @podarok , @Sanchiz , @AndreyMaximov, @YMCA-GTC, @ymcagtc, @danylevskyi

**Comment by podarok** [comment]
Great idea
Through release management I'm coming to the same thing, technically.
I guess this should be highly integrated with GitHub where we can pull all needed information automatically. I don't want us to spend a lot of time for updating this content.

**Comment by YMCA-GTC** [comment]
@ddrozdik Very good idea. I'll add this to our roadmap.

**Comment by YMCA-GTC** [comment]
Added to the roadmap here: https://trello.com/c/xVbRA6Eh/150-better-communication-of-product-roadmap-features-and-capabilities-score-6

**Comment by paige-kiecker** [comment]
Closing this out to reduce redundancy. Task is on roadmap linking back here 
https://trello.com/c/xVbRA6Eh/150-better-communication-of-product-roadmap-features-and-capabilities-score-6
