### ISSUE TITLE
Tutorial how to install Cachet

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1371]
Would be great to create tutorial how to upload Cachet font to the website.
Different themes use different names for font-family:
- Open Y Rose - "Cachet W01 Book"
- Open Y Carnation - "Cachet"
- Open Y Lily - "Cachet"

Given that, Rose's font family should be changed to "Cachet" and then single tutorial should be created.

**Comment by YMCA-GTC** [comment]
@Sanchiz Is this one that 5J would be willing to take on? Please let me know.

**Comment by alexschedrov** [comment]
@YMCA-GTC I see two solutions:

------------------------
1. Create documentation/video as is using "Cachet W01 Book" in Rose and Retention Campaign themes and "Cachet" on the other themes.

**Pros**
- Easy
- No changes in the code

**Cons**
- Inconsistency


----------------------
2. Fix the issue and use "Cachet" as the name and update all places where "Cachet W01 Book" is being used https://github.com/ymcatwincities/openy/search?q=%22Cachet+W01+Book%22&unscoped_q=%22Cachet+W01+Book%22

**Pros**
- Will be consistent across themes

**Cons**
- An upgrade path tutorial should be created for those Ys who use Rose and Retention themes
- It will require to perform code changes in CSS customizations that use legacy font name "Cachet W01 Book"

@YMCA-GTC let me know your thoughts on this.

**Comment by YMCA-GTC** [comment]
@Sanchiz Let's go with #1 for now as we will eventually merge the Rose and Lily themes someday hopefully.

**Comment by paige-kiecker** [comment]
This is now included during installation of multi-step form. @Sanchiz does that solve for this?

**Comment by alexschedrov** [comment]
@paige-kiecker the step is there, but it just says go to the form and upload font. There are no instructions on the font names, needed files (Bold, Italic, Regular) and etc. 

![image](https://user-images.githubusercontent.com/1316234/60280042-c9732500-990a-11e9-8ba4-9c0b7f0d7069.png)


Eventually for different themes uploaded font should have different names, and there's no documentation for that, so I proposed to record 1-2 minutes video to explain that for now.

**Comment by paige-kiecker** [comment]
@Sanchiz got it. I am going to put this in the backlog for now until we know more about the status of the Rose/Lily merger. Thanks for the update!

**Comment by paige-kiecker** [comment]
This functionality has changed. A tutorial video has been added to the roadmap to address the new workflow.
