### ISSUE TITLE
Carnation and JS aggregation

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1374]
When JS aggregation is enabled on the Carnation theme, then JS cannot properly process methods `Drupal.behaviors.openyMoveBanners`, `Drupal.behaviors.openyMoveBreadcrumbs` and `Drupal.behaviors.openyMoveHeaderAlerts`.

**Comment by YMCA-GTC** [comment]
Assigning to IXM for estimates

**Comment by paige-kiecker** [comment]
Resolved with 2.0.9 release
