### ISSUE TITLE
Carnation and search

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1375]
By default Carnation theme has search icon in the header. Since Open Y doesn't have search built-in, I suggest to suppress this icon.

![image](https://user-images.githubusercontent.com/1316234/48271423-fb4f7e00-e444-11e8-845e-0d94c336bd98.png)

**Comment by YMCA-GTC** [comment]
Asking IXM for an estimate on this one

**Comment by ddrozdik** [comment]
@YMCA-GTC this is fixed and merged already by FJ team.
