### ISSUE TITLE
Clean up excess of openy_schedules module

### ISSUE THREAD

**Issue by miroslav-lee** [ymcatwincities/openy#1390]
Remove non existent views "specific_alerts_block" of` SchedulesSearchForm.php` file.

![code](https://user-images.githubusercontent.com/24233384/48840273-3637a700-ed9f-11e8-9051-d4961e61fd4f.png)
![code](https://user-images.githubusercontent.com/24233384/48840312-4a7ba400-ed9f-11e8-8373-7ec908901440.png)

**Comment by YMCA-GTC** [comment]
@podarok @Sanchiz @ygerasimov Can I please get help from one of you on determining if this is a bug, or an enhancement, as well as the severity of this issue? Thank you

**Comment by podarok** [comment]
This code is deprecated, could be removed any time. Not used now at all, we've updated alerts to decoupled version.

**Comment by YMCA-GTC** [comment]
@podarok Is this something simple you can fix? I also want you to help me set the severity of this.

**Comment by podarok** [comment]
@miroslav-lee please review https://github.com/ymcatwincities/openy/pull/1719

**Comment by podarok** [comment]
Fixed in latest dev. Will be in next point release
