### ISSUE TITLE
Events in the Open Y Rose

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1399]
1. Let's make image as required field for event or adjust styles in the Open Y Rose
![image](https://user-images.githubusercontent.com/1316234/49724720-a2a51800-fc72-11e8-96f1-4902303618b3.png)

2. There's no spacing between event teaser on iPad Prod
![image](https://user-images.githubusercontent.com/1316234/49724741-b05a9d80-fc72-11e8-97e8-3df5904ec2f5.png)

3. Mobile/Table layout has two location icons
![image](https://user-images.githubusercontent.com/1316234/49724775-c8322180-fc72-11e8-98ef-f49103ca0eac.png)

**Comment by YMCA-GTC** [comment]
Good catch @Sanchiz I'll assign to IXM for estimates.
