### ISSUE TITLE
Two columns with Sticky Sidebar in Rose, Lily, Carnation does not work

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1403]
Layout "Two columns with Sticky Sidebar" in Rose does not work. It's basically same as Two columns with Sidebar, so Sidebar doesn't stick at the top of the page.

**Comment by YMCA-GTC** [comment]
Asking IXM for an estimate on this one. Agree that the severity is low.

**Comment by paige-kiecker** [comment]
This affects all 3 themes, not just Rose, per https://github.com/ymcatwincities/openy/issues/1101

Closing 1101 out to consolidate to this recent ticket.

**Comment by paige-kiecker** [comment]
This has been resolved!
