### ISSUE TITLE
Alerts issues - Scheduling inconsistencies

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1412]
Some Y associations have been reporting that alert content types are sometimes not displaying at the date and time that has been selected when the alert block has been scheduled for display.

This is not something happening across all sites - but enough have reported it that it justifies investigation.

**Comment by YMCA-GTC** [comment]
Assigning to IXM

**Comment by anpolimus** [comment]
Fix for this issue is under test here: https://github.com/ymcatwincities/openy/pull/1441
