### ISSUE TITLE
Remove deprecated 'entity.query' service from Drupal\openy_repeat\RepeatManager class

### ISSUE THREAD

**Issue by afi13** [ymcatwincities/openy#1421]
The `Drupal\openy_repeat\RepeatManager` class has a dependency on `entity.query` service which is deprecated in Drupal 8.3.0. 
But also the class has a dependency on the entity type manager service, so we can easily remove `entity.query` from the class and use entity type manager instead.

**Comment by ddrozdik** [comment]
@ygerasimov @kolesnikoff  FYI  ^^ 
cc @podarok

**Comment by podarok** [comment]
go ahead and remove it

**Comment by YMCA-GTC** [comment]
@ddrozdik @podarok Did this end up getting resolved?

**Comment by ddrozdik** [comment]
@afi13 what the status of this issue?

**Comment by afi13** [comment]
Still not fixed.

**Comment by YMCA-GTC** [comment]
@afi13 You have my permission to make this change if you'd like :)

**Comment by podarok** [comment]
It's deprecated but will be removed in Drupal 9 only
```php
 * @deprecated in Drupal 8.3.0, will be removed before Drupal 9.0.0. Use
 *   \Drupal\Core\Entity\EntityStorageInterface::getQuery() or
 *   \Drupal\Core\Entity\EntityStorageInterface::getAggregateQuery() instead.
```
I guess we can live with this as is unless somebody has spare time to refactor it to the newer style

**Comment by sarah-halby** [comment]
@podarok confirming that this has been added to your testing log for Drupal 9 work per your comment on Aug 29, 2019? Have dependencies been tested and we are confirmed to remove this as a part of the Drupal 9 upgrade?

**Comment by sarah-halby** [comment]
This was completed for Drupal 8 & Drupal 9. It's already in the release. We will close this issue per @podarok.
