### ISSUE TITLE
Grid Content component in Carnation

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#1429]
Grid Content component doesn't use setting "Style" and just displays as many elements per row as created.

It should display exact about or items per row as selected in "Style" field.

![image](https://user-images.githubusercontent.com/1316234/50841723-00aa4580-136e-11e9-88df-c83a65264eaf.png)

**Comment by YMCA-GTC** [comment]
Assigning to IXM for resolution
