### ISSUE TITLE
PEF GroupEx Pro -- cancellations, substitutions

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#1439]
Current integration with GroupExPro doesn't handle cancellations nor substitutions. Would be great to implement these.

**Comment by YMCA-GTC** [comment]
Andrii - please backport this in for February from YGTC

**Comment by YMCA-GTC** [comment]
Andrii to discuss with @ygerasimov offline to ensure no conflicts

**Comment by YMCA-GTC** [comment]
To clarify - when a class is canceled, it will be removed from the schedule within a few minutes of the cancelation happening in the Group Ex system - once that data has synced to the schedule interface/PEF. 

For a class to display in schedules AFTER being canceled, the GroupEx content admin should simply rename the class as "Canceled" in parenthesis such as "Yoga (canceled)" to avoid customer confusion.

For substitutions, YGTC will backport our solution for this.

**Comment by paige-kiecker** [comment]
This has been resolved, per @podarok
