### ISSUE TITLE
CircleCI tests always failed

### ISSUE THREAD

**Issue by afi13** [ymcatwincities/openy#1443]
Hello,

Looks like CircleCI tests don't work anymore and always failed in PRs.
Example: https://circleci.com/gh/ymcatwincities/openy/1587?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It would be nice to fix them or completely remove. The current state is confusing.

**Comment by afi13** [comment]
@podarok @ddrozdik FYI

**Comment by YMCA-GTC** [comment]
@podarok can you please help me determine severity?

**Comment by podarok** [comment]
@Sanchiz could you remove circleci integration completely?

**Comment by alexschedrov** [comment]
@podarok @afi13 removal of `.circleci` in the root folder should disable integration.

**Comment by YMCA-GTC** [comment]
@podarok Can you please update this when you have a moment? Thank you!

**Comment by afi13** [comment]
The issue has been fixed already.
