### ISSUE TITLE
Use namespaced dependencies in .info.yml 

### ISSUE THREAD

**Issue by afi13** [ymcatwincities/openy#1446]
According to https://www.drupal.org/node/2000204 all dependencies should be namespaced in the format: {project}:{module} in .info.yml file. For example "drupal:file"

**Comment by YMCA-GTC** [comment]
@podarok can I get your insight on this one, please? Is this a bug, and what is the severity?

**Comment by podarok** [comment]
@afi13 I agree
Let's convert info files whenever we touch them in our PRs
No need to spend time specifically on optional thing

**Comment by YMCA-GTC** [comment]
@podarok Do we have documentation in our Wiki for this to establish the best practice? If so, let's close this out. Thanks!

**Comment by sarah-halby** [comment]
@YMCA-GTC per @podarok this is a Drupal core best practice and the documentation is available via Drupal.
