### ISSUE TITLE
How to update libraries in the repository?

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1447]
We need to update documentation for developers on how to work with libraries `drupal-library` from composer.json to support composer installation. 
At this moment whenever we add changes to the list of libraries in the openy `composer.json` we have to repeat similar changes in the https://github.com/ymcatwincities/openy-project. Otherwise, development builds will fail.

**Comment by YMCA-GTC** [comment]
Agreed - @podarok let's make this a priority. I'll add a basecamp ticket for you.

**Comment by podarok** [comment]
@ddrozdik could you share initial docs?

**Comment by ddrozdik** [comment]
can be closed, this is not relevant anymore, see https://github.com/ymcatwincities/openy/issues/1512 for details.
