### ISSUE TITLE
Open Y 2.0: New Alerts issues

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1451]
I found some issues with new ReactJs based alerts. 

1. Alert link changed position in comparison to the sandbox version. Is it ok? see screenshot below
![image](https://user-images.githubusercontent.com/6285570/51270641-8b2a1f00-19d6-11e9-82d6-315699c00c44.png)
2. Arrow Icons on the right side became a bit of grey and for a few pixels moved down, see screenshot above. 
3. In the console(Open Y Rose theme) I see errors and debug information: 
![image](https://user-images.githubusercontent.com/6285570/51272720-ef9bad00-19db-11e9-9c78-00062cd4b1d5.png)
4. see screenshot 
![image](https://user-images.githubusercontent.com/6285570/51273987-13142700-19df-11e9-9f95-27e8175be9a4.png)
5. see screenshot 
![image](https://user-images.githubusercontent.com/6285570/51274073-4656b600-19df-11e9-9988-eca74ab51c34.png)
6. Info message in logs. see screenshot 
![image](https://user-images.githubusercontent.com/6285570/51277039-7e61f700-19e7-11e9-8d27-83fdfac1087e.png)

**Comment by ddrozdik** [comment]
cc @podarok, @danylevskyi

**Comment by podarok** [comment]
@ddrozdik openy_node_js is deprecated script, should be removed
All other items - correct and need to get fixed before release

EDIT: item 6 is correct, why mentioned as a bug?

**Comment by podarok** [comment]
https://github.com/ymcatwincities/openy/pull/1458

Item 3 is fixed
Theming issues will be fixed next week @ddrozdik

**Comment by YMCA-GTC** [comment]
@podarok @ddrozdik I consider this important and would like to see it resolved for the Feb 12 release please.

**Comment by podarok** [comment]
@ddrozdik all issues fixed. Please check

**Comment by ddrozdik** [comment]
@podarok PR has been already merged. I suppose you have tested it. thanks.
