### ISSUE TITLE
iPad title headers in right sidebar are not responsive

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1452]
See screenshot 
![image](https://user-images.githubusercontent.com/6285570/51274267-c3822b00-19df-11e9-9826-d116b0e24c07.png)

URL: http://sandbox.openymca.org/programs/swimming

**Comment by ddrozdik** [comment]
Assigned to @fivejars

**Comment by ddrozdik** [comment]
this issue has been fixed in the 2.0 release.

**Comment by alexschedrov** [comment]
CC @YMCA-GTC
