### ISSUE TITLE
Branch (Today's) hours are being shown incorrectly

### ISSUE THREAD

**Issue by nikitapogrebnyak** [ymcatwincities/openy#1455]
Quite a few Y Centres have been complaining of "Today Hours" showing incorrect times during the weekend and at the beginning of the week. This happens because Drupal's render cache (and/or Varnish cache) keeps showing times from the previous day(s).

**Comment by podarok** [comment]
@nikitapogrebnyak 
This is not related to OpenY
Please ensure Varnish configured appropriately 
For the YGTC we have 1h Drupal cache ttl which gives us 2h maximum update time for Varnish

**Comment by nikitapogrebnyak** [comment]
@podarok
Well, from what I've heard from the Y centres' representatives, this is quite sensitive information, and "Today's Hours" must show correct times every time when visitor opens branch page, and therefore it should not depend on cache settings.
In case with YGTC - Cora McCorvey branch, for example. If cache has been invalidated on Saturday at 11:59pm, everyone who opens branch page on Sunday between 12am and 1:59am, they would still see and possibly plan their visit based on Saturday's hours, UNLESS they expand "All hours" block, of course. Otherwise, people would come on Sunday to a closed center.

**Comment by podarok** [comment]
@nikitapogrebnyak that's why we have 1 hour TTL
1h is enough for schedules as we found
not 1day

**Comment by podarok** [comment]
@nikitapogrebnyak another option - we have installed purge module to purge varnish cache on node update
Works like a charm

**Comment by YMCA-GTC** [comment]
If there is a code based fix for this, IXM will backport it for February release.

**Comment by nikitapogrebnyak** [comment]
@podarok "purge" indeed is a good module when the content depends on node update. In this case, however, "Today's Hours" doesn't require a node update. According to the name, it should be a dynamic element, which shows working hours based only on the moment of time when a visitor opens branch page.
@YMCA-GTC We do have a code-based fix for this issue. I'll find someone to create a pull-request.

**Comment by YMCA-GTC** [comment]
Thank you @nikitapogrebnyak much appreciated!

**Comment by bran** [comment]
Linking to PR: https://github.com/ymcatwincities/openy/pull/1521

**Comment by YMCA-GTC** [comment]
@podarok tells me this is resolved, so I am closing it for now.
