### ISSUE TITLE
How to work with PRs and builds?

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1459]
Based on feedback from people who joined development teams recently we see a lack of documentation that will provide basic information to answer such questions: 
- How to work with builds?
- How to create a build for my PR? 
- Why some builds are created automatically and some not? 
- When builds are deleted from the server?
- Who should I contact in order to get logs from the server? 
- Who should I specify for review? 
- Who is responsible for merging? 
- What labels in PRs should I use? 
- What milestone should I specify? 
- Why I can't add labels or specify milestone?

- Why Steps for review in Pull Requests are so important? 
- Why should I add a reference to the GitHub issue in my PR description? 
- In what format should I add commits, should I add internal Jira task ID or GitHub issue?
- What is deepcode bot? 
- What should I do if `CIBox tests`/`Accessibility tests`/`ci/circleci` are failed?

**Comment by ddrozdik** [comment]
cc @podarok , @YMCA-GTC

**Comment by podarok** [comment]
Working on this
Thank you

**Comment by podarok** [comment]
@ymcagtc @YMCA-GTC here is a doc https://3.basecamp.com/3608022/buckets/6003462/documents/1536605817 work in progress. Help reviewing it before posting in OpenY wiki

**Comment by podarok** [comment]
FAQ is initiated
Please check here
https://github.com/ymcatwincities/openy/wiki/Development-FAQ
