### ISSUE TITLE
Errors on configs import in 8.x-2.x

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#1462]
After merging new ReactJs based Alerts to the 8.x-2.x branch, we noticed errors which are related to alert blocks.
```
The configuration cannot be imported because it failed validation for the following reasons:
Configuration block.block.openy_rose_views_block__alerts_footer_alerts depends on the views.view.alerts configuration that will not exist after import.
Configuration block.block.openy_rose_views_block__alerts_footer_alerts_local depends on the views.view.alerts configuration that will not exist after import.
Configuration block.block.openy_rose_views_block__alerts_header_alerts depends on the views.view.alerts configuration that will not exist after import.
Configuration block.block.openy_rose_views_block__alerts_header_alerts_local depends on the views.view.alerts configuration that will not exist after import.
```
This issue brokes upgrade tool and config update/import. Also, I received feedback from developers who tried to test the 2.x update on several production websites and they noticed the same issue.

Steps to reproduce:
- [ ] Get fresh installation of Open Y 8.x-2.x
- [ ] Login as admin
- [ ] Go to /admin/config/development/configuration/single/import
- [ ] Import any config
- [ ] Check that you can see errors

**Comment by ddrozdik** [comment]
cc @podarok , @danylevskyi

**Comment by podarok** [comment]
Hi @hamrant and @ddrozdik 
This is weird and looks like unrelated

Please check 
https://github.com/ymcatwincities/openy/tree/8.x-2.x/themes/openy_themes/openy_rose/config/install
There are no block's configs you mentioned in your message
as well as here https://github.com/ymcatwincities/openy/tree/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_alert/config/install
no 
views.view.alerts
How did you get these configs in the database of freshly installed OpenY? Are you sure files, that were removed from repository aren't existing on your host machine?

**Comment by podarok** [comment]
Testing https://github.com/ymcatwincities/openy/pull/1463

**Comment by hamrant** [comment]
@podarok I got this during testing upgrade path from 8.x-1.x to 8.x-2.x with upgrade tool fixes.
And also on  OpenY 8.x-2.x fresh install. I will double check this now and I'll let you know if I find a specific reason.

**Comment by hamrant** [comment]
@podarok on 8.x-2.x fresh installation all works fine. So issue only on upgrade path from 8.x-1.x to 8.x-2.x. I will continue investigation and provide more details. Thanks for help.

**Comment by podarok** [comment]
@hamrant this definitely fixes one issue of having non needed panelizer dependency
https://github.com/ymcatwincities/openy/pull/1463
Please check

**Comment by hamrant** [comment]
@podarok Wow, thanks. Looks great, I will double check this on local and close this issue if all ok.

**Comment by podarok** [comment]
@hamrant and welcome to the club of Drupal config initiative haters.... )))

**Comment by hamrant** [comment]
@podarok I have checked upgrade path with your fix and all works as expected, thanks for help!
