### ISSUE TITLE
Layout issue in the amenities block on the Locations page

### ISSUE THREAD

**Issue by miroslav-lee** [ymcatwincities/openy#1474]
When I open the Location page with a width of 768 px, the Amenities block has some layout issues, see screenshot

![default](https://user-images.githubusercontent.com/24233384/51662743-d7bcbe00-1fc5-11e9-9c1f-3ad015ef3e5a.png)

**Comment by YMCA-GTC** [comment]
Thank you for the feedback. While I concede that this is ugly, it is a feature enhancement and not a bug as it is not preventing the site from being used. We will add it to our backlog.

**Comment by paige-kiecker** [comment]
This is on the roadmap after being previously reported via https://github.com/ymcatwincities/openy/issues/1152. CLosing out this one as it's on the roadmap!
