### ISSUE TITLE
Default font on Carnaton landing pages is purple when it should be black

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#1481]
See attached screenshots.

Reproduction steps:

- Start with a vanilla install of 1.14.1 Carnation
- Create new landing page
- In content area, create 1 column paragraph
- Add text such as "this is some sample text" in the paragraph description.
- Note that the font will appear purple when the page is loaded for both anon and authenticated users.

Expected behavior: font to appear black by default

![image](https://user-images.githubusercontent.com/17653329/51783062-7bf35180-20f9-11e9-8d7a-4b2e701464ef.png)

![image](https://user-images.githubusercontent.com/17653329/51783056-5cf4bf80-20f9-11e9-9540-c43746196c42.png)

**Comment by YMCA-GTC** [comment]
Assigning to IXM to resolve. Hoping to have this fixed for the 2/12 release.

**Comment by anpolimus** [comment]
@podarok What is your test workflow here?
Do I need to change status for this thicket? Please help.
Thank you.

**Comment by podarok** [comment]
@anpolimus if you see PR merged - feel free to close respective ticket if you see me failing to do that )))
