### ISSUE TITLE
Google Translate  breaks date header in schedules

### ISSUE THREAD

**Issue by KylieAldridge** [ymcatwincities/openy#1482]
Translating into a different language breaks the date header on schedules. The date selector in filters shows the correct date while the header doesn't not change. 
![image-5](https://user-images.githubusercontent.com/36514293/51868959-2048e400-2304-11e9-8c88-6f9a1ac44bd8.png)

**Comment by podarok** [comment]
@Shuklina @danylevskyi here is a code how to skip element from translation https://stackoverflow.com/a/9629628/3027445

**Comment by podarok** [comment]
@KylieAldridge are you working on the issue?

**Comment by KylieAldridge** [comment]
@podarok yes it's been assigned to @anpolimus internally!

**Comment by paige-kiecker** [comment]
This has been corrected; closing out
