### ISSUE TITLE
matchHeight library generates error in the admin panel and on some Open Y pages 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1484]
I noticed that after adding matchHeight library in the PR https://github.com/ymcatwincities/openy/pull/1477 on some pages on console there are errors from this line https://github.com/ymcatwincities/openy/pull/1477/files#diff-3923a2603d1958614d744ac3a5ecd12bR10

Steps to reproduce: 
1. Build a new Open Y 2.0 build
2. Login as admin 
3. Go to /admin/content page 
4. check the console(inspect code -> Console)
![image](https://user-images.githubusercontent.com/6285570/51916772-0e903b00-23ef-11e9-9a2e-27ec0da765d6.png)

P.S. I think does not make sense initialize reactjs scripts for alerts when we visit admin pages. Please think about this.

**Comment by ddrozdik** [comment]
cc @podarok , @danylevskyi

**Comment by podarok** [comment]
Fixed https://github.com/ymcatwincities/openy/pull/1490
