### ISSUE TITLE
Notice in alerts

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1496]
After upgrading YGTC site to the latest version we discovered a notice in logs, see below:
 
`Notice: Trying to get property of non-object in Drupal\openy_node_alert\Plugin\rest\resource\AlertsRestResource->get() (line 151 of /var/www/docroot/profiles/contrib/openy/modules/openy_features/openy_node/modules/openy_node_alert/src/Plugin/rest/resource/AlertsRestResource.php) `

**Comment by ddrozdik** [comment]
cc @podarok , @danylevskyi

**Comment by podarok** [comment]
fixed
