### ISSUE TITLE
UnexpectedValueException on event page due to incorrect date conversion

### ISSUE THREAD

**Issue by vitaly-malashevsky** [ymcatwincities/openy#1523]
There is a rare case when event page dies due to an unhanded exception `UnexpectedValueException - The created date does not match the input value.`, coming from here  https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.module#L59
This happens for the DST dates only. Eg: `2019-03-09T21:30:00 America/New_York` -> gets incorrectly converted to `2019-03-09T02:30:00` and does not match `2019-03-09T03:30:00` when **validate_format** is on.
The route cause of the problem is in wrong timezone usage during date creation. It should use `DATETIME_STORAGE_TIMEZONE` instead of user's timezone and when set to the latter for formatting purposes.

**Comment by YMCA-GTC** [comment]
@podarok Can you please help me assess the severity of this issue?

**Comment by podarok** [comment]
This is fixed in https://github.com/ymcatwincities/openy/pull/1524
