### ISSUE TITLE
Fix custom hardcoded behavior from YGTC 

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1536]
https://github.com/ymcatwincities/openy/commit/04184a6d2a7e5d7e8b33b76c0eac0de2bd8d4971

**Comment by AndreyMaximov** [comment]
https://github.com/ymcatwincities/openy/commit/19ea9f7630dfe36d969f2eb7c5d62acc767573a7

**Comment by AndreyMaximov** [comment]
https://github.com/ymcatwincities/openy/commit/348f391e4b838d34385e6e17e4609427c03054a5

**Comment by podarok** [comment]
Fixed
