### ISSUE TITLE
(Carnation) Update logo.svg

### ISSUE THREAD

**Issue by aaronjchristian** [ymcatwincities/openy#1543]
Update the themes logo.svg so we can apply the "fill" attribute on our path element when transitioning the navbar from a dark background to a light one, or vice versa.

**Comment by YMCA-GTC** [comment]
Hi @aaronjchristian I agree - I've added this to the roadmap. But I see you self-assigned this, does that mean you are taking this on and will contribute this change into Open Y? If so - thank you! If not, please let me know so I can make sure we get to it via other means.

**Comment by aaronjchristian** [comment]
Hi @YMCA-GTC, yes I have actually completed this for another Y project I am working on, I just need to find a bit of time to port it over. I should have some time next week to do so!

**Comment by YMCA-GTC** [comment]
That's great news @aaronjchristian Thank you very much for your help with this!

**Comment by paige-kiecker** [comment]
Hi @aaronjchristian, were you able to contribute this change to Open Y? I don't see a PR referenced on this issue so wanted to follow up. Thanks!

**Comment by sarah-halby** [comment]
@Sanchiz was this completed in the Carnation refactoring work recently completed? If so, could you comment & close out of this issue, please? @aaronjchristian did you contribute this previously? We are following up after @paige-kiecker's comment above.

**Comment by aleevas** [comment]
I've added a PR with fix https://github.com/ymcatwincities/openy/pull/2270
Needs to review

**Comment by sarah-halby** [comment]
@podarok since this item was added to the PR above, can it be closed out? Does this also fix this issue: Logo disappears on scroll on IE 11 on Carnation (again, this is a known issue, but my task is to list what I have found)? (Found during QA of last major release).  https://3.basecamp.com/3608022/buckets/9444393/todos/3178611215

**Comment by podarok** [comment]
IE11 definitely another task @sarah-halby 
This one considered as closed.
Thanks all!
