### ISSUE TITLE
Composer is locked on wrong versions

### ISSUE THREAD

**Issue by afi13** [ymcatwincities/openy#1544]
Looks like `composer.lock` file was not updated in the last release and we have a different version of packages in `composer.json` and lock files:

| composer.json                 | composer.lock        |
| ----------------------------- | -------------------- |
| `"drupal/core": "~8.6.10"`    | `"version": "8.6.7"` |
| `"drupal/paragraphs": "~1.6"` | `"version": "1.5.0"` |
| `"drupal/metatag": "~1.8"`    | `"version": "1.7.0"` |

As result impossible to install any package with composer because of conflict between `composer.json` and `composer.lock` files.
We should always update `composer.lock` file after any changes in `composer.json`. Or we should remove `composer.lock` file from the repo.

**Comment by YMCA-GTC** [comment]
@podarok Was this resolved? If so, please close this ticket. Thanks!

**Comment by podarok** [comment]
This was fixed. Thank you!
