### ISSUE TITLE
Add sourceMap files or remove references

### ISSUE THREAD

**Issue by AndreyMaximov** [ymcatwincities/openy#1546]
I found a couple of places where there are references to css/js source map files, but the files are missed.

https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js#L2
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/css/main.css#L2
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap.min.css#L6
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap-theme.min.css#L6

The references make web browsers to make additional requests to web servers thus involving Drupal core bootstrapping.

**Comment by podarok** [comment]
Fixed
