### ISSUE TITLE
groupex_form_cache__field_gfc_response grows a lot

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#1552]
On our site we have a lot of data in groupex_form_cache__field_gfc_response table. At some point module got enabled and takes a lot of space.

![image](https://user-images.githubusercontent.com/294265/54455791-e5ff9e80-4719-11e9-858b-8c1035bf3716.png)

For my case -- I am not using it at all and simply uninstalling it.

Suggest we have some cron job that cleans up these records regularly.

@podarok  please advise what you think.

**Comment by podarok** [comment]
@ygerasimov 
on YGTC site we are running groupex cache clear more often ( every 15 minutes ) to avoid database overload
```
drush ev '\Drupal::service("groupex_form_cache.manager")->resetCache(100);'
```
It is also described in respective module's README, how to deal with the module

**Comment by YMCA-GTC** [comment]
@podarok do we need to make a change to the code within Open Y for vanilla installs so they don't face this issue? If a default setting is causing a module to be enabled, that was otherwise intended to NOT be enabled, and that module is causing a problem for people such as taking up memory, then I consider it a bug.

**Comment by podarok** [comment]
@YMCA-GTC this is covered in respective README as part of how to use the module https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_group_schedules/modules/groupex_form_cache/README.md#how-to-clear-the-only-stale-cache
So could be closed
Let us know @ygerasimov if this needs something else
