### ISSUE TITLE
WSOD on the Map settings page

### ISSUE THREAD

**Issue by vitaly-malashevsky** [ymcatwincities/openy#1554]
There is an error while trying to access http://sandbox.openymca.org/openy/settings/openy_map related to the missing route **geolocation.settings** with the messsage: `Symfony\Component\Routing\Exception\RouteNotFoundException: Route "geolocation.settings" does not exist.`

The error comes from https://github.com/ymcatwincities/openy/blob/0f69ff3b551502254cf70a368260456bbe2b6e95/modules/custom/openy_map/src/Form/SettingsForm.php#L94-L100

and it's tied to the geolocation module upgrade, here is similar issue https://www.drupal.org/project/geolocation/issues/2978754

The new route should be **geolocation_google_maps.settings** and it belongs to a new sub-module now _geolocation_google_maps_ which has to be enabled to make sure route is accessible.

It might also needed to adjust access to the legacy map settings and change it to newer version `geolocation_google_maps.settings`, eg here:
https://github.com/ymcatwincities/openy/blob/0f69ff3b551502254cf70a368260456bbe2b6e95/modules/custom/openy_map/openy_map.module#L67

**Comment by YMCA-GTC** [comment]
I agree, this is critical. We are looking into a point release ASAP to resolve this.

**Comment by YMCA-GTC** [comment]
We are planning a point release to resolve this by March 27, 2019

**Comment by podarok** [comment]
fixed
