### ISSUE TITLE
Terms and Conditions triggers a warning after platform upgrade to v2.0

### ISSUE THREAD

**Issue by vitaly-malashevsky** [ymcatwincities/openy#1556]
We've just upgraded to v2.0 and got this warning in admin area:

> Warning: Parameter 3 to Drupal\openy\Form\TermsOfUseForm::buildForm() expected to be a reference, value given in Drupal\Core\Form\FormBuilder->retrieveForm() (line 518 of core/lib/Drupal/Core/Form/FormBuilder.php).

, coming from brand new [Terms of Use](https://github.com/ymcatwincities/openy/pull/1418) feature that was intended to popup during the site installation w/o problems.

![image](https://user-images.githubusercontent.com/8169225/54996493-1f65c300-4fd2-11e9-9939-ca492dea6c12.png)

In our case it gets called from a route `openy_system.openy_terms_and_conditions` and has no 3rd argument **$install_state** hence producing a warning.

As long as the form was intended to be used during profile installation and not using the 3rd argument, the easiest solution could be removing it from _**TermsOfUseForm::buildForm**_ declaration here 
https://github.com/ymcatwincities/openy/blob/42a96117bee4907cc121041e8fbade886515932b/src/Form/TermsOfUseForm.php#L56.

This simple fix does a trick very well!

**Comment by YMCA-GTC** [comment]
@Sanchiz @akaleMulder can you investigate this issue and resolve, please?

**Comment by YMCA-GTC** [comment]
5J has flagged the pull request for merging and we expect this to be resolved soon.
