### ISSUE TITLE
Failed to execute unzip on the MacOs during Open Y installation 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1564]
I've executed the command `composer create-project ymcatwincities/openy-project:8.2.x-dev  --no-interaction` to install Open Y and during installation, I noticed the following error
```
  - Installing ymcatwincities/openy (8.2.0.5): Downloading (100%)
    Failed to execute unzip -qq  'docroot/profiles/contrib/openy/c4da63e7920c706ce12d61d253ecb8d7.zip' -d '/Users/dmitry/Projects/fivejars/ymcatwincities/openytest/openy-project/vendor/composer/736d400e'

error:  cannot create /Users/dmitry/Projects/fivejars/ymcatwincities/openytest/openy-project/vendor/composer/736d400e/ymcatwincities-openy-11da3a9/tests/features/paragraphs/1��_2��_4��_paragraphs.feature
        Illegal byte sequence

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
```

Looks like this is just MacOs related issue.

**Comment by podarok** [comment]
Hi
Supporting macos as a hosting platform could be very tough. Should we open Pandora's box?

**Comment by podarok** [comment]
@ddrozdik this is not stopping OpenY from unpacking, right?
This file exists in tests only, so trivial bug we should ask Paragraph's creators to fix.
Correct me if I'm wrong

**Comment by ddrozdik** [comment]
@podarok this is not a blocker and even not a critical issue, this is just something to investigate what is wrong with it.

**Comment by anpolimus** [comment]
Hi, @ddrozdik.
I had same issue and it was connected with cache of composer.
I've cleared composer cache and rerun my containers - everything started working properly.

**Comment by kolesnikoff** [comment]
@ddrozdik @anpolimus this a very old bug.
I think the problem is in a filename of https://github.com/ymcatwincities/openy/tree/8.x-2.x/tests/features/paragraphs/1с_2с_4с_paragraphs.feature.
All "с"s in the file name are Cyrillic "с".
I guess we need to rename them to latin "c" and everything should be ok.

**Comment by dchubar-fj** [comment]
@podarok I think this one can be closed, behat tests have been removed in https://github.com/ymcatwincities/openy/commit/4cb72ad358e4ca0ba453ca55161a430af7cc844a
