### ISSUE TITLE
Feature Request: Bulk Update Upgrade Log Dashboard

### ISSUE THREAD

**Issue by mattshoaf** [ymcatwincities/openy#1566]
The site I'm developing has translations, so a lot of entities are flagged as changed in the openy upgrade log at `admin/openy/development/upgrade-log/dashboard`. It would be more efficient to be able to be able to bulk update config items, ideally each config would have a checkbox and you could bulk update them all to "Current Config" or "Open Y Version"

I was able to clear over 200 of them when upgrading to 1.14.1, see https://www.drupal.org/project/openy/issues/3033468, but when going to 2.0, the logs don't appear to be saved as an entity that I can clear using drush.

**Comment by paige-kiecker** [comment]
Thanks for flagging this, @mattshoaf. We are looking into it and will post updates here on any optimizations to the process.

**Comment by mattshoaf** [comment]
Thanks, I need to update that issue, using that delete process actually breaks updates later because config changes aren't appropriately flagged. If I come up with a different workaround or pull request, I'll post it here.

**Comment by paige-kiecker** [comment]
assigning this to 5J to resolve
