### ISSUE TITLE
New alerts (React component) -- placement, template

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#1567]
I have a problem with YMCA WNC site regarding alerts. New javascript place alerts under the header
https://github.com/ymcatwincities/openy/blob/42a96117bee4907cc121041e8fbade886515932b/modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/index.js#L60

In my case alerts should be placed above the header, so I had to hack the javascript.

Also, is there a way to change the html used by alerts without hacking contrib javascript?

**Comment by podarok** [comment]
@ygerasimov-imagex @ygerasimov is there any chance to use CSS for placement?

**Comment by ygerasimov** [comment]
@podarok not for placement. This would involve more clutter than just patching the javascript.

Can we adjust javascript not to place wrapper for react component but rather place it with twig file? Then it will be easy to override on a theme level.

**Comment by podarok** [comment]
@ygerasimov-imagex @ygerasimov I guess we could
We should extend it to look for available wrapper and skip adding own in case if wrapper exists on a page.
Feel free to extend it - should be 3-5 lines of code, I assume

**Comment by mikemuller** [comment]
@podarok @ygerasimov We'll need this functionality as well. Our placement and styling of the alerts is a little different. Any ETA on this update?

**Comment by podarok** [comment]
@paige-kiecker @ymcagtc ETA for development is 10h.
What should be done
- If there is an alert placeholder on a page - stick Alerts region to it, instead of adding by default after ```<header/>``` and before ```</body>``` tags via JS

Let me know when this needs to be added to OpenY distro

**Comment by paige-kiecker** [comment]
@podarok was this addressed with the release of 2.1.1?

**Comment by podarok** [comment]
@paige-kiecker yes, this was fixed
