### ISSUE TITLE
SQL error when node program_subcategory edit and try to save.

### ISSUE THREAD

**Issue by Fant0m771** [ymcatwincities/openy#1570]

**Comment by podarok** [comment]
![image](https://user-images.githubusercontent.com/563412/55885896-6ac3c800-5bb3-11e9-8be0-046c07fa3000.png)
Tested on a sandbox - no issues
Could you provide more details about error you are facing with @Fant0m771 ?

**Comment by Fant0m771** [comment]
When trying to save existing program_subcategory and you do not have Activity which using current program_subcategory you will see SQL error  Drupal\Core\Entity\EntityStorageException: Query condition 'node__field_class_activity.field_class_activity_target_id IN ()' cannot be empty. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 805 of /mnt/www/html/ymcatrianglevdmwy6nczq/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

**Comment by Fant0m771** [comment]
Fix is [here](https://github.com/ymcatwincities/openy/pull/1571)
cc: @podarok
