### ISSUE TITLE
Missed dropzone.min.js when updating from 2.0.4 to 2.0.7

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1574]
In some cases dropzone.min.js missed during upgrade
If you see issues like on screenshots below

![image](https://user-images.githubusercontent.com/563412/56050366-5f5bd280-5d54-11e9-845f-06a5d2b67d00.png)

![image](https://user-images.githubusercontent.com/563412/56050371-64b91d00-5d54-11e9-9760-33b60857474b.png)

Or during upgrade of your db
```
drush updatedb
Dropzonejs requires the dropzone.min.js library.                                                            [error]
       Download it (https://github.com/enyo/dropzone) and place it in the
       libraries folder (/libraries)
Requirements check reports errors.
```
Solution:
=====

from within your docroot folder
```sh
cd libraries/dropzone/dist/min/
wget https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js
```

And you should get your form working

**Comment by anpolimus** [comment]
@podarok we had the same issue during 2.x upgrade.

**Comment by anpolimus** [comment]
we added library locally but we need to make it working automatically with composer

**Comment by anpolimus** [comment]
From communication with @podarok : it would be better to implement it as library with links to CDN

**Comment by paige-kiecker** [comment]
@anpolimus sounds like you and @podarok have resolved this, closing this out.
