### ISSUE TITLE
Can't update to Open Y 2.0

### ISSUE THREAD

**Issue by AndreyMaximov** [ymcatwincities/openy#1577]
There is a way of upgrading Open Y 1.x to 2.0 that people really use:
- get the code updated by using `composer create-project ymcatwincities/openy-project:8.2.....`;
- roll out customizations over the updated code ;
- run the database updates.

Seems legit.

In fact, it doesn't work because composer pulls the latest versions of contrib modules.

Paragraphs 1.8 is what composer is downloading nowadays. Unfortunately, there is no easy way to provide an upgrade path with this version of the module installed. The database updates fail with:
`Field storage definition for 'revision_uid' could not be found. [error]`

Even though the documentation says to use `--prefer-lowest` when updating packages with composer:
- it is easy to forget run `composer update --and-all-those-long-additional-stuff`;
- it doesn't make much sense to run `composer update` right after `composer create-project`, because it must already be up to date;
- we don't really need the oldest versions of all the packages.

So the command must just pull the compatible modules.

**Comment by paige-kiecker** [comment]
Resolved in 2.0.9 release
