### ISSUE TITLE
The updated alerts module's CSS requires a font but doesn't provide it

### ISSUE THREAD

**Issue by AndreyMaximov** [ymcatwincities/openy#1579]
See https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/css/main.css#L1

```
@font-face{
  font-family:slick;
  font-weight:400;
  font-style:normal;
  src:url(/static/media/slick.ced611da.eot);
  src:url(/static/media/slick.ced611da.eot?#iefix) format("embedded- 
 opentype"), url(/static/media/slick.b7c9e1e4.woff) 
  format("woff"), url(/static/media/slick.d41f55a7.ttf) 
  format("truetype"), url(/static/media/slick.f97e3bbf.svg#slick) format("svg")
}
```

Can we also have a non-minified version of the file and the minified one renamed to `main.min.css`?

**Comment by podarok** [comment]
@AndreyMaximov file is dynamically generated, so request about having non minified - makes no sense
Use this command https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/package.json#L28
```sh
yarn build
```
to get css file recompiled.

**Comment by AndreyMaximov** [comment]
Having both minified and non-minified does make sense. The minified versions are hard to review but good to use in production. The non-minified versions are much more human-friendly and easier to review.

Rebuilding the files locally is the same as introducing customizations - nobody wants to maintain them if it's so easy to avoid.

**Comment by AndreyMaximov** [comment]
@podarok ^^

**Comment by podarok** [comment]
@AndreyMaximov feel free to improve yarn build flow to compile into non minified version of css

**Comment by podarok** [comment]
BTW, We need to backport alerts fix from YGTC ( it reduces resulting JS ~50% )

**Comment by AndreyMaximov** [comment]
@podarok cool. Glad to hear.

Hopefully, the original question about the font is going to be addressed.

**Comment by YMCA-GTC** [comment]
@podarok Do you have any updates on when the YGTC alerts will be backported, so we can close out this ticket? I see it marked as a bug and not an enhancement so I will update the severity.

**Comment by podarok** [comment]
Alerts already backported https://github.com/ymcatwincities/openy/pull/1592
