### ISSUE TITLE
Openy_rose node preview fatal error due to not looking for the correct parameter

### ISSUE THREAD

**Issue by bran** [ymcatwincities/openy#1582]
$vars['node_type'] does get set for node previews but there is no 'node' parameter. The preprocess needs to be updated to include 'node_preview' as a parameter.

See: https://github.com/ymcatwincities/openy/blob/fcb08262fe4e3c4233c03d6c7c366ddd28944497/themes/openy_themes/openy_rose/openy_rose.theme#L356

**Comment by paige-kiecker** [comment]
Assigned to IXM for resolution
