### ISSUE TITLE
Sandbox site tours refactoring 

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1584]
Some aspects of the Open Y Sandbox tours are currently not functioning as intended. Additional changes to the Tours have already been made within a Github branch labeled tour_fixes, but these final changes should be committed there before a PR can be submitted. 

Details about each fix needed can be found here: https://docs.google.com/document/d/16nDESJitpdbf33G8v-7PTeqCdDMAy6Vj__qFkm8Wi34/edit?usp=sharing

**Comment by SanyokMedved** [comment]
changes are here: https://github.com/ymcatwincities/openy/commit/97f442654dcad405977647c13ebf38cf8ec7f004
