### ISSUE TITLE
Timezone for teaser view of event node can be messed up

### ISSUE THREAD

**Issue by Tigatok** [ymcatwincities/openy#1590]
Was viewing a teaser mode for an event node, and the timezone was set to the UTC vs the drupal config timezone set.

Similar code to below can be used in the openy_node_event.module 
```

if ($element['#view_mode'] != 'full') {
    if ($element['#view_mode'] != 'teaser') {
       return;
    }
    // Event teasers are showing UTC time. Set to correct timezone before render
    $datesField = $node->get('field_event_dates')->getValue();
    $timezone = 'America/New_York';
    $startDt = DrupalDateTime::createFromFormat(DATETIME_DATETIME_STORAGE_FORMAT, $datesField[0]['value'], "UTC");
    $endDt = DrupalDateTime::createFromFormat(DATETIME_DATETIME_STORAGE_FORMAT, $datesField[0]['end_value'], "UTC");
    $startDt->setTimezone(new DateTimeZone($timezone));
    $endDt->setTimezone(new DateTimeZone($timezone));
    $datesField[0]['value'] = $startDt->format('Y-m-d\TH:i:s');
    $datesField[0]['value'] = $startDt->format('Y-m-d\TH:i:s');
    $node->get('field_event_dates')->setValue($datesField);
```

Not sure if this should be a bigger change or if the above can work.

**Comment by podarok** [comment]
@Tigatok thank you for the report
By default Drupal stores everything in UTC, it is responsibility of OpenY adopter to display it in a correct timezone,
Could you show what was changes in your case to understand if we need to improve it somehow?

**Comment by YMCA-GTC** [comment]
@podarok Do you consider this a bug, or a feature request?

@Tigatok Do you have any updates to @podarok 's request for more information that you could provide to us so we can dig deeper into this?

Thanks!

**Comment by podarok** [comment]
@YMCA-GTC I don't know. This could be a configuration issue of the @Tigatok site.

**Comment by Tigatok** [comment]
So Drupal stores everything as UTC, but there are areas in Drupal where you can specify the timezone you want it to use. In my above code snippet, even though I had set Drupal to use the America timezone, it was still doing its own thing.

**Comment by paige-kiecker** [comment]
Assigning to FJ for resolution

**Comment by AndreyMaximov** [comment]
@podarok @paige-kiecker 

That's already fixed in https://github.com/ymcatwincities/openy/commit/836bb1ef0b874a9efd4929302a7417c880a558eb

**Comment by paige-kiecker** [comment]
@podarok  ^can you confirm this can be closed?

**Comment by podarok** [comment]
Yes
