### ISSUE TITLE
Status message box cannot be closed after making page update

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1593]
The Status message box that appears after a successful update to a page cannot be closed. The page must be refreshed to remove it.
![image](https://user-images.githubusercontent.com/48487047/56982188-5a659400-6b46-11e9-8f87-2b241bba8a16.png)

Sometimes if the browser window is resized, the box reappears, and the page must be refreshed again to remove the message.

**Comment by OlgaBezhenar** [comment]
Hello @paige-kiecker,

Can you please clarify, is this carnation theme? 
Thank you.

**Comment by paige-kiecker** [comment]
Hi @OlgaBezhenar the screenshot was from Lily I believe? But I also duplicated the issue in carnation and Rose, so it affects all 3 themes. It is just less noticeable in Carnation and Rose because it is a thin bar along the top or the page rather than a box.

**Comment by paige-kiecker** [comment]
This has been resolved
