### ISSUE TITLE
Node preview is broken for Landing Pages on Lily

### ISSUE THREAD

**Issue by bran** [ymcatwincities/openy#1598]
Try to preview a landing_page node on a site using a Lily based theme.

**Comment by podarok** [comment]
@bran is it similar to https://github.com/ymcatwincities/openy/pull/1583 ?

**Comment by bran** [comment]
@podarok Yes that's right.

**Comment by paige-kiecker** [comment]
@podarok can you assign a severity to this issue? Is it something that can be included in the next point release?
