### ISSUE TITLE
Incorrect Address Display in Schedules Experience

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1609]
When a user clicks on a location for a class on the schedules page, the address displays out of order. Address should display in format: [Street, City, State, Country, ZIP].

![image](https://user-images.githubusercontent.com/48487047/58593787-7a65a180-8231-11e9-8641-f25f2f8c5f69.png).

**Comment by anpolimus** [comment]
@paige-kiecker PR that resolves this issue is merged. Could we close this issue now?

**Comment by paige-kiecker** [comment]
Yes, thank you
