### ISSUE TITLE
Add field_header_content to program content type

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy#1634]
Carnation makes reference to field.header_content in node--program--full.html.twig @ lines 80-88

`{% if content.field_program_color is empty %}
  {% set color = 'inherit' %}
  {% set bg_color = '' %}
{% else %}
  {% set color = '#' ~ content.field_program_color['#items'].entity.field_color.value %}
  {% set bg_color = 'background-color: '  ~  color %}
{% endif %}
`

Field is not present in @modules/openy_node_program/openy_node-program.install @lines 104-123:
 
`function openy_node_program_update_8004() {
  $config_dir = drupal_get_path('module', 'openy_node_program') . '/config/install/';
  // Update multiple configurations.
  $configs = [
    'field.field.node.program.field_content' =>[
      'description',
    ],
    'field.field.node.program.field_program_color' => [
      'description',
    ],
    'field.field.node.program.field_program_icon' => [
      'description',
    ],
    'field.field.node.program.field_program_image' => [
      'description',
    ],
    'field.field.node.program.field_sidebar_content' => [
      'description',
    ],
  ];`

Recommend updating content type to support `field_header_content` and adding support for fields in Lily/Rose.

**Comment by paige-kiecker** [comment]
@dwells-tn is this currently blocking your use of that content type, or is this just something you discovered and wanted the Core Team to be aware of?

**Comment by dwells-tn** [comment]
@paige-kiecker Not blocking content entry. Just making aware. I just added the field_header_content to our program content type. The biggest risk would be if programs had a list display on a site and were pulling from the same Image field as the default banner without an option for two different images.
