### ISSUE TITLE
Activity Finder check that field exist required to avoid fatal error

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1640]
Hi.
At one of our projects, only branch content type has field_branch_hours field.
at this place there is no check that this field is exist at CT
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php#L537
This issue produce fatal error in some cases.

**Comment by paige-kiecker** [comment]
Assigned to IXM for resolution

**Comment by SanyokMedved** [comment]
It has been resolved here: https://github.com/ymcatwincities/openy/commit/6f9ccdcf83b031ad7f0e9fd0b5700675e61f6ca0

**Comment by paige-kiecker** [comment]
@podarok can you review this?

**Comment by podarok** [comment]
This was fixed https://github.com/ymcatwincities/openy/issues/1640#issuecomment-519061835
