### ISSUE TITLE
Installing open Y

### ISSUE THREAD

**Issue by bluenodesystems** [ymcatwincities/openy#1642]
I get this error when trying to install open y using this command 
composer require ymcatwincities/openy

[Composer\Downloader\TransportException]
The "http://openy.cibox.tools:4680/packages.json" file could not be downloa
ded: failed to open stream: Connection timed out

**Comment by podarok** [comment]
@bluenodesystems we had this issue in our chat recently - it was a firewall blocking access. Could you please check if you have access to the url from the server you are trying to install OpenY?

**Comment by bluenodesystems** [comment]
Thanks for this info, the host fixed the issue by doing this
I'm glad to inform you I've fixed the issue by opening port 4680 for externals connections towards openy.cibox.tools.

**Comment by podarok** [comment]
Great
