### ISSUE TITLE
Make expanded default value configurable at Activity Finder

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1644]
Some of our clients want to have filters on the left rail of the Activity Finder to be expanded by default.
At now, default value is hard-coded to be collapsed by default.
We need to make it configurable from AF settings page OR at the paragraph configuration page.

![image](https://user-images.githubusercontent.com/3023950/60921874-2de79a00-a2a4-11e9-8f22-761287973488.png)

**Comment by paige-kiecker** [comment]
@YMCA-GTC something to consider for AF phase 3

**Comment by paige-kiecker** [comment]
Resolved by IXM
