### ISSUE TITLE
Schedules are not displaying in case of / at url parameter

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1660]
In case if category has / character, it breakes filtering at schedules page.
example of url to schedules:

> mind-body-classes?date=2019-07-17T22%3A04%3A33.657Z&locations=&categories=Mind%2FBody
![image](https://user-images.githubusercontent.com/3023950/61436637-e7e5a280-a943-11e9-920e-82c4c54032fe.png)

**Comment by anpolimus** [comment]
![image](https://user-images.githubusercontent.com/3023950/61436707-0b105200-a944-11e9-865d-9b1f9ae26688.png)

**Comment by paige-kiecker** [comment]
Assigned to IXM for resolution

**Comment by anpolimus** [comment]
@paige-kiecker that issue was connected to dedicated project and is not present at OpenY
Please, close it.
