### ISSUE TITLE
Add check that field exist

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1667]
In some cases during sync of groupex items system could fail because of absent check of field.
We have to add try catch here:
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_repeat/src/RepeatManager.php#L175

**Comment by paige-kiecker** [comment]
Assigned to IXM for resolution

**Comment by anpolimus** [comment]
@paige-kiecker it was fixed and released at this PR: 
https://github.com/ymcatwincities/openy/pull/1754

**Comment by paige-kiecker** [comment]
thanks @anpolimus closing out
