### ISSUE TITLE
Bug in cascade updates of class, activity, category nodes

### ISSUE THREAD

**Issue by AndreyMaximov** [ymcatwincities/openy#1673]
There are `hook_node_update()` implementations that make cascade updates of the content types mentioned in the subject.

https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.module#L13

https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_category/openy_node_category.module#L13

https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_class/openy_node_class.module#L13

Every time a published Program gets unpublished all the child Categories get unpublished as well, and in contrary when an unpublished Program gets published its child Categories get published.
Same works for Categories and Activities, Activities and Classes.

The thing is the code doesn't take into account the fact that there can be a workflow (for example, the editorial workflow), that allows users to create drafts. A draft is an unpublished revision of the node. The default revision doesn't change when a draft is created, so that website visitors can't notice any changes, but the website editors can.

Saying the code doesn't take into account the fact that there can be a workflow means, that every time you create or edit a draft, the code considers the whole node is unpublished (because drafts are unpublished revisions). That leads to cascade updates and unpublishing of the whole subtree - if you create a draft of a Program node then all the referencing category nodes get unpublished, then all activity nodes that reference the categories get unpublished, and, eventually, the classes get unpublished.

For the websites that use those nodes for building schedules, it means there is no schedule for that program anymore.

By default, Open Y is shipped without any workflows enabled, but the modules needed for that are enabled (`workflow`, `content_moderation`). So anybody can enable such workflows and configure them to fit their needs. That's why I consider that to be a bug.

**Comment by paige-kiecker** [comment]
This has been resolved
