### ISSUE TITLE
Need refactor preprocess logic

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1676]
At this openy_node_event we have to change hard-coded code with template solution that will give us opportunity to overwrite and easily change data format at different projects.
Existed solution requires some additional time for altering of existed preprocess solution that will not be supported at next releases of Drupal.
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.module#L45

**Comment by podarok** [comment]
@anpolimus there was some code merged https://github.com/ymcatwincities/openy/pull/1682
I'm not sure if this is related

**Comment by anpolimus** [comment]
@podarok , at #1682 code is related to alerts.
At this issue we want to fix events

**Comment by ivan-berezhnov** [comment]
@anpolimus @podarok  PR with fix created. Please check.

**Comment by ivan-berezhnov** [comment]
@anpolimus  @podarok  PR merged. Can we close this ticket?

**Comment by podarok** [comment]
Sure
