### ISSUE TITLE
[Carnation] Refactor matchAllHeight

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1692]
Hi.
1. At this place there is no need to have custom function since it is used only once and too small to be a separate function
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/src/js/openy_carnation.js#L218

2. It would be better to make list of classes for input data of MatchHeight configurable for theme settings.
Now, it seems to be hard-coded and you have to override all this file if you want to make changes to this list.
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/src/js/openy_carnation.js#L223

**Comment by paige-kiecker** [comment]
@anpolimus are you already working on this or waiting for direction from the OY Core team?

**Comment by anpolimus** [comment]
We are waiting for your directions. 
This issue is created during our work on client's tickets at one of the Y that using Carnation.

**Comment by paige-kiecker** [comment]
@anpolimus I added it to the Carnation Refactoring card on our roadmap so it's not forgotten.

**Comment by anpolimus** [comment]
Ok thx
