### ISSUE TITLE
[Carnation] Refactor openy_carnation.js and openy_carnation_landing.js 

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1693]
We need to split openy_carnation.js into list of small libraries that could be overwritten at sub_themes.
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/src/js/openy_carnation.js

Main benefit of this improvement is that new updates from OpenY will work automatically for libraries that are not altered.

Our use case -  for small fix at our project we have to override all code in openy_carnation.js and manually copy/paste updates during each OpenY update.

For openy_carnation_landing.js we need to remove commented code.

**Comment by paige-kiecker** [comment]
@anpolimus are you working on this already? would you consider this a bug or enhancement?

**Comment by anpolimus** [comment]
@paige-kiecker we are planning this to our list of Carnation refactoring

**Comment by sarah-halby** [comment]
@anpolimus & @ddrozdik was this item completed as a part of the Carnation refactoring? Was this added as a part of one of the point releases in 2020?

**Comment by ddrozdik** [comment]
@sarah-halby it has been completed more than a year ago as a part of this commit https://github.com/ymcatwincities/openy/commit/20871d745bc41ab941de6d1a60e720c3516f2dd2#diff-646b573991b154c0886650caa4178624fb923c1517406ec843e84a8a03f336de
The issue can be closed.

**Comment by sarah-halby** [comment]
Thanks for confirming @ddrozdik and helping us clean up this backlog. cc @podarok FYI - closing this item.
