### ISSUE TITLE
Folder Structure for Media Uploads

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1705]
As an Open Y site admin, I want the ability to store images in a nested folder structure similar to DropBox, Google Drive, MacOS, WinOS so that I can easily store and use my images in a manner that makes sense to my team without relying on file-name naming conventions due to the lack of such folders today.

Folders will be stored within the Drupal admin interface for each unique Y site.

**Comment by anpolimus** [comment]
@paige-kiecker let me offer you this contrib: https://www.drupal.org/project/media_directories
Using this contrib we can assign vocabulary to Media and add any folders structure we need.

**Comment by paige-kiecker** [comment]
@anpolimus can you demo that feature on our call tomorrow?

**Comment by paige-kiecker** [comment]
This was completed by Five Jars in version 2.4.0

**Comment by paige-kiecker** [comment]
This was completed by Five Jars in version 2.4.0
