### ISSUE TITLE
WYSIWYG Custom Font Sizes

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1707]
As an Open Y Site Admin, I want to be able to easily set my font size using the WYSIWYG built-in editor in Drupal 8 (ckeditor) so that I can quickly manipulate my pages however I wish and not be restricted to the default font sizes currently available.

**Comment by anpolimus** [comment]
@paige-kiecker this issue could be resolved by installation of this plugin: https://ckeditor.com/cke4/addon/font
or by netter understanding of heading sections that are already enabled in core right now.
https://ckeditor.com/docs/ckeditor4/latest/features/format.html this plugin is already in core.

**Comment by paige-kiecker** [comment]
Thanks @anpolimus! I think that first link is more what the community is looking for based on some previous conversations

**Comment by AndreyMaximov** [comment]
Resolved in https://github.com/ymcatwincities/openy/pull/1717

**Comment by podarok** [comment]
Thanks
