### ISSUE TITLE
Failed update: openy.terms_and_conditions.schema depends on the Open Y module that will not be installed after import

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1718]
Hi.
We are getting this error at different project during update to the latest OpenY 2.x version.

> openy.terms_and_conditions.schema depends on the Open Y module that will not be installed after import

Probably, this issue exist because openy module is not present at the system (probably system is thinking that OpenY profile is not a module).

We recommend to move this config and logic to existed openy_update module.

**Comment by anpolimus** [comment]
@kolesnikoff

**Comment by podarok** [comment]
@anpolimus 
```sh
drush ev "Drupal::service('module_installer')->install(['openy']);"
```
And then run updatedb

**Comment by anpolimus** [comment]
It is helped. Thank you.
