### ISSUE TITLE
Carnation uses two different FontAwesome styling versions.

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1720]
Initially, Carnation had 5th version of font awesome icons library.
After refactoring, additional js lib was added that were adding 4th version of FA.
At this blame report we could see how this changes were applied:
https://github.com/ymcatwincities/openy/blame/8.x-2.x/themes/openy_themes/openy_carnation/openy_carnation.libraries.yml

We need to leave only 5th version of FA.

**Comment by paige-kiecker** [comment]
Assigned to IXM for resolution

**Comment by paige-kiecker** [comment]
This has been resolved in https://github.com/ymcatwincities/openy/pull/1752
