### ISSUE TITLE
Incorrect height of modal window on Open Y based sites 

### ISSUE THREAD

**Issue by anprok** [ymcatwincities/openy#1728]
Use of styles
`#ui-id-2 {
    width: 90%;
    overflow-y: scroll;
    height: 200px;
}`

https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_socrates/modules/openy_autocomplete_path/css/autocomplete.css#L1

Using style with #ui-id-2 leads to the situation that in some cases modal windows with a randomly generated identifier have an incorrect height
Example of bug on Ymcamn.org (YMCA Twin CIty)
![image](https://user-images.githubusercontent.com/16559938/64612619-e92fca80-d3dc-11e9-9bc2-42f105368eee.png)

**Comment by paige-kiecker** [comment]
Assigned to IXM for resolution

**Comment by paige-kiecker** [comment]
this has been resolved in 2.2.3
