### ISSUE TITLE
DropzoneJS is not installed by composer

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1732]
During a lot of migrations I've noticed that dropzonejs is not installed automatically.
After little investigation, I've found that this package is migrated from github to gitlab and automatic npm-asset installation is not working.

I'll place code that fixes this soon.

**Comment by paige-kiecker** [comment]
Thanks, @anpolimus

**Comment by sarah-halby** [comment]
This was addressed in Q1-Q2 of 2020. Closing ticket.
