### ISSUE TITLE
Redundant Menu Titles that link to different pages [Daxko]

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1740]
When viewing the CMS menu, the Daxko integration displays 2 labels with the same name, but they link to different places. 

Resolution: determine if both links are needed, if yes, provide unique label for each

![image](https://user-images.githubusercontent.com/48487047/65633097-f0400680-dfa0-11e9-9d31-6bac58f416ef.png)

**Comment by paige-kiecker** [comment]
Assigned to IXM for resolution

**Comment by anpolimus** [comment]
@paige-kiecker PR is merged, please close the ticket.

**Comment by paige-kiecker** [comment]
@anpolimus 
![image](https://user-images.githubusercontent.com/48487047/66215258-d0879d00-e688-11e9-8c6f-36759ec241c1.png)
