### ISSUE TITLE
Failed to create temporary directory: 

### ISSUE THREAD

**Issue by okirordan** [ymcatwincities/openy#1741]
I am trying to install open y  but when I reach the Installation type stage,I get an An AJAX HTTP error occurred.
This is the full error (I running on xampp Windows 10)

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /national/docroot/core/install.php?rewrite=ok&profile=openy&terms_and_conditions=1&langcode=en&continue=1&id=2&op=do_nojs&op=do
StatusText: OK
ResponseText: Drupal\Core\Config\ConfigImporterException: Failed to create temporary directory: /tmp/confi_simpleb46f93e2-ff83-4854-82ae-29d93a50b14f in Drupal\openy_upgrade_tool\ConfigUpdater->importConfigSimple() (line 150 of C:\xampp\htdocs\national\docroot\profiles\contrib\openy\modules\custom\openy_upgrade_tool\src\ConfigUpdater.php).

**Comment by podarok** [comment]
@okirordan looks like you have issues with permissions to your temp directory by webserver
Ensure that your webserver has permissions to it

**Comment by podarok** [comment]
Feel free to reopen this issue in case if you still having issues
