### ISSUE TITLE
Activity Finder: restriction logic improvements 

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1742]
1. We need to add logic that will work in collaboration with Home Branch feature.

When user is selecting Home Branch, Activity Finder should take this parameter and restrict total results based on home branch data.

![image](https://user-images.githubusercontent.com/3023950/65706369-0201d680-e093-11e9-9f3f-ce6573c3bdae.png)

2. We need to implement feature flag for this feature (probably not all agencies want this logic. They need to have ability to disable it). 

**or we could change total's text to:**

![image](https://user-images.githubusercontent.com/3023950/65706619-7f2d4b80-e093-11e9-80bc-d9c65bc65839.png)

**Comment by podarok** [comment]
@anpolimus 
This looks really great ![image](https://user-images.githubusercontent.com/3023950/65706619-7f2d4b80-e093-11e9-80bc-d9c65bc65839.png)
We just need to have 2 links - one for all programs and another for home branch ( in the message itself )
I'd like to hear feedback from Ben McCoy - in case if any concerns. @paige-kiecker

**Comment by anpolimus** [comment]
@podarok as I told at slack - we need to organize dev sync meeting and discuss how two system could alter each other.

**Comment by hamrant** [comment]
@anpolimus @podarok we already have home branch plugin for AF - https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_home_branch/js/hb-plugins/hb-activity-finder-location.js

But it works only on the location selection step.

**Comment by podarok** [comment]
@paige-kiecker definitely need feedback from Ben

**Comment by hamrant** [comment]
As for an additional button - it's hard to inject this to AF application from the separated module. We can try to do this, but without results count.

**Comment by paige-kiecker** [comment]
@podarok I will get the group together to discuss this and https://github.com/ymcatwincities/openy/issues/1738

**Comment by anpolimus** [comment]
@hamrant since, general strategy is to move all to webpack apps, we need to discuss how other subsytems could alter data and look of our applications

**Comment by paige-kiecker** [comment]
Resolved by IXM
