### ISSUE TITLE
Google Translate widget end of life problem.

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1761]
Hi.
According to this message: https://translate.google.com/intl/en/about/website/
We have to think about alternative solution.

After some searching I've found that this service could be a good alternative for us.
https://gtranslate.io/

**Comment by podarok** [comment]
```
This change does not affect existing use of the Website Translator.
```
Looks like we should be fine stil, correct?

**Comment by anpolimus** [comment]
I hope so, but I've created this issue to double check it with you.

**Comment by anpolimus** [comment]
Since this is not an urgent problem for us - lets make it minor

**Comment by paige-kiecker** [comment]
Let's schedule a solution for this for the February release

**Comment by podarok** [comment]
We just need to have an option similar as we have for openy maps with Google and Leaflet plugins

**Comment by paige-kiecker** [comment]
This was determined to not be an issue. Closing and we will monitor any new information from Google
