### ISSUE TITLE
Landing page layout switcher does not hide sidebar area

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1762]
For some reason when we select one column layouts we still see the sidebar area. Previously it was hidden for one column layouts and become visible when I choose two columns layout. 
![image](https://user-images.githubusercontent.com/6285570/66753057-9180f500-ee9b-11e9-819b-6bda1a832867.png)

**Comment by ddrozdik** [comment]
cc @paige-kiecker

**Comment by anpolimus** [comment]
@paige-kiecker, @ddrozdik  we have fixed this issue across multiple client's project.
We can backport our fix here.

**Comment by ddrozdik** [comment]
@anpolimus good news. What are you waiting for then :)? let's backport it

**Comment by paige-kiecker** [comment]
@anpolimus can that be backported for November? 
cc: @podarok

**Comment by anpolimus** [comment]
@paige-kiecker on review now.

**Comment by ddrozdik** [comment]
Hi @anpolimus. I don't remember if this issue was fixed already, but the issue is still open. Please update the status of this issue. Thank you.

**Comment by anpolimus** [comment]
Hi.
It was fixed during November release.
