### ISSUE TITLE
Hide Drupal themes from the list of available themes on the Appearance page

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1763]
It would be nice to hide Drupal themes from the list of available themes on the Appearance page http://sandbox.openymca.org/admin/appearance. At this moment we have a few Open Y themes and some Drupal themes like Bartik, Seven, Stark. I f you try to enable them the site will be completely broken because they are not designed to work with Open Y components. 

![image](https://user-images.githubusercontent.com/6285570/66756289-62ba4d00-eea2-11e9-8590-5ef7eb605d4a.png)

Also make sense to hide Open Y Admin, because it is designed to work only with admin pages.

Marked this issue as a very low priority.

**Comment by anpolimus** [comment]
Subscribe

**Comment by paige-kiecker** [comment]
Agreed, this functionality should not be disabled, but should definitely be buried within the /appearance page so prospective Y's reviewing Open Y on Sandbox do not become confused.

**Comment by Elenamarchenkova** [comment]
Five Jars starts working on this :)

**Comment by paige-kiecker** [comment]
This was resolved in 8.2.4.4
