### ISSUE TITLE
Hide Main menu in the Microsites menu for Carnation does not work

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1764]
Microsites menu paragraph has a checkbox to hide the main menu. In Carnation it does not work. Probably because the theme is so specific and different from Lily and Rose, but anyway it should support such a feature. 

There is another [issue](https://github.com/ymcatwincities/openy/issues/1299) related to the microsites menu which should be taken into consideration as well.

**Comment by paige-kiecker** [comment]
Thanks, @ddrozdik, we will take this into consideration as we work on moving Carnation out of beta

**Comment by ddrozdik** [comment]
Steps to reproduce on the Sandbox:
1. Login as admin 
2. Go to http://sandbox.openymca.org/locations/downtown-ymca
3.  Edit the page and add the microsites menu paragraph as the second paragraph to the Header area. "Hide the Main menu" checkbox should be disabled/unchecked. 
![image](https://user-images.githubusercontent.com/6285570/68235794-eafcbf80-0014-11ea-8649-49abe1fbab77.png)

4. Go to Appearance and install Carnation as a default theme 
5. Return back
6. Verify you can see the main menu. 
![image](https://user-images.githubusercontent.com/6285570/68235726-cc96c400-0014-11ea-9238-0daa713ed99b.png)

7. Edit the page and enable checkbox "Hide the Main menu" and save the page 
![image](https://user-images.githubusercontent.com/6285570/68235837-fea82600-0014-11ea-98d1-93b636a72c9c.png)

8. Verify, you still will see the main menu while you **should not see it**.

**Comment by anpolimus** [comment]
This issue is fixed at carnation refactoring PR: https://github.com/ymcatwincities/openy/pull/1783
