### ISSUE TITLE
Activity FInder: keywords are not populated from wizard to results screen

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1769]
Given: I'm trying to search activities by entering search phrase on initial screen of Activity Finder
Expected result: search results page should use search phrase in search
Actual result: search phrase is not used in search.

![image](https://user-images.githubusercontent.com/3023950/67087469-ac10e200-f1ab-11e9-98e4-e80a730709ca.png)

![image](https://user-images.githubusercontent.com/3023950/67087503-bb902b00-f1ab-11e9-94a5-4371bcda44d6.png)

**Comment by anpolimus** [comment]
@paige-kiecker  we found this issue during testing of one of our project.
This is in our list for November release of Activity Finder 3.0

**Comment by anpolimus** [comment]
@podarok , @paige-kiecker this issue was fixed during AF 3.0 PR.
Please close this issue once you will test it at your projects.

**Comment by paige-kiecker** [comment]
Thanks @anpolimus

**Comment by paige-kiecker** [comment]
@podarok please check this
