### ISSUE TITLE
[Carnation] Address & Branch hours block is hardcoded 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#1781]
Block is hardcoded. There is no way to move it to another place, hide or replace it with another one.
![image](https://user-images.githubusercontent.com/6285570/68237632-8c394500-0018-11ea-980e-e5058e29127f.png)

Steps to reproduce:
1. Login as admin on the Sandbox
2. Change theme to Carnation
3. Go to http://sandbox.openymca.org/locations/downtown-ymca
4. Verify you can't hide, move or replace this block. It is hardcoded.

**Comment by anpolimus** [comment]
@ddrozdik, @podarok  this is hard-coded across all themes now.

### Links:
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_rose/templates/node/node--branch--full.html.twig#L142
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_lily/templates/node/node--branch--full.html.twig#L124
At previous release, we've fixed carnation styling of its block.

At last sprint, we've introduced a block and paragraph called Branch Contact Info and styled it for Carnation (it was backporting from one of our client's website).

This module is not enabled by default.
If you enable it, you could add Branch Contacts Info paragraph anywhere across Branch CT.

![image](https://user-images.githubusercontent.com/3023950/75244135-e894c000-57d3-11ea-92c1-165510194b43.png)

At the scope of this task, we could enable this module by default, delete the hard-coded part of the branch node and add this block to the header section.
Also, we could style it for all themes (not only for Carnation).
@paige-kiecker, are you ok with it?

**Comment by anpolimus** [comment]
Scope:
1. Style Branch Contact block not only for Carnation but for Rose and Lily.
2. Delete hard-coded branch address data for all themes.
3. Add new block to Demo content migration

**Comment by anpolimus** [comment]
Approved by @paige-kiecker
