### ISSUE TITLE
Fix cropper library configuration

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1786]
Let's introduce openy_focal_point.install with setting config /admin/config/media/crop-widget for image_widget_crop from CDN 
https://cdnjs.com/libraries/cropper
This should eliminate requirements error
![image](https://user-images.githubusercontent.com/563412/68686850-f0a65800-0574-11ea-8977-0a915856b76b.png)

**Comment by podarok** [comment]
![image](https://user-images.githubusercontent.com/563412/68689568-38c77980-0579-11ea-997e-8397b345fc09.png)

**Comment by ygerasimov** [comment]
We need to stick to 3.1.6 version instead of 4.0.0. Our js crashes on 4.x. I am testing installation and preparing a pull request.

**Comment by paige-kiecker** [comment]
This will be fixed in 2.3.1
