### ISSUE TITLE
Carnation Banner in 2.3 Open Y should display image

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1787]
![image](https://user-images.githubusercontent.com/563412/68687001-306d3f80-0575-11ea-9ed3-50f8a615008b.png)

Steps to reproduce
- Create Landing Page
- Add Banner in Content Area
- Save
- View page in Carnation theme

Same node working well in Lily
![image](https://user-images.githubusercontent.com/563412/68687102-627ea180-0575-11ea-97f7-2095562549df.png)

**Comment by podarok** [comment]
Small Banner is also not working
Standard OpenY

![image](https://user-images.githubusercontent.com/563412/68690603-f2731a00-057a-11ea-8f56-601586f3302a.png)

**Comment by anpolimus** [comment]
We are working on it.
