### ISSUE TITLE
Clean installation. Activity finder settings throws an Error

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#1793]
On a clean installation (search is not enabled) I open Activity Finder settings page and getting an error 
![image](https://user-images.githubusercontent.com/294265/68803192-20f10380-0614-11ea-9b2e-33503c242133.png)

**Comment by podarok** [comment]
Looks like dependency issue.
Missed search api?

**Comment by ygerasimov** [comment]
@podarok it should not require search_api as we could use Daxko as a backend

**Comment by anpolimus** [comment]
@paige-kiecker we've fixed it during testing of new release.
