### ISSUE TITLE
No programs demo content when installing Extended profile

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#1799]
I am installing "extended" profile with UI, I am not getting any Programs related demo content and Programs feature is not enabled at all.

Please confirm if it is desirable behavior

![image](https://user-images.githubusercontent.com/294265/68882262-b4354200-06c3-11ea-8ffd-1797a0d9b478.png)

**Comment by paige-kiecker** [comment]
@podarok can you look into this? If it doesn't affect the Sandbox Demo content, we can downgrade the severity

**Comment by podarok** [comment]
@paige-kiecker I guess I won't be able to check it next 1-2 weeks.
Maybe we can assign it to some core-partner to get fixed sooner

**Comment by paige-kiecker** [comment]
This was resolved with the new Sandbox experience launch
