### ISSUE TITLE
Programs search. FULL while it has 26 spots left

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#1800]
Default demo content with Solr backend for Activity Finder.

Family Swim shows in the listing as FULL but if I click on it -- there are 26 spots left.

![image](https://user-images.githubusercontent.com/294265/68891606-00897d80-06d6-11ea-9625-048faa006959.png)

![image](https://user-images.githubusercontent.com/294265/68891622-0bdca900-06d6-11ea-9d5b-033f40bdc760.png)

https://www.loom.com/share/97e9190a24e44b619612fdc7d4d8d7f1

**Comment by podarok** [comment]
We have no this in YGTC, so could be fixed in https://github.com/ymcatwincities/openy/pull/1802

**Comment by sarah-halby** [comment]
Once Activity Finder from Y of the North is backported into Open Y, this issue should be reviewed and revisited, but @podarok believes the backport will fix this issue. Potential for February 2021 release.

**Comment by sarah-halby** [comment]
@ddrozdik was this item addressed already? With Brandywine Activity Finder v3 - was this item already fixed or is it still an issue on their site? If it was fixed, could it be backported to Open Y?

**Comment by ddrozdik** [comment]
@sarah-halby this issue was assigned to IXM, not sure we worked on it. But I will check was it fixed on Brandywine or other Open Y websites we have built.

**Comment by sarah-halby** [comment]
Thank you @ddrozdik - we want to confirm if it is fixed on a Y site we know is using this feature. I appreciate you checking on it. :-)

**Comment by ddrozdik** [comment]
@sarah-halby team said they had not seen this issue this year, so I assume it is fixed. I tried to check it on the Sandbox environment, as @ygerasimov mentioned; however, Activity Finder does not work there with demo content. 

I think we can close it, and if anybody reports a similar issue, we can review it on the latest versions of Open Y.

**Comment by sarah-halby** [comment]
Thanks @ddrozdik. We'll close the issue and we can review/reopen if it is raised again. 

cc @podarok
