### ISSUE TITLE
Style element issue with the fields Background and Text color

### ISSUE THREAD

**Issue by Elenamarchenkova** [ymcatwincities/openy#1804]
The Background color and Text color are not displayed in the Style area in the admin panel.

Steps to reproduce:

1. Go to the Admin Panel - Content
2. Add Content -> Blog Post content type
3. Expand Style Area

**Expected result**: there are Background color and Text color fields.

![text and background](https://user-images.githubusercontent.com/57805241/69053861-030c1000-0a13-11ea-950d-cfcb85d3e0a0.png)

**Actual result**: The Background color and Text color fields are not displayed in the Style Area.

**Comment by ddrozdik** [comment]
сс @paige-kiecker , @podarok

**Comment by anpolimus** [comment]
We added it to our backlog.

**Comment by anpolimus** [comment]
@ddrozdik , @Elenamarchenkova, @paige-kiecker  this is working as expected.
According to implemented logic, color field should be displayed once editor select color card
![image](https://user-images.githubusercontent.com/3023950/70321761-dfc5cb00-1830-11ea-8aa9-2301d3af3fb1.png)

**Comment by ddrozdik** [comment]
I confirm it works as expected. It can be closed. 
cc @paige-kiecker.
