### ISSUE TITLE
Membership: Title Field

### ISSUE THREAD

**Issue by Elenamarchenkova** [ymcatwincities/openy#1805]
The title is not output on the Membership content type page.
Instead of it the title Description is visible.

Steps to reproduce:

1. Go to the admin panel -> Content
2. Add content -> Membership
3. Fill in Title field and Description field
4. Save 

**Expected result:** 
The title field should output the filled information on the page.

**Actual result:** 
The word Description is displayed.

![description](https://user-images.githubusercontent.com/57805241/69054754-f7b9e400-0a14-11ea-8bcf-c4a4714039f6.png)

![membership description](https://user-images.githubusercontent.com/57805241/69054762-fbe60180-0a14-11ea-839a-e199b9d96cf5.png)

**Comment by podarok** [comment]
This is a very simple task - view mode for the CT should be changed and the label of the field should be hidden.

**Comment by Elenamarchenkova** [comment]
Five Jars starts working on the issue.
