### ISSUE TITLE
Membership: Membership info output

### ISSUE THREAD

**Issue by Elenamarchenkova** [ymcatwincities/openy#1807]
Membership info is not output on the page in the Membership content type.

Steps to reproduce:

1. Go to Admin panel -> Content
2. Add Content -> Membership content type
3. Add membership info
4. Save

**Expected result**: 
Membership info is output on the page.

**Actual result:**
No membership info on the page

![membership info](https://user-images.githubusercontent.com/57805241/69067024-07dcbe00-0a2b-11ea-96f5-00bb8772effc.png)

![membership info1](https://user-images.githubusercontent.com/57805241/69067039-0f03cc00-0a2b-11ea-8dea-2ab78eff1eb3.png)

**Comment by Elenamarchenkova** [comment]
Five Jars starts working on this issue.

**Comment by ddrozdik** [comment]
I think we can close this issue since the page described above is visible only to the content editor and not supposed to be an independent page. 
cc @paige-kiecker, @podarok

**Comment by sarah-halby** [comment]
@podarok agrees with @ddrozdik on your comment above. Closing out ticket.
