### ISSUE TITLE
Groupex: bug with the same session at different room

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1813]
In case if we have 2 equal name of sessions at different rooms, at PDF render session would be shown at wrong place.

Example:

> Now we have an issue with the D.R. Semmes Family YMCA printed schedule. It appears that the yoga classes for Studio 2 are being placed under studio 1. 
> When I just select Studio 2 for D.R. Semmes Classes show correctly on the printed schedule. 
> However, If I select all the rooms it shows them all under studio 1.

**Comment by anpolimus** [comment]
@paige-kiecker we already fixed it for our client and backporting it to OpenY, since this bug is sensitive.

**Comment by paige-kiecker** [comment]
@anpolimus you are so kind! I will monitor the issue and close it once it's merged
