### ISSUE TITLE
Activity Finder: bug in case 2 equal categories.

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1814]
When filtering activities it seems to be only looking at the subcategory rather than the main category and subcategory.

**Comment by anpolimus** [comment]
@paige-kiecker , this is backport of bug fixed for one of our client.

**Comment by paige-kiecker** [comment]
Great, thanks @anpolimus

**Comment by paige-kiecker** [comment]
This has been merged. Closing the ticket
