### ISSUE TITLE
Correct Sandbox Site Issues

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1822]
Currently, images do not display within the tiles on the Sandbox homepage. Also, there is a typo in the Parents' Night Out card that affects both the Sandbox and new OY site installs that use the demo content. 

![image](https://user-images.githubusercontent.com/48487047/69662060-42f17980-1049-11ea-956e-d55aae2148e3.png)

**Comment by podarok** [comment]
FIxed in dev
Will be tagged in next point release
