### ISSUE TITLE
PEF: Activity details popup is broken after filtering by location

### ISSUE THREAD

**Issue by afi13** [ymcatwincities/openy#1824]
Steps to reproduce:

- Check activity details popup without any filters
- Verify the popup contains the only description.
- Apply filter by a location.
- The popup contains the list of sessions inside with an infinite loader. And the layout is broken.

![Peek 2019-11-28 12-42](https://user-images.githubusercontent.com/2179416/69795196-c394af00-11dc-11ea-8912-740a021914fe.gif)

**Comment by afi13** [comment]
Looks like a regression after merge of https://github.com/ymcatwincities/openy/pull/1779

**Comment by podarok** [comment]
@denysfilatov  could you check if reproducible in YGTC site, please?
/cc @shuklina @dmytrolavrinenko
If no(fixed) - let's backport fix and notify this thread in OpenY GitHub that we are working on backporting it.
Thank you

**Comment by manachynskyi** [comment]
#1827 should fix this.

**Comment by afi13** [comment]
Fixed
