### ISSUE TITLE
Change custom code related to usr_alias table to get support for Drupal 8.8+ core

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#1838]
An initial branch is here https://github.com/ymcatwincities/openy/pull/1834

We have a code that does SQL query against the table which doesn't exist in 8.8 Drupal core https://www.drupal.org/project/drupal/releases/8.8.0 .

We must replace it with a new, based on the entity system. See change record https://www.drupal.org/node/3013865. 

We should use `path_alias` entity now.
Once this is resolved - we'll continue to work on getting ready for 8.8 core

**Comment by anpolimus** [comment]
@podarok , we've made first round of investigation and prepared next plan:

1. Update pathauto contrib module to the last version.
2. Fix OpenY use of url_alias table: 
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_location/modules/openy_loc_camp/src/CampService.php#L193
3. Fix problem at lndr, optimizely and metatags module
    For this purpose, I've created tasks at issue tracker of contrib modules:
    https://www.drupal.org/project/lndr/issues/3109186#comment-13438786
    https://www.drupal.org/project/optimizely/issues/3109200

**Comment by podarok** [comment]
I'm fine with removing optimizely and lndr from distribution as unsupported
@paige-kiecker @ymcagtc what do you think?
