### ISSUE TITLE
Header Image Broken on Program Content Type

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#1844]
Steps to recreate:

- Log In to the sandbox site
- Change default theme to Carnation
- Edit any Program page & add an image to the "Image" field under the "Header Area"
- Save & View the page

Visually, the image should be showing like a "Small Banner".  However, it's not printing out to the correct area in the HTML, and therefore, styling is not being inherited.  This seems to be an issue arising with the update after 8.x-2.1-dev.

![image](https://user-images.githubusercontent.com/32372465/70644634-09a03880-1c09-11ea-8ed2-121e1a70b4ec.png)

**Comment by anprok** [comment]
We have a similar problem in Carnation theme for class page
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/node/class/node--class--full.html.twig#L89

Landing page
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/node/node--landing-page--full.html.twig#L111
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/node/include/node--landing-page--one-column-full.html.twig#L72
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/node/include/node--landing-page--one-column.html.twig#L72

Small banner paragraph
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/paragraph/paragraph--small-banner.html.twig#L52
https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/paragraph/paragraph--banner.html.twig#L52

**Comment by paige-kiecker** [comment]
@anprok did the PR you submitted only fix this issue for the Program content type, or did it also resolve the issues you mentioned above for Class pages, Landing pages and all small banner paragraph types?

**Comment by anprok** [comment]
@paige-kiecker I submitted fix only for Program content type at Carnation theme. Actually, I was waiting for approval that to resolve issues on these pages as well
