### ISSUE TITLE
Block field cannot be used

### ISSUE THREAD

**Issue by afi13** [ymcatwincities/openy#1861]
Steps to reproduce:

- Go to any paragraph type (or create new one)
- Add a block field
- Set a custom block plugin as a default value for the field, ex. `Repeat Schedules Block`
- Submit the field settings form

AR: Fatal error:
```
Got error 'PHP message: Uncaught PHP Exception RuntimeException: "A plugin type must be set through static::setSelectablePluginType() first.
```

**Comment by podarok** [comment]
@afi13 what version of 
- plugin
- drupal
- entity_reference_revisions 
module do you have?

**Comment by afi13** [comment]
@podarok I can reproduce it on the sandbox, so it's about default versions. We are preparing the PR with the fix.
