### ISSUE TITLE
Demo Content Not Rendering Correctly

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1863]
Demo content for Grid Content block in Carnation and "What's happening at the Y?" block in Lily are not displaying with proper padding.

![image](https://user-images.githubusercontent.com/48487047/71294446-268de780-233e-11ea-9423-b98a1f8282ec.png)

![image](https://user-images.githubusercontent.com/48487047/71294416-12e28100-233e-11ea-93ca-dc3b65770da9.png)

**Comment by Elenamarchenkova** [comment]
Five Jars starts working on the issue.

**Comment by podarok** [comment]
Merging, fixed in https://github.com/ymcatwincities/openy/pull/1963
