### ISSUE TITLE
Color field does not work for banner in Carnation

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy#1870]
For Carnation, the color for the banner on Carnation is always green, unlike in Rose, which allows you to change the color behind your text.

Two ways to reproduce:
**A. Banner with background color only on desktop and mobile.**
1. Create a landing page.
2. Add a banner to any region and select blue.
3. Hit save.

**B. Banner with image on mobile** 
1. Repeat 1-2 from A.
2. Add an image.
3. Hit save.
<img width="1451" alt="Screen Shot 2020-01-03 at 10 17 15 PM" src="https://user-images.githubusercontent.com/52217125/71759739-28e05d80-2e77-11ea-8f0e-4fc45843f361.png">
![Screen Shot 2020-01-03 at 10 19 33 PM](https://user-images.githubusercontent.com/52217125/71759740-28e05d80-2e77-11ea-94ef-25308b0cbda3.png)

Issue seems to be related to a `.banner-green` applied to the cta area in Carnation.

**Comment by dwells-tn** [comment]
You can find the `.banner--green` on `line 58` of 
[themes/openy_themes/openy_carnation/templates/paragraph/paragraph--banner.html.twig](https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/paragraph/paragraph--banner.html.twig)

**Comment by anpolimus** [comment]
@dwells-tn we will look to it.
