### ISSUE TITLE
Closing quotation mark does not appear for Story Card

### ISSUE THREAD

**Issue by paige-kiecker** [ymcatwincities/openy#1872]
When using the story card paragraph type in a webpage's sidebar, the closing quotation mark for the story is missing

![image](https://user-images.githubusercontent.com/48487047/71928469-3d657400-315d-11ea-9315-ffeed45f8ddc.png)

**Comment by paige-kiecker** [comment]
![image](https://user-images.githubusercontent.com/48487047/71929002-4a369780-315e-11ea-91a5-2cc7751f3bfa.png)

This issue applies to Rose and Lily. The Story card is not supported in Carnation at this time.

**Comment by Elenamarchenkova** [comment]
Five Jars starts working on this issue.
