### ISSUE TITLE
Table Cell Padding Doesn't Work for Content Editors Using WYSIWYG in Rose/Lily

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy#1874]
**Issue**
- When you try to use the out-of-the-box table widget in WYSIWYG, the cell padding field does not do anything in Lily or Rose.

**Steps to Reproduce**

1.  Go to sandbox.openymca.org
2. Create a landing page with simple content
3. Add a table with 100 pixels of padding. Hit save.

The table is not effected by these changes.

**Potential Issue**
`line 222` in themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap.css gives `td, th` a zero padding. This appears to be overriding the WYSIWYG settings when you inspect the element.
<img width="1436" alt="Screen Shot 2020-01-10 at 1 44 18 PM" src="https://user-images.githubusercontent.com/52217125/72187092-62a3ed80-33bc-11ea-966d-0ce1ec499698.png">
<img width="1436" alt="Screen Shot 2020-01-10 at 1 43 12 PM" src="https://user-images.githubusercontent.com/52217125/72187093-62a3ed80-33bc-11ea-9bb9-184875f6ef90.png">
<img width="1436" alt="Screen Shot 2020-01-10 at 1 42 52 PM" src="https://user-images.githubusercontent.com/52217125/72187095-62a3ed80-33bc-11ea-8f3b-6a782bf98895.png">
<img width="1436" alt="Screen Shot 2020-01-10 at 1 42 33 PM" src="https://user-images.githubusercontent.com/52217125/72187096-62a3ed80-33bc-11ea-9dd2-047c6197d72b.png">

**Comment by dwells-tn** [comment]
The path to the issue in Lily: themes/openy_themes/openy_lily/css/vendor/bootstrap/bootstrap.css

**Comment by paige-kiecker** [comment]
Thanks @dwells-tn, this is a complex issue we are working on a bigger solution to fix. We are exploring our broader strategy for our new design approach for Open Y, which Bootstrap would be a part of. 
cc: @podarok

**Comment by podarok** [comment]
Fixed today in dev.
Thank you
