### ISSUE TITLE
No Breadcrumbs on Program Pages

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#1880]
[Carnation Theme]
[openy-8.x-2.3.5]

----------

The Breadcrumb section seems to be missing on all pages of Program Content Type. 

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/32372465/73105148-d87c7e80-3ebd-11ea-887d-b133c5b306ec.png">

They appear on Program Subcategory types, as expected:

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/32372465/73105171-ecc07b80-3ebd-11ea-96e3-bd1ab26b0da1.png">

**Comment by anpolimus** [comment]
Hi, @jwtechdesign.
In last releases we've fixed feature, called "hide breadcrumbs" which was not working at Carnation before.
Can you verify that Hide breadcrumbs is unchecked at this page?

**Comment by jwtechdesign** [comment]
Hello @anpolimus - thank you for the update!

However, I do not see this checkbox or feature.  Is there meant to be a checkbox at the node edit level?  Is it on the Content Type settings?

**Comment by anpolimus** [comment]
@jwtechdesign nevermind. I've forgot that Programs CT doesent have this feature.
We will fix it.
