### ISSUE TITLE
Twig |render filter produce Twig fatal error.

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1899]
We are expecting a lot of Twig Fatal error after update to Drupal 8.8.
This is connected to new render logic at Drupal 8.8
I've noticed that this bug is connected to some fields and could appear unexpectedly.

We have to replace |render checks to twig_tweak rule field.isEmpty() to make everything worked.
Carnation has 91 item where this logic is used.

We have to add this message to release notes, since child themes also have to be updated.

Error text:
`Exception: Object of type Drupal\Core\Field\EntityReferenceFieldItemList cannot be printed. in Drupal\Core\Template\TwigExtension->renderVar() (line 591 of core/lib/Drupal/Core/Template/TwigExtension.php).`

**Comment by anpolimus** [comment]
Our team is working on fixes for Carnation right now.

**Comment by anpolimus** [comment]
cc @paige-kiecker , @podarok

**Comment by paige-kiecker** [comment]
Resolved in 8.2.4.4
