### ISSUE TITLE
Fatal error on location page from unexpected phone-number

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#190]
When I add a branch and specify some phone number there like "12345"
Save and publish 
And go to /locations 
You will see fatal error there:
InvalidArgumentException: The URI 'tel:12456' is invalid. You must use a valid URI scheme. in Drupal\Core\Url::fromUri() (line 280 of /var/www/demo/core/lib/Drupal/Core/Url.php).

**Comment by david-hernandez** [comment]
I get "Website encountered an unexpected error" when entering a phone number like 1234. But this is on the branch creation form, so there is definitely something up with the phone number validation for the form itself. That is the thing that should be preventing non-phone number like data from being entered.

**Comment by podarok** [comment]
Confirmed
```Uncaught PHP Exception InvalidArgumentException: "The URI 'tel:12345' is invalid. You must use a valid URI scheme." at /var/lib/jenkins/jobs/SANDBOX_FAST/workspace/build/docroot/core/lib/Drupal/Core/Url.php line 281, referer: http://sandbox.openymca.org/node/add/branch```

**Comment by YMCA-GTC** [comment]
In progress for next release per IXM

**Comment by YMCA-GTC** [comment]
Resolved with 1.12
