### ISSUE TITLE
[Policy] Externalize Vue and related libraries

### ISSUE THREAD

**Issue by duozersk** [ymcatwincities/openy#1902]
We need to put some order into how we use the Vue and related libs (vue-router, vuex, etc.) across the distribution. We already have several Vue-powered applications that include these libs in a variety of ways:
- Activity Finder has 2 separate Vue implementations - one for wizard steps, another one for results listing (https://github.com/ymcatwincities/openy/tree/8.x-2.x/modules/custom/openy_activity_finder)
-- Wizard is written using components approach and bundles Vue and Vue-router directly into the build artifact - https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_activity_finder/openy_af_vue_app/dist/main.js
-- Results listing is using the openy_system/vue and openy_system/vue_router libs which is getting assets from local libraries directory - https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_system/openy_system.libraries.yml

Suggestions:
- Change openy_system/vue and openy_system/vue_router libraries definition to get assets from CDN just like we already do with moment and jquery.matchHeight
- Add vuex library definition into openy_system module
- Remove vue and vue-router libraries from composer.json - https://github.com/ymcatwincities/openy/blob/8.x-2.x/composer.json#L119 and https://github.com/ymcatwincities/openy-project/blob/8.2.x/composer.json#L177
- Externalize Vue and related libs from build artifacts using Webpack 'externals' option - https://webpack.js.org/configuration/externals/ - to exclude them from the build asset
- Fix openy_activity_finder/openy_activity_finder library definition to depend on the openy_system/vue and openy_system/vue_router libraries
- Fix other Vue and vue-router usages in the codebase using the above approach

This will allow us to improve in several areas:
- Unify Vue libs usage in the project
- Libraries version bump will need to happen in one place - just the .libraries.yml definition in the openy_system module (and not in both composer.json + composer.lock in both openy and openy-project)
- Improve performance as libs will come from CDN

Please comment with any improvements to the above suggestions.

**Comment by ddrozdik** [comment]
I like this approach. +1

**Comment by podarok** [comment]
Thank you for the suggestions, guys.

> Change openy_system/vue and openy_system/vue_router libraries definition to get assets from CDN just like we already do with moment and jquery.matchHeight 

approved

> Add vue.js library definition into openy_system module

approved

> Remove vue and vue-router libraries from composer.json - https://github.com/ymcatwincities/openy/blob/8.x-2.x/composer.json#L119 and https://github.com/ymcatwincities/openy-project/blob/8.2.x/composer.json#L177

approved

> Externalize Vue and related libs from build artifacts using Webpack 'externals' option - https://webpack.js.org/configuration/externals/ - to exclude them from the build asset

approved

> Fix openy_activity_finder/openy_activity_finder library definition to depend on the openy_system/vue and openy_system/vue_router libraries

approved ( can be made within Multiparticipan Online Registration )

> Fix other Vue and vue-router usages in the codebase using the above approach

approved
