### ISSUE TITLE
console error after alert closing (incognito mode)

### ISSUE THREAD

**Issue by Elenamarchenkova** [ymcatwincities/openy#1918]
When you close an alert, you get the error in the console.

**Steps to reproduce:**

1. Open an incognito mode
2. Go to sandbox: http://sandbox.openymca.org/
3. Set up Lily theme as a default theme
4. Close any alert
5. Check console

**Expected result**: no errors

**Actual result**: there is the error. Please look at the screenshot below:

![incognito mode](https://user-images.githubusercontent.com/57805241/74737931-8d585000-525e-11ea-96a4-e14e894ddc48.png)

**Comment by anprok** [comment]
Let's close this issue
