### ISSUE TITLE
Blog node: Title is not aligned with sidebar

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#192]
if you have installed demo content goto [sitename]/blog/nourish-yourself-healthy-fats

Check the blog post with sidebar
Note that title is not aligned with sidebar

![image-2017-02-13-17-49-13-551](https://cloud.githubusercontent.com/assets/25036221/23457375/902cef0c-fe6f-11e6-95f2-8783a71e17a8.png)

**Comment by SanyokMedved** [comment]
Title's markup is fixed. Please check and close issue.

**Comment by alexschedrov** [comment]
This has been fixed in https://github.com/ymcatwincities/openy/pull/330.
