### ISSUE TITLE
GroupExScheduleFetcher cache not validated correctly

### ISSUE THREAD

**Issue by mattshoaf** [ymcatwincities/openy#1928]
When a user visits a page using the Groupex Pro `group_schedules` block, once they've made the initial selection, changing the form does not update the results.

After some debugging, I discovered that by commenting out
```
 if ($this->schedule) {
   return $this->schedule;
 }  
```
line 127 in `docroot/profiles/contrib/openy/modules/custom/openy_group_schedules/src/GroupexScheduleFetcher.php` the results will update correctly.

Suggestion: we need to check that the parameters are the same for the new query, and not just that the schedule exists.

**Comment by rahulusagility** [comment]
Adding patch file
