### ISSUE TITLE
add Camp content type to the Tour for content types	

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#193]
Go to [sitename]/node/add?tour=1
Click through the steps:
and see there is no tour step for camps

Proposed description:
"""
Here a user can add Camps. This content type is used for creation of the Camp primary pages similar to Branches. Camp teasers will also appear in Location finder page and you can associate blogs with your camp.
"""

**Comment by alexschedrov** [comment]
Fixed.
