### ISSUE TITLE
Activity finder number of weeks bug

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#1930]
The number of weeks on program search is calculating incorrectly. I have checked several examples and they are all one week short. This was originally reported by Silicon Valley and I checked on Houston and Tampa to confirm. I also made sure no exception dates were present in these examples. I guess the calculation that is working out the number of weeks needs to be fixed.

Example:

![image](https://user-images.githubusercontent.com/3023950/75245141-cf8d0e80-57d5-11ea-9dfa-7eeb40ca1181.png)

https://www.ymcasv.org/schedules/program-search?locations=811&categories=15106&exclude=&ages=144&days=6&keywords=&no_results=0&sort=title__ASC

**Comment by podarok** [comment]
Let's verify if weeks calculation is correct in YGTC @danylevskyi @dmytrolavrinenko . Seems like there is a bug, and we need to know if we have rthis fixed or not to backport to OpenY as a bug fix
Could be good task for @shuklina

**Comment by podarok** [comment]
Hi @anpolimus 
This was fixed a while ago in OpenY and successfully backported to YGTC, that's why we have no issue in AF.
See https://github.com/ymcatwincities/openy/pull/1855 fix.
We recommend updating to latest OpenY or pulling a fix from above PR
Let us know if the issue still there.

**Comment by anpolimus** [comment]
Change to 3weeks 2days

**Comment by paige-kiecker** [comment]
Resolved in 8.2.4.4
