### ISSUE TITLE
Zip and street address search works not properly on Rose and Lily themes

### ISSUE THREAD

**Issue by NadyaRudenko** [ymcatwincities/openy#1939]
If try to search location by zip currently indicated for branches
![image](https://user-images.githubusercontent.com/62060358/76415512-018b9c80-63a2-11ea-898d-37819b829c95.png)
on 5 miles distance it shows nothing, for 10 miles it shows only East YMCA
![image](https://user-images.githubusercontent.com/62060358/76415555-1405d600-63a2-11ea-9c7f-fbac05ae7d5e.png)
![image](https://user-images.githubusercontent.com/62060358/76415577-1ec06b00-63a2-11ea-9077-eb611331c8bc.png)
Address search also doesn't work
![image](https://user-images.githubusercontent.com/62060358/76416287-74e1de00-63a3-11ea-9fc3-345cc3db4b0b.png)
![image](https://user-images.githubusercontent.com/62060358/76416694-3a2c7580-63a4-11ea-96ea-deb90355eaf4.png)

**Comment by Elenamarchenkova** [comment]
Five Jars starts working on the issue.

**Comment by paige-kiecker** [comment]
This was resolved in 8.2.4.4
