### ISSUE TITLE
fix text in search placeholder for locations to ensure the text fits

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#194]
Let's make sure the text in the search placeholder fits.

![image-2017-02-24-17-09-58-411](https://cloud.githubusercontent.com/assets/25036221/23458116/b6e54326-fe72-11e6-9a09-245a85690d93.png)

**Comment by tolichka** [comment]
Found this issue and it will be fixed for this page: /locations

Size of text can not be changed, just made input box more wider on large screen devices.

Also found that similar structure in this file: modules\custom\location_finder\templates\location-finder-element.html.twig

If someone will provide link where this file is rendering than i can check that page and make changes on that page also if needed, but without live checking will not fix.

Will be fixed only for /locations page now.

**Comment by alexschedrov** [comment]
Fixed in #418.
