### ISSUE TITLE
Update drupal-composer/drupal-scaffold to drupal/core-composer-scaffold

### ISSUE THREAD

**Issue by mattshoaf** [ymcatwincities/openy#1943]
According to https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold and https://www.palantir.net/blog/guide-drupal-8-8-update the dependency `drupal-composer/drupal-scaffold` should be updated to `drupal/core-composer-scaffold`. The last update to https://github.com/drupal-composer/drupal-scaffold/tree/2.6.1 was over a year ago, so it is probably abandoned as well.

**Comment by mattshoaf** [comment]
I created the related issue in the openy-project, both will need to update at the same time: https://github.com/ymcatwincities/openy-project/issues/75

**Comment by podarok** [comment]
Thank you @mattshoaf 
We already working on this
