### ISSUE TITLE
make sure there is faded text in the search placeholder for blogs that reads search the blog.. 

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#195]
make sure there is faded text in the search placeholder for blogs that reads search the blog.. 

[sitename]/blogs

![without text](https://cloud.githubusercontent.com/assets/25036221/23458275/8417b342-fe73-11e6-8ac3-ca087081d409.png)
![with text](https://cloud.githubusercontent.com/assets/25036221/23458282/86f588e6-fe73-11e6-980c-302d5126b3e8.png)

**Comment by david-hernandez** [comment]
This was fixed some time ago.
