### ISSUE TITLE
Branch Contacts Info block is broken in Carnation

### ISSUE THREAD

**Issue by dchubar-fj** [ymcatwincities/openy#1962]
URL: https://sandbox-carnation-cus.openy.org/locations/downtown-ymca

**Comment by podarok** [comment]
conversation https://openy.slack.com/archives/C6G4ZTLVC/p1585048171191800?thread_ts=1585046657.190200&cid=C6G4ZTLVC

**Comment by dchubar-fj** [comment]
Fixed on sandbox, can be closed.
