### ISSUE TITLE
if there are no menu items in the footer and just social icons then the styling is broken

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#197]
if there are no menu items in the footer and just social icons then the styling is broken/

![image-2017-01-27-18-14-00-276](https://cloud.githubusercontent.com/assets/25036221/23459716/80703eb6-fe79-11e6-9f4a-64eb2660d4fe.png)

**Comment by david-hernandez** [comment]
This was fixed a couple weeks ago. Either just before, or during DrupalCon.
