### ISSUE TITLE
Theme errors in console

### ISSUE THREAD

**Issue by Elenamarchenkova** [ymcatwincities/openy#1979]
When you go to the sandbox home page https://sandbox-rose-std.openy.org/, you get the following in the dev console:

![open y](https://user-images.githubusercontent.com/57805241/78016640-c0a8f700-7353-11ea-9826-eb1b65736cbd.png)

Steps to reproduce:

1. Go to https://sandboxes.openy.org/
2. Choose Rose Standard
3. Log in as an admin
4. Get the home page https://sandbox-rose-std.openy.org/
5. Find the errors in the console.

**ER:** No errors
**AR:** The error shown on the screenshot above.

**Comment by sarah-halby** [comment]
Checking with Julia about the estimate for 5J to fix this item.

**Comment by sarah-halby** [comment]
Update from Julia - the estimate is 6 hours of testing  & development.

**Comment by podarok** [comment]
This is not a blocking issue @sarah-halby - only for Content Managers this is in console
We have inline editing via verf module, developed by IMX back in a while. Quick edit from the core, which is causing us issues - functional, but we should understand if this is needed for content managers.

**Comment by podarok** [comment]
@sarah-halby I see this bug is in a backlog for Y North - let's wait for it to be backported from there
/cc @dmytrolavrinenko

**Comment by podarok** [comment]
This is fixed in 9.x-2.x
