### ISSUE TITLE
Admin/Content Tour - 3rd step focus is wrong is should point to the content listing

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#198]
Admin/Content Tour - 3rd step focus is wrong is should point to the content listing

Go to /admin/content
Start the tour
navigate to the 3rd step
It should point to content table 
But now it is pointing to undefined area

![image-2017-02-07-20-02-21-868](https://cloud.githubusercontent.com/assets/25036221/23459776/d65193b6-fe79-11e6-99be-b76096ce5f06.png)

**Comment by david-hernandez** [comment]
Can you verify this is still a problem? It seems positioned correctly for me.

![screen shot 2017-05-12 at 3 14 03 pm](https://cloud.githubusercontent.com/assets/1504038/26013297/b6c23f98-3725-11e7-9beb-81b85427854a.png)
