### ISSUE TITLE
Fix config import for OpenY Focal Point module

### ISSUE THREAD

**Issue by anprok** [ymcatwincities/openy#1981]
During OpenY upgrade on Seattle I found a some Upgrade tool conflict appeared and the reason was incorrect config import in hook updates of some features. There are hook updates to enable using of OpenY Focal Point module where configuration was imported completely, and not the peculiar parameters with the changes imported. This situation led to overwriting the configurations changes made on the project earlier and the appearance of conflicts in OpenY upgrade tool. 
List of incorrect hook updates 
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.install#L167
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.install#L96
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/openy_prgf_small_banner.install#L176
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_prgf/modules/openy_prgf_teaser/openy_prgf_teaser.install#L126
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.install#L277

Also some configs that was imported not changed eventually.
For example here paragraphs.paragraphs_type.banner config import https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.install#L173 
but this config not changed since creation time in 2017 (changes was reverted) https://github.com/ymcatwincities/openy/blame/8.x-2.x/modules/openy_features/openy_prgf/modules/openy_prgf_banner/config/install/paragraphs.paragraphs_type.banner.yml

Let's fix hook updates to import only changed parameters in config but not full config.

**Comment by paige-kiecker** [comment]
Assigned to Five Jars, they will backport fix after Seattle upgrade

**Comment by AndreyMaximov** [comment]
@paige-kiecker @sarah-halby @podarok 

We analyzed this issue, and while it’s legit, we should not fix it. The reasons for such conclusion:

1. the code changes mentioned in the issue are related to the 8.2.3 release (Nov 12, 2019); there are not many web-sites that haven’t updated yet to 8.2.3 or newer Open Y.
2. it’s a bad practice to change the old database update hooks - we must avoid doing such changes;
3. the requested change is really minor as those configs are significantly changed and switching to param updating won’t significantly improve developers' experience.

The requested change should have been applied before the 8.2.3 release. Once the sub-optimal code in database update hooks is released, it must not be modified anymore (unless it fixes a critical issue).

@podarok Does it sound reasonable for you?

The issue raises a good question about code changes verification though. There is a [wiki-page about the review process](https://github.com/ymcatwincities/openy/wiki/Open-Y-Pull-Requests-review-standard) that already references the[ Upgrade Path doc](https://github.com/ymcatwincities/openy/blob/8.x-2.x/docs/Development/Upgrade%20path.md) that explains the difference between the available ways of dealing with the updated configs.

Maybe we should improve the documentation related to the review process and explicitly state that the configs being modified should go through the parameter update procedure and not the whole config import.

In my database of the websites launched in 2019 and earlier, more than 70% have updated to 8.2.3 already.

![image](https://user-images.githubusercontent.com/5453109/97971142-a47ea400-1dd3-11eb-9d95-2f2320e0f987.png)

**Comment by podarok** [comment]
I agree we shouldn't change old DB hooks. @AndreyMaximov thank you for the investigation.

I guess we can close this issue as outdated

**Comment by sarah-halby** [comment]
@podarok what are your thoughts about the documentation request?

**Comment by podarok** [comment]
I've added referenced documentation to our WIKI and mentioned the preferred way of maintaining the upgrade path.
https://github.com/ymcatwincities/openy/wiki/Code-Review-Quality-Best-Practices#how-to-support-upgrade-path
Thank you @AndreyMaximov for suggestions. 
Considering this as closed
