### ISSUE TITLE
Alert dismissal functionality

### ISSUE THREAD

**Issue by mattshoaf** [ymcatwincities/openy#1988]
With the new alerts, we've noticed that dismissing an alert on one page prevents alerts displaying on subsequent pages.

Observed cookie values:
`Expires / Max-Age:"Session"`
```
alerts_dismiss:
  0:25476
  1:25481
```
The user might not have seen the second alert before dismissing both, and won't see any alerts on subsequent pages, even if it's a different alert than on the ones that were dismissed.

Recommendations:
- Allow each alert to be dismissed individually
- Check available alerts against each of the previously dismissed alerts to determine which should be displayed
- Max age should be longer, proposing one week

**Comment by podarok** [comment]
This is fixed recently https://github.com/ymcatwincities/openy/pull/2264

**Comment by podarok** [comment]
@mattshoaf ^^^ FYI
