### ISSUE TITLE
anonymous users should not be able to navigate the node page for certain content types

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#199]
anonymous users should not be able to navigate to pages for certain content types. These content types are listed below
Branch with the coming soon check box selected
A Session CT full view
Alert CT full view 
Activity CT full view 
Membership CT full view

**Comment by Kerby70** [comment]
See https://github.com/ymcatwincities/openy/pull/351

**Comment by alexschedrov** [comment]
Merged.
