### ISSUE TITLE
Installing on pantheon

### ISSUE THREAD

**Issue by ugintl** [ymcatwincities/openy#2004]
Is it possible to install it on pantheon?

Currently I am using Acquia Dev Desktop windows 10 for development and using the open y composer template

The reason of using pantheon is that it allows to host 2 free dev sites. So it is easier for me to show the work to the client without paying for the hosting.

**Comment by podarok** [comment]
Hi @ugintl 
Thank you for your question.

OpenY is just a very very powerful version of Drupal. It is the biggest and most extended Drupal profile in the world.
But it still Drupal

When you do composer create project as described in our docs - you'd get a tree of codebase you'd need to deploy to Pantheon
Docroot folder is a folder where vhost of Webserver should be serving your site from
If Pantheon needs different name of the folder - rename it or better add a link on a filesystem to keep backward compatibility.


Let me know if you need any assistance.

If you need a call - feel free to book a time below
https://calendly.com/andrii-podanenko

**Comment by ugintl** [comment]
What about the vendor directory? It is outside the docroot folder. Dont we need that?

**Comment by ugintl** [comment]
Some D8 projects have a different pantheon template because of the structure.

**Comment by ugintl** [comment]
I think the solution is this https://pantheon.io/docs/nested-docroot

but the problem is that the "docroot" folder needs to be converted to "web". How can I do it?

**Comment by podarok** [comment]
@ugintl you can create a link from docroot to web once `composer create-project` finished

**Comment by ugintl** [comment]
How to create a link?

**Comment by anpolimus** [comment]
@ugintl you could create a symlink from docroot to web or change composer setting.
Here you can see how do they do it at the official pantheon composer.json example:
https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json#L98

**Comment by sarah-halby** [comment]
Once @podarok will add documentation to FAQ, then this item can be closed. Thanks for your help @podarok & @anpolimus

**Comment by podarok** [comment]
Thank you all
Added to our FAQ https://github.com/ymcatwincities/openy/wiki/Development-FAQ#how-to-install-open-y-on-pantheon-hosting
