### ISSUE TITLE
Moving Landing Page "Tab"(s) into a "Tabs" fieldgroup throws error.

### ISSUE THREAD

**Issue by aaronjchristian** [ymcatwincities/openy#2005]
When moving the various Tab fieldgroups inside of a Tabs fieldgroup throws an error.

`Notice: Undefined index: #group_name in openy_node_landing_field_group_form_process_alter() (line 12 of profiles/contrib/openy/modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.module).`

![Screen Shot 2020-04-30 at 8 00 17 PM](https://user-images.githubusercontent.com/16310921/80778545-a1051a00-8b1d-11ea-8a10-0c6c25bbc7a2.png)

![Screen Shot 2020-04-30 at 8 02 26 PM](https://user-images.githubusercontent.com/16310921/80778544-9fd3ed00-8b1d-11ea-9a0f-6f39ae5fa0ae.png)

**Comment by aaronjchristian** [comment]
https://www.drupal.org/project/openy/issues/3132760

**Comment by sarah-halby** [comment]
@podarok is going to double-check this item - to verify that this is still an issue and apply the patch from Aaron.

**Comment by podarok** [comment]
Fixed in https://github.com/ymcatwincities/openy/pull/2056
