### ISSUE TITLE
Undefined property: stdClass::$region in field_group_form_process

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2007]
While testing Open Y I noticed the following notice. The notice should be fixed.

`Notice: Undefined property: stdClass::$region in field_group_form_process() (line 366 of modules/contrib/field_group/field_group.module).
field_group_form_process(Array, Object, Array)
call_user_func_array('field_group_form_process', Array) (Line: 999)
Drupal\Core\Form\FormBuilder->doBuildForm('node_alert_edit_form', Array, Object) (Line: 563)
Drupal\Core\Form\FormBuilder->processForm('node_alert_edit_form', Array, Object) (Line: 320)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)`

**Comment by froboy** [comment]
I ran into this as well. It's possibly related to [this issue on drupal.org](https://www.drupal.org/project/field_group/issues/3059614), but I haven't been able to confirm yet.

**Comment by ddrozdik** [comment]
assigned this one to @ymcatwincities/five-jars team.
cc @sarah-halby

**Comment by podarok** [comment]
Will be added to post November first point release.
Fixed in #2275
