### ISSUE TITLE
Virtual Y doesn't work for OpenY Rose theme

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2044]
![image (5)](https://user-images.githubusercontent.com/563412/85721929-7a68f700-b6fa-11ea-816c-9483d3d02268.png)

**Comment by paige-kiecker** [comment]
@podarok @anpolimus can you confirm this is resolved?

**Comment by sarah-halby** [comment]
@paige-kiecker Andrii says this is resolved for Virtual Y, but it has not been resolved for Open Y yet.  We are keeping this open in the meantime.

**Comment by sarah-halby** [comment]
This was updated in the November 2020 major release. This item is closed. cc @paige-kiecker
