### ISSUE TITLE
Upgrade drupal/search_api_solr - in Drupal 8

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2075]
drupal/search_api_solr current version 1.3 - should become ^4.1
Accordingly to search_api_solr documentation 4.x version supports 4-8 versions of Solr.
search_api_solr 1.x is not supported and outdated.
Let's upgrade it in OpenY Drupal 8 in order to unblock Drupal 9 and provide support for decent versions of Solr

We also need upgrade path for existing users

TIP: In Drupal 9 there is a change that helped to get Open Y installed with latest search API - see https://github.com/ymcatwincities/openy/pull/2032/commits/ee52322f32ca528389e5e03df658ce50cb1511fc

**Comment by sarah-halby** [comment]
@podarok Julia checked this off in Basecamp. Can you please review, test, and determine whether or not we can close this item out?
