### ISSUE TITLE
Upgrade paragraphs module - in Drupal 8

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2077]
In order to become ready for Drupal 9 we should get this module upgraded
drupal/paragraphs 1.6 => 1.12
After upgrade we need to ensure our paragraphs remain working

Let's upgrade these in Drupal 8 first

PS. All demo content was successfully imported with 1.12 Paragraps in Drupal 9.

**Comment by sarah-halby** [comment]
@podarok can you review the commits added after you closed this issue?

**Comment by podarok** [comment]
@sarah-halby no need to review commits there. Those were fivejars team references to this issue during sync of the code between their branches in their forks.
