### ISSUE TITLE
Alerts "Visibility Pages" field does not work for <front> path

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2129]
When I add <front> to the Visibility Pages field I expect that alert will be displayed only on the homepage. But at the moment it does now work. 
![image](https://user-images.githubusercontent.com/6285570/91754207-b5434b80-ebd1-11ea-9e3b-a50b08caa411.png)

Also, I noticed that the description field does not render the needed token \<front>
![image](https://user-images.githubusercontent.com/6285570/91754300-dad05500-ebd1-11ea-8c05-4d2a8f378aa5.png)

while if I open the content type field configuration I see it there 

![image](https://user-images.githubusercontent.com/6285570/91754467-1e2ac380-ebd2-11ea-9047-780221d7d324.png)

**Comment by ddrozdik** [comment]
cc @paige-kiecker

**Comment by ddrozdik** [comment]
assigned this one to @ymcatwincities/five-jars team.
cc @sarah-halby

**Comment by podarok** [comment]
Will be added to post November first point release.
Fixed in #2277
