### ISSUE TITLE
Alerts placed in Header appear in Pre-Footer of Program & Program Subcategory nodes [Carnation]

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#2136]
Steps to Recreate:

1) Create an Alert
2) Select Placement as "Header" on all pages
3) View a Program Subcategory Node

The alert will appear in the footer of the page.  Here's the HTML structure:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/32372465/92007968-2a1aa080-ed0c-11ea-986f-193e926426be.png">

This is most likely an issue with the twig templates, but have not had time to review further.  Thought I would submit in case someone has a fix.

You can see this on the Carnation Sandbox when viewing a program subcategory node, as there are multiple alerts already live.  For example, [here](https://sandbox-carnation-cus.openy.org/programs/kids-and-family-activities).

**Comment by sarah-halby** [comment]
This also needs to be reviewed on Lily as well before closing this ticket.
