### ISSUE TITLE
Drupal 9 - Adding a Date Block breaks Landing Pages and throws "Website encountered an unexpected issue"

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy#2151]
**Issue description:** When a content editor tries to add a date block to a landing page on any D9 Open Y theme, Drupal throws the white "unexpected error" page.

### Steps to Recreate:

1. Go to any theme (both extended and custom; date block doesn't come on standard install.
2. Add new landing page and add date block.
3. Put any content inside the three paragraph fields (I tested with simple content).
4. Save the page and get the error.

I tested this on Carnation extended, Lily extended, and Rose custom.

**Comment by podarok** [comment]
```
InvalidArgumentException: The date cannot be created from a format. in Drupal\Component\Datetime\DateTimePlus::createFromFormat() (line 253 of /home/jenkins/workspace/D9_SANDBOX_CARNATION_CUSTOM/build/docroot/core/lib/Drupal/Component/Datetime/DateTimePlus.php).
```

**Comment by podarok** [comment]
fixed
Thanks for reporting
