### ISSUE TITLE
Inline Editing Disabled on Open Y Sandboxes

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy#2152]
**Issue Description:** The Inline editors developed in Open Y 2.4 is not currently enabled on the sandboxes, both in Drupal 9 alphas and public Drupal 8 sandboxes.

**How to reproduce**

- Go to sandboxes.openy.org and login
- Click on a landing page. None of the inline tools show up.

**Comment by podarok** [comment]
It's not disabled. Now you need to click on "Geysir" in a top right corner in order to enable contextual links for inline editing https://www.youtube.com/watch?v=w_k6az6pwnI
This came with contrib module updated
