### ISSUE TITLE
Focal Point Crop and Manual Crop Not Enabled on Sandboxes

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy#2153]
**Issue Description:** Cropping tools for Open Y are not available on the sandboxes.

**How to reproduce**

- Visit the media browser tab and click "Quickedit media(s)" on any photo.
- Click "Edit in new tab."
- None of the editing tools demoed in OY 2.3 are enabled in sandbox.

**Comment by podarok** [comment]
Module upgraded from 8.x-1.0-beta6 to 8.x-1.5 https://git.drupalcode.org/project/focal_point/-/compare/8.x-1.0-beta6...8.x-1.5#c11fe6755541e0364fc8bb6cf24e0ea1fff2d700
So we should upgrade our code respectively

**Comment by sarah-halby** [comment]
@podarok user story has been opened for FiveJars in Basecamp and Julia has been notified. Once I get a time estimate for completion and due date, I will add a comment to this issue.

**Comment by podarok** [comment]
Fixed and verified on D9 sandbox
![image](https://user-images.githubusercontent.com/563412/95181183-a3098e00-07cb-11eb-99d0-24b5af9216df.png)
