### ISSUE TITLE
Buttons colors after color change

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#216]
We have set up http://openy.ixm.ca/ and changed the button color to red. It changed the color of "Start guided tour" to red but it didn't for the "Load more" in the bottom of the page.

Please change the styling so theme button color got applied sitewide.

https://monosnap.com/file/birNySNVQEzHM41zz7o8ActZsNHBD8

**Comment by david-hernandez** [comment]
Can you recheck this? Lots of theme setting enhancements were made more recently.

**Comment by YMCA-GTC** [comment]
@ygerasimov Please review and close if applicable.

**Comment by podarok** [comment]
Fixed on latest OpenY version
![image](https://user-images.githubusercontent.com/563412/34530465-ee8ec404-f0b7-11e7-8a2d-f1df08049467.png)
