### ISSUE TITLE
Update contrib modules in Drupal 8 Open Y

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2180]
![image](https://user-images.githubusercontent.com/563412/92736701-2f6a9180-f383-11ea-848d-c18242a18e64.png)

**Comment by sarah-halby** [comment]
@podarok to double-check these contrib modules before closing this ticket.

**Comment by podarok** [comment]
We are good. The change was made in https://github.com/ymcatwincities/openy/pull/2285
