### ISSUE TITLE
Upgrade/Depreciate Media

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2183]
As an Open Y product manager, I would like to upgrade or depreciate media_* and tested in Drupal 8 so that that other Drupal 9 work for Open Y extended and custom can be tested.

Done when:
media_* is upgraded & tested in Drupal 8

@podarok please add more detail on Monday when you return. 

FiveJars team, this corresponding to the work in Basecamp as previously discussed.

**Comment by podarok** [comment]
We have media in core and a bunch of contrib modules named media_* - let's investigate if there is a way to reuse core and get rid of contribs
