### ISSUE TITLE
Vue Applications are not loading in Rose content region

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2191]
Example: Activity Finder in content section for Rose

https://sandbox-rose-cus.openy.org/activity-finder#/

![image](https://user-images.githubusercontent.com/563412/93472623-98ab5100-f8fd-11ea-8a9e-958817bf41d0.png)

**Comment by sarah-halby** [comment]
This is not working when configured in specific regions within Rose - a layout issue.
