### ISSUE TITLE
Remove reference to a non-existing CT "location" from configs

### ISSUE THREAD

**Issue by NightHunterSV** [ymcatwincities/openy#2193]
While upgrading to the latest version of Open Y I noticed a warning that reports there is a reference in the `repeat_schedules` paragraph to a not existing content type `location`. I believe it should be removed from configs. 

The following config contains this broken reference: 
field.field.paragraph.repeat_schedules.field_prgf_repeat_loc.yml

Below is the example of its presence:

https://github.com/ymcatwincities/openy/blob/5cecddbe4a7b285c4e52bd44b21ea2feacd20d61/modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/field.field.paragraph.repeat_schedules.field_prgf_repeat_loc.yml#L29

Also, the related code can be found here:
https://github.com/ymcatwincities/openy/blob/fcb08262fe4e3c4233c03d6c7c366ddd28944497/themes/openy_themes/openy_lily/sass/global/_openy-lily-styles.scss#L202

**Comment by ddrozdik** [comment]
@podarok, @sarah-halby ^^

**Comment by ddrozdik** [comment]
@podarok , @sarah-halby we can prepare a fix. However, I believe it can be an issue for the YMCA of the North since they still use the old content type called `location`. 

So, it would be nice to get approval before starting work on it. 

Thanks.

**Comment by sarah-halby** [comment]
@ddrozdik the Y North team will take a look at this and @podarok will take a look at this with @dmytrolavrinenko. Thank you for raising this issue.
