### ISSUE TITLE
Branches Popup All & Classes

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2196]
Issue in Rose, Lily & Carnation - the only option in Branches pop up is all - individual location is not available. @podarok please add more details and steps to test & review. 

Time estimate to fix: 8 - 16 hours

Lines 19 & 20 in testing/tracking document for Drupal 9, available on developers slack channel.

**Comment by podarok** [comment]
This is fixed in both 9.x and 8.x branches
