### ISSUE TITLE
'Add to calendar' on the Schedules page creates an incorrect event

### ISSUE THREAD

**Issue by akaleMulder** [ymcatwincities/openy#2197]
Steps to reproduce:
1. Go to https://www.ymcanorth.org/y-schedules
2. Move 3-4 days forward from the current date (I moved from Sep 19 to Sep 22)
3. Click the 'Add to Calendar' link next to any class and select 'Google Calendar' (or any other Calendar of your choice, I know the issue can also be reproduced in Outlook)

ER: Event will be added to the calendar with the title of the class I selected, and its date and time will be the same as on the Schedules page.
AR: Event is added to the calendar with an incorrect title, date, and sometimes time will be incorrect, too.

See video explaining the steps to be followed to reproduce the bug: https://www.loom.com/share/5d10b77d94004f3a9dd4b0aaa41e463f

**Comment by podarok** [comment]
Fixed on YN https://github.com/ymcatwincities/yn/pull/4827
To be backported by @svicervlad soon

**Comment by sarah-halby** [comment]
@podarok per our Slack conversation, we will hold on adding this to the distribution until the October or November release, depending on the timing. Due to its severity and label as a bug, it will not be pushed into the 9/23 release.
