### ISSUE TITLE
Google Search - Drupal 9

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2199]
Google Search needs to be tested in Lily, Rose, and Carnation against mod creation. @podarok please add additional details as needed. Corresponds to row 37 in Drupal 9 testing & tracking document.

**Comment by sarah-halby** [comment]
@podarok to work on this week and next week to prepare for February 2021 release.

**Comment by podarok** [comment]
This is done, tested - all working good. https://www.youtube.com/watch?v=ek1jk2DJU8M
