### ISSUE TITLE
Latest Blog Post - Lily Picture Taller than No Picture

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2201]
This Picture Block is taller than the No Picture Block in Lily. Andrii to investigate if that is intentional and if not, how to address.

**Comment by sarah-halby** [comment]
#2292 is linked to this issue per discussion last week. @podarok

**Comment by podarok** [comment]
This is fixed, thanks @shuklina and @dmytrolavrinenko
