### ISSUE TITLE
Latest News Posts (Branch) - Image/Text Overlap

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2202]
In Lily, the image overlaps the text below it in Drupal 9. @podarok to add additional testing and replication steps.

**Comment by sarah-halby** [comment]
Connected to #2201 
![image (5)](https://user-images.githubusercontent.com/68397223/99405126-03ebb200-28b2-11eb-975d-ee2a68fcff54.png)
![image (6)](https://user-images.githubusercontent.com/68397223/99405127-04844880-28b2-11eb-92ea-a9c20efe8292.png)
![IMG_C7D6BDA00474-1](https://user-images.githubusercontent.com/68397223/99405129-051cdf00-28b2-11eb-9e3a-3e25fe38a7ed.jpeg)

Title is hidden on cards for blog pots on Lily & same on mobiles, and when you click news tag you go to another page where you can see part of the titles

**Comment by podarok** [comment]
This is fixed
