### ISSUE TITLE
Cachet Font Testing on Drupal 9

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2208]
Cachet Font needs to be tested on Drupal 9 in Lily, testing needs to be done in Carnation. @podarok to add additional details.

**Comment by sarah-halby** [comment]
@podarok will test on sandbox with contrib from @froboy.

**Comment by sarah-halby** [comment]
@podarok to test this week for this item.

**Comment by podarok** [comment]
Tested and created a Tutorial https://youtu.be/Kl1lwYSg3ww
All works great.

**Comment by sarah-halby** [comment]
@podarok Great! We've sent this to @froboy for review and I've asked him if there is specific copy (text) he'd like us to use, as well as direct links for Ys to access cachet without paying for it independently. Until this update has been made, I'm going to reopen this issue and it can be closed once we have received that information and the documentation has been completed.

**Comment by sarah-halby** [comment]
@podarok here is the proposed copy from Avi - we can discuss it tomorrow morning: "To help Ys incorporate the Cachet font into their online applications, Y-USA is now licensing the web font version of Cachet for all YMCAs. Previously, Ys could only access the desktop version of the font from the Brand Resource Center (BRC)." The links are:  https://theybrand.org/wordpress/cachet (link to download) & https://link.ymca.net/ce/pulse/user/content/search?recent_search_id=59331&search_type=full_network&save_search_in=all (link for more information).

**Comment by froboy** [comment]
Here's what's on the [installer page](https://github.com/ymcatwincities/openy/blob/8.x-2.x/src/Form/UploadFontMessageForm.php#L32) currently:

> By default free Verdana fonts are used. While paid Cachet fonts are recommended by YMCA Branding Guide. 
To use Cachet fonts on the Open Y website go to the <a href=\'@config_url\'>Open Y Font Settings page</a> and upload the font files there.

I think it'd make sense to change this to:

> By default free Verdana fonts are used. Y-USA is now licensing the web font version of Cachet for all YMCAs via the [Brand Resource Guide](https://theybrand.org/wordpress/cachet). To use Cachet fonts on the Open Y website, download from the BRG then go to the <a href=\'@config_url\'>Open Y Font Settings page</a> and upload the font files there (using these instructions)

Subbing in the video or maybe a text version of the instructions that Andrii just made.

**Comment by sarah-halby** [comment]
@podarok just confirming that you saw the updates from @froboy above.
