### ISSUE TITLE
All News Category Pages in  Carnation Open Y sandbox are broken

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2219]
An issue raised by @froboy on October 2, 2020. All news category pages in the Carnation Open Y sandbox are broken. Experience can be recreated here: https://sandbox-carnation-std.openy.org/news/category/summer-day-camp

@podarok low priority given how buried it is in the sandbox.

**Comment by sarah-halby** [comment]
This is a duplication of issue #2296 - when 2296 is closed, this item can be closed as well. Added to backlog due to the low severity of the issue. To check with partners to determine if they have fixed for any of their sites and get an estimate for a backport.

**Comment by podarok** [comment]
Closed as #2296 is a duplicate and fixed already

**Comment by sarah-halby** [comment]
@froboy this has been fixed ^^
