### ISSUE TITLE
Automatically check all paragraph checkboxes

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2232]
It is related to the Cloning module that is usually installed by default with the Open Y (some of our clients encountered that bug already). If a user clones a source page, edits the cloned page, and saves the changes, the source page with all its content disappears. The issue arises only in case some of the Paragraphs are missed while cloning (so you can avoid the issue if you tick all the Paragraph checkboxes while cloning). Anyone using the Cloning module can encounter that bug.

@podarok FYI - FiveJars is working on this item for the November release. We will pursue a more robust fix for the following major release.

**Comment by NightHunterSV** [comment]
The fix is provided in https://github.com/ymcatwincities/openy/pull/2240

**Comment by podarok** [comment]
Thank you
