### ISSUE TITLE
The "field_prgf_repeat_loc" at "paragraph:repeat_schedules" references the "node:location" entity type that does not exist.

### ISSUE THREAD

**Issue by duozersk** [ymcatwincities/openy#2246]
```[warning] The "field_prgf_repeat_loc" at "paragraph:repeat_schedules" references the "node:location" entity type that does not exist. Please take action. ResourceTypeRepository.php:474```

Apparently this is due to the error in this config file - https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/field.field.paragraph.repeat_schedules.field_prgf_repeat_loc.yml#L29 - t references the bundle "location" which is gone from the Open Y distribution, but this config wasn't updated

**Comment by podarok** [comment]
It should be converted to openy_er field type

**Comment by podarok** [comment]
This is fixed in https://github.com/ymcatwincities/openy/pull/2323
