### ISSUE TITLE
FAQ field render is hidden in Bootstrap 3 themes

### ISSUE THREAD

**Issue by duozersk** [ymcatwincities/openy#2247]
https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/custom/openy_field_faq/templates/openy-faq-item.html.twig#L15

The class "hide" has "display: none !important;" rule in Bootstrap 3. It renders the whole FAQ paragraph render invisible in the browser.
![image](https://user-images.githubusercontent.com/2128648/96390228-4d19ea80-11bc-11eb-97c9-e00fd95fb05c.png)

**Comment by podarok** [comment]
FAQ item is supported only in Carnation. This is a known issue.
There was no demand on using FAQ in other themes

**Comment by duozersk** [comment]
It is definitely in use on YGBW, which is on Rose - https://ymcagbw.org/soccer

**Comment by podarok** [comment]
@sarah-halby seems like this is a good candidate for backporting from YGBW support for FAQ component

**Comment by sarah-halby** [comment]
@podarok what is the time estimate for the backport, testing, QA for Rose and/or Lily? @duozersk do you have any clients using it on Lily as well?

**Comment by duozersk** [comment]
@sarah-halby I don't think we have other clients on Lily except YMCA of the North.

**Comment by podarok** [comment]
@shuklina is working on getting FAQ fixed for Lily in Y North codebase. To be backported afterward
/cc @dmytrolavrinenko @sarah-halby
