### ISSUE TITLE
Reference to missing config file

### ISSUE THREAD

**Issue by vitalii-stepaniuk** [ymcatwincities/openy#2259]
Current version is 8.2.1.3.
I'm updating it to 8.2.6.4
The error I'm getting happens on 'drush updb' 

On updates I'm getting the following:

`file_get_contents(profiles/contrib/openy/modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/core.entity_view_display.block_content.featured_highlights_block.default.yml): failed to   [warning]
open stream: No such file or directory ConfigUpdater.php:183
TypeError: Argument 2 passed to Drupal\openy_upgrade_tool\OpenyUpgradeLogManager::saveLoggerEntity() must be of the type array, null given, called in /var/www/docroot/profiles/contrib/openy/modules/custom/openy_upgrade_tool/src/ConfigUpdater.php on line 188 in /var/www/docroot/profiles/contrib/openy/modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManager.php on line 268 #0 /var/www/docroot/profiles/contrib/openy/modules/custom/openy_upgrade_tool/src/ConfigUpdater.php(188): Drupal\openy_upgrade_tool\OpenyUpgradeLogManager->saveLoggerEntity('core.entity_vie...', NULL, Object(Drupal\Core\StringTranslation\TranslatableMarkup))
#1 /var/www/docroot/profiles/contrib/openy/modules/custom/openy_upgrade_tool/src/ConfigUpdater.php(107): Drupal\openy_upgrade_tool\ConfigUpdater->logConfigImportError('profiles/contri...', 'core.entity_vie...')
#2 /var/www/docroot/profiles/contrib/openy/modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.install(41): Drupal\openy_upgrade_tool\ConfigUpdater->importConfigs(Array)
#3 phar:///usr/local/bin/drush8/commands/core/drupal/update.inc(65): openy_prgf_featured_highlights_update_8002(Array)
#4 phar:///usr/local/bin/drush8/commands/core/drupal/batch.inc(151): drush_update_do_one('openy_prgf_feat...', 8002, Array, Object(DrushBatchContext))
#5 phar:///usr/local/bin/drush8/commands/core/drupal/batch.inc(97): _drush_batch_worker()
#6 phar:///usr/local/bin/drush8/includes/batch.inc(98): _drush_batch_command('829')
#7 phar:///usr/local/bin/drush8/commands/core/drupal/update.inc(239): drush_batch_command('829')
#8 phar:///usr/local/bin/drush8/commands/core/core.drush.inc(1237): _update_batch_command('829')
#9 phar:///usr/local/bin/drush8/includes/command.inc(422): drush_core_updatedb_batch_process('829')
#10 phar:///usr/local/bin/drush8/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#11 phar:///usr/local/bin/drush8/includes/command.inc(199): drush_command('829')
#12 phar:///usr/local/bin/drush8/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#13 phar:///usr/local/bin/drush8/includes/preflight.inc(67): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#14 phar:///usr/local/bin/drush8/includes/startup.inc(465): drush_main()
#15 phar:///usr/local/bin/drush8/includes/startup.inc(369): drush_run_main(false, '/', 'Phar detected. ...')
#16 phar:///usr/local/bin/drush8/drush(114): drush_startup(Array)
#17 /usr/local/bin/drush8(10): require('phar:///usr/loc...')
#18 {main}
TypeError: Argument 2 passed to Drupal\openy_upgrade_tool\OpenyUpgradeLogManager::saveLoggerEntity() must be of the type array, null given, called in /var/www/docroot/profiles/contrib/openy/modules/custom/openy_upgrade_tool/src/ConfigUpdater.php on line 188 in Drupal\openy_upgrade_tool\OpenyUpgradeLogManager->saveLoggerEntity() (line 268 of /var/www/docroot/profiles/contrib/openy/modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManager.php).
Drush command terminated abnormally due to an unrecoverable error. `

I found that on this update:
https://github.com/ymcatwincities/openy/blob/d4469a050d5c7dbe70a03789941f591b0b2dfc8b/modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.install#L41

there is a reference to a config, which is missing in the module's config directory.
I would fix it by myself if I would have a clue what config needs to be updated in this case.

Thanks!

**Comment by podarok** [comment]
@vitalii-stepaniuk could you provide more details about what are you trying to do?

Which version of OpenY are you using?
Which version you are trying to upgrade to?
Which command you are running prior to this error message?>

**Comment by vitalii-stepaniuk** [comment]
@podarok I've updated the description with the following:

Current version is 8.2.1.3.
I'm updating it to 8.2.6.4
The error I'm getting happens on 'drush updb'

**Comment by podarok** [comment]
https://github.com/ymcatwincities/openy/wiki/OpenY-upgrade-how-to-for-Developers
I'd recommend trying to upgrade to 8.2.2.1 before going to 8.2.6.4

**Comment by sarah-halby** [comment]
@vitalii-stepaniuk please review @podarok recommendation above. Can you confirm the upgrade path recommended or are you still facing issues?

**Comment by sarah-halby** [comment]
@vitalii-stepaniuk following up one more time on @podarok recommendation above. If we do not hear back from you, we will close this issue and reopen it if need be in the future.

**Comment by podarok** [comment]
We've updated the document with a key version of Open Y which developers should not skip during upgrades from old Open Y versions. See https://github.com/ymcatwincities/openy/wiki/Important-versions-for-upgrade-path
