### ISSUE TITLE
Upgrade 1-click install script to support php 7.4 

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2291]
Php 7.4 will be actively supported until November 2021, therefore we'd like all of Open Y to be compatible and supported using 7.4 by Q1 2021 Major Release to ensure that YMCAs have the time to test and upgrade before active support ends. PHP upgrade schedule available here: https://www.php.net/supported-versions.php 

PHP 7.3 active support ends early December 2020 and security support ends in early December 2021 which is why we want to migrate to 7.4 securely.

This corresponds with the Open Y Roadmap item: https://trello.com/c/5CriVAcA/180-ensure-all-of-open-y-is-compatible-with-php-74-score-6

**Comment by podarok** [comment]
The [script](https://github.com/ymcatwincities/openy-project/blob/8.2.x/scripts/openyonclickinstall.sh) is deployed and verified on
- Ubuntu 16.04LTS x64 - End of Life April 2021 - ( PHP7.3, MySQL 5.7, Apache 2)
- Ubuntu 18.04LTS x64 - End of Life April 2023 - ( PHP7.4, MySQL 5.7, Apache 2)
- Ubuntu 20.04LTS - End of Life April 2025 - ( PHP7.4, MySQL 8, Apache 2)

TODO: Record a video tutorial

**Comment by podarok** [comment]
@sarah-halby I've recorded a new tutorial for Ubuntu 20 https://www.youtube.com/watch?v=9fq5kaEmIkE
Review it, please and let's publish and share with the community

**Comment by podarok** [comment]
This is resolved now
