### ISSUE TITLE
Sandbox Default Font Size is Too Small

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2297]
Per the QA process from the last major release (Nov 2020), the default font size for the sandbox environment is too small, believed to be 10pt font. 
![Sandbox Font Size](https://user-images.githubusercontent.com/68397223/99406074-1a463d80-28b3-11eb-972d-95994f59ff81.png)

**Comment by podarok** [comment]
This is fixed now.
To be populated to all other sandbox indexes by @podarok 
Thank you @shuklina

**Comment by podarok** [comment]
Population is done
https://github.com/ymcatwincities/sandboxes_html/pull/10
https://github.com/ymcatwincities/sandboxes_html/pull/11
https://github.com/ymcatwincities/sandboxes_html/pull/12
https://github.com/ymcatwincities/sandboxes_html/pull/13
https://github.com/ymcatwincities/sandboxes_html/pull/14
https://github.com/ymcatwincities/sandboxes_html/pull/15
