### ISSUE TITLE
Duplicate ID openy_alerts_header_placeholder in the HTML markup

### ISSUE THREAD

**Issue by dchubar-fj** [ymcatwincities/openy#2298]
**Problem**
The elements with the same IDs are used for alerts placeholders:
* In header https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/node/include/header-default.html.twig#L59
* In footer https://github.com/ymcatwincities/openy/blob/8.x-2.x/themes/openy_themes/openy_carnation/templates/page/page.html.twig#L180

So we have invalid HTML markup on all pages(W3C validation is not passed) - 2 HTML elements with the same ID:
![Screenshot from 2020-11-17 18-07-30](https://user-images.githubusercontent.com/58946680/99407191-df1e2b80-28ff-11eb-9a21-e25e68a25a78.png)

**Proposed resolution**

- Update the Alerts React application in order to work with 2 placeholders (one for header and one for footer)
- Update templates and replace `openy_alerts_header_placeholder` with the `openy_alerts_footer_placeholder` for the element placed in footer

**Comment by podarok** [comment]
Related #2136

**Comment by podarok** [comment]
This is fixed in #2317
