### ISSUE TITLE
Visual Issues for Webform 5 in Rose, Lily, Carnation

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2299]
**Visual issues:**
1. on Carnation and Rose some fields are longer than the other
![Carnation   Rose Spacing Issue](https://user-images.githubusercontent.com/68397223/99589681-f87fb000-29b1-11eb-9601-d31a3c3e47e0.png)

2. On Carnation a big free space before the form (seen on the first screenshot). On Rose strange dividing line before the first field (seen on the second screenshot)
![Carnation   Rose Webform Field Length](https://user-images.githubusercontent.com/68397223/99589682-f9184680-29b1-11eb-8947-64681e8ffc8b.png)

3. Rose and Lily - fields that I marked as required doesn't have any marking that can show that they are required (star or whatever)
![Rose   Lily Required Fields](https://user-images.githubusercontent.com/68397223/99589683-f9184680-29b1-11eb-9dd8-95ef0fa94574.png)

**Comment by dmytrolavrinenko** [comment]
Hello @sarah-halby !

@shuklina has fixed the issue of the required mark in Rose and Lily
We've tested the issue on sandboxes with standard I Openy with Carnation, Lily, and Rose themes, and we couldn't reproduce the bug with different width of the fields in the webform on Carnation and Lily theme (1. on Carnation and Rose some fields are longer than the other)

Here are our test steps:
	1. Go to https://sandbox-rose-std-dev.openy.org/ and login as admin.
	2. Go to /admin/structure/webform and create a custom webform.
	3. Go to Build form and add this code in the Elements (YAML)

```
first:
   '#type': textfield
   '#title': First
   '#required': true
last:
   '#type': textfield
   '#title': Last
   '#required': true
add_your_email:
   '#type': email
   '#title': 'Add your email'
   '#required': true
number:
   '#type': number
   '#title': Number
tell_us_you_what_you_think:
   '#type': textarea
   '#title': 'What you think'
choose:
   '#type': checkbox
   '#title': Choose
checkboxes:
   '#type': checkboxes
   '#title': Checkboxes
   '#options':
     'Question 1': 'Question 1'
     'Question 2': 'Question 2'
     'Question 3': 'Question 3'
actions:
   '#type': webform_actions
   '#title': 'Submit button(s)'
   '#submit__label': 'Send message'
```

4. Save.
5. Create content Landing Page and add paragraph webform and Save the page.

Please let us know how to replicate the issue or provide the elements for your form. 

Thank you!

**Comment by sarah-halby** [comment]
Thank you @dmytrolavrinenko for the update and the steps to reproduce. We appreciate your help! @podarok can you please retest with the steps above tomorrow when you return?

**Comment by podarok** [comment]
@sarah-halby this is already tested.

**Comment by sarah-halby** [comment]
@podarok can this item be closed then?

**Comment by podarok** [comment]
@sarah-halby would be cool to get steps to reproduce from IMX QA . If can't be reproduced - we are good then and can be closed as fixed

**Comment by sarah-halby** [comment]
@podarok I've asked Nadiia for steps to reproduce. If we get them, I will add them here. If not, we can close this.

**Comment by sarah-halby** [comment]
@podarok Nadiia confirms that she still sees these issues in the Sandbox. Here are the steps to reproduce:

For the first one, I indicated a link, checked just now and it is the same, titles are hidden under images on news cards. You can see that they are there while the page is loading. https://sandbox-lily-std-dev.openy.org/news

2. Issue can be found on:
https://sandbox-carnation-std-dev.openy.org/news/category/general-wellness
https://sandbox-carnation-std-dev.openy.org/news/category/summer-day-camp
or any other news category page. 

3. Happens on any page on Carnation on IE11
https://sandbox-carnation-std-dev.openy.org
![image (8)](https://user-images.githubusercontent.com/68397223/101055618-af9e2e80-354f-11eb-9570-6c53ca804208.png)


4. Open https://sandboxes-dev.openy.org/ on any mobile and you will see a tiny font-size.

**Comment by sarah-halby** [comment]
All items complete on this with the exception of IE 11. We determined that we will not support the IE 11 changes due to the end of life for IE 11 and the edge cases for this browser.
