### ISSUE TITLE
Visual Issue: Coming Soon Banner Rose & Lily

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2301]
![Coming Soon Label Rose   Lily](https://user-images.githubusercontent.com/68397223/99591220-19490500-29b4-11eb-88e6-b9367e37dbb2.png)

On Carnation looks good.
Just want to make sure, that you were aware of how it looks on Rose and Lily (on desktop). 

The original issue for Carnation: 
#https://github.com/ymcatwincities/openy/pull/2127

**Comment by dmytrolavrinenko** [comment]
Just to confirm. 
Would it be okay to move the label to the upper right corner of the tile for Rose and Lily, in order to avoid overlapping with the location title?

**Comment by podarok** [comment]
Thank you @dmytrolavrinenko and @shuklina
