### ISSUE TITLE
 Map pins overlapping each other when it placed too close

### ISSUE THREAD

**Issue by aleevas** [ymcatwincities/openy#2315]
Sometimes when the map pins are placed too cose to each other we can see this picture:
![INOYI-33PinsOverlapping](https://user-images.githubusercontent.com/744406/100623110-5f925280-332a-11eb-9faf-40f81c6a3bd9.png)

As solution we can use clustering for map.
For Gmap it standard functionality
For Leaflet we can use this lib https://github.com/Leaflet/Leaflet.markercluster

**Comment by sarah-halby** [comment]
This is tested and works fine. This is an optional feature that can be enabled or disabled. Recommending to merge in February 2021 release, but waiting for approval.

**Comment by sarah-halby** [comment]
@podarok closing this issue for now given the mention above and the closed PR.
