### ISSUE TITLE
New Branches not filtered on Locations page (Location Finder Paragraph) when lat/lon are empty

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#2327]
**Description:**
Found this bug on a live Open Y site (https://www.ymcagreenville.org/locations).  

On the default locations page, when you use the "filter by amenities" in the sidebar, the Map filters correctly.  However, branches do not filter correctly in the content area - the "cards" coming from the Location Finder paragraph.  **This appears to only be happening to newly created branch pages.**  For example, when installing Open Y, there are 4 branches that come in the demo content (depending on the install profile).  Those branches filter correctly.  However, any new branch created after that do not.

**Page / Location of Bug to test:** 
https://sandbox-carnation-cus.openy.org/locations (also confirmed on Lily & Rose)

**Steps to Reproduce:**
- Log in to Sandbox above
- Create new Branch (Add Content > Branch) with basic information.
- Add single Amenity to that Branch page (Adaptive Programs, for example).
- Go to "/locations" and filter by any amenity in the sidebar
- You will notice the branch page you created above, will always show.

Any suggestions to resolve would be greatly appreciated!

**Comment by podarok** [comment]
@jwtechdesign you should provide lat/lon values in order to get filtering working properly
This is definitely a bug, because lat/lon should be required fields @sarah-halby 

Thank you
