### ISSUE TITLE
Alerts on location related pages are not working 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2330]
On the latest version of Open Y (2.7.0 & 2.7.1), there is a problem with the Location field, which part of the Alert content type. This field has no options while branch and camps exist on the website 
![image](https://user-images.githubusercontent.com/6285570/101827276-284d4e00-3b41-11eb-914a-14922fcd856f.png)

Without options, there is no way to create an alert that will be associated with all branch or camp pages via this reference. 

**Expected Results:**
Location dropdown contains a list of branch and camp locations.

**Comment by podarok** [comment]
Confirmed as a bug

**Comment by sarah-halby** [comment]
Approved to include on Dec 22, 2020 point release due to needs from YMCAs.

**Comment by sarah-halby** [comment]
This item is an exception to our code freeze for the Dec 2020 point release due to the importance of the alerts for YMCAs (both for 2020 and the holiday season). Approved by @sarah-halby & @podarok - Open Y Core team informed via call.

**Comment by ddrozdik** [comment]
@podarok thank you for a quick fix

**Comment by podarok** [comment]
> @podarok thank you for a quick fix

NP, thank you for finding this bug. It was a nasty one, especially now...
