### ISSUE TITLE
Membership Calculator (Choose Location Step) Broken

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#2341]
Tested on all 3 themes - seems to be the same for all.  Branches do not show as Radio element options in the second step of the Membership Calculator.  This causes an error where a user cannot complete the process to see Step 3 and register.

Steps to Recreate:

1)  Navigate to the default Join page where the Membership Calculator lives: https://sandbox-carnation-cus.openy.org/join
2)  Select a Membership & choose "Next".
3)  Bug is on this step --> No locations / branches listed below the map.

![image](https://user-images.githubusercontent.com/32372465/102527101-4562af00-4062-11eb-8632-639c8b8d6111.png)

Thanks!

**Comment by podarok** [comment]
@jwtechdesign it's not broken. Please visit Locations Filter and enable locations to be displayed

**Comment by podarok** [comment]
Addressed in https://github.com/ymcatwincities/openy/pull/2210
https://github.com/ymcatwincities/openy/pull/2212
First time seen https://github.com/ymcatwincities/openy/issues/2196

**Comment by froboy** [comment]
I've documented this requirement [on the message board](https://community.openymca.org/t/membership-calculator-paragraphs-open-y-user-docs/908#troubleshooting). It would be nice if this worked out of the box (on the Sandboxes as well) but hopefully this will help for now.
