### ISSUE TITLE
In the openy hours formatter we always use hardcorded default values

### ISSUE THREAD

**Issue by aleevas** [ymcatwincities/openy#2344]
Looks like we have some logical issue in [openy_hours_formatter.js](https://github.com/ymcatwincities/openy/blob/f06361f1f8b96aee9c1e60acc177e40cdcb70047/modules/custom/openy_hours_formatter/js/openy_hours_formatter.js#L53)

```
if (typeof drupalSettings.openy_hours_formatter != 'undefined') {

        drupalSettings.openy_hours_formatter = {};
}
```

And as result we always use default values that hardcorded in that file.
That's mean even if we use another timezone for the Open Y site, anyway for user we display works hours based on default "America/New York" timezone
![todaysHoursBlock](https://user-images.githubusercontent.com/744406/102899672-f78be380-4473-11eb-8bf3-6182151bd985.png)

**Comment by podarok** [comment]
How come this is America/New York @aleevas ?
Does the code use default timezone from Drupal?

**Comment by aleevas** [comment]
> How come this is America/New York @aleevas ?
> Does the code use default timezone from Drupal?

@podarok in the code below we use that defaults value if we don't have values that we should be sent through drupalSettings array.
But in the condition that I show you in issue description, if we sent this values -> we make this settings empty object
Please see:
```
 updateTodayHours: function () {
      if (typeof drupalSettings.openy_hours_formatter != 'undefined') {
        drupalSettings.openy_hours_formatter = {};
      }

      var $todayHours = $('.today-hours > .today');
      var hoursData = [];
      var branchHours = drupalSettings.openy_hours_formatter.branch_hours || [];
      var tz = drupalSettings.openy_hours_formatter.tz || 'America/New York';
```

So I've fixed this condition to correct one
