### ISSUE TITLE
Teaser image style is too small (Carnation)

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2347]
At mobile viewpoints on Carnation, `prgf_teaser` images can display at up to 510px wide but the image style is only outputting `260×220`. The style should be at least doubled to output 520x440, possibly 2x that (if we're accounting for high-density displays).

![Health_and_Fitness___YMCA_of_Greensboro_—__Private_Browsing_](https://user-images.githubusercontent.com/238201/103043687-5cfad580-4543-11eb-8e49-f96955be8077.png)

**Comment by sarah-halby** [comment]
Story point = 1

**Comment by sarah-halby** [comment]
@froboy this has been completed and will be added into the next Open Y point release.
