### ISSUE TITLE
Open Y Map - Change default base layer

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2350]
See https://sandbox-carnation-cus.openy.org/locations?type=ymca,camps&amenities ![Locations___Site-Install](https://user-images.githubusercontent.com/238201/103101563-d2b37f80-45dd-11eb-8909-866bd9e9c20f.png)

As per https://phabricator.wikimedia.org/T261694 and https://github.com/geopython/pygeoapi/issues/567, Wikimedia is now:

> limiting the maps API to only wikis and tools hosted on Wikimedia Foundation domains.

I'd recommend:
- (easy) changing the default base layer to OpenStreetMap.Mapnik in [module config](https://github.com/ymcatwincities/openy/blob/9.x-2.x/modules/custom/openy_map/config/install/openy_map.settings.yml#L3)
- (medium) removing wikimedia from the [form options](https://github.com/ymcatwincities/openy/blob/9.x-2.x/modules/custom/openy_map/src/Form/SettingsForm.php#L124) and providing an update hook.

**Comment by sarah-halby** [comment]
The easy option is a story point 1. The medium option would a story point 2 due to the need for the upgrade path. We will separate these into two user stories to be able to address the immediate need of option 1 and pursue option 2 in the future. cc @froboy
