### ISSUE TITLE
Carnation: Location finder listing improvements

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2360]
**Test Environment:**
Environment: | https://sandboxes-d9.openy.org/
Drupal version | 9.0.10
Open Y version | 8.x-2.7.1
Open Y installation type | Custom
Open Y theme | Carnation

**Description:**
1. Not obvious that a phone number is clickable until you try and click. I recommend changing styles for them. 
![image](https://user-images.githubusercontent.com/6285570/103665723-d0113c80-4f84-11eb-9078-0e6ac36da7c4.png)

2. For the demo content it would be nice to have real phone numbers formats instead of 9999999999.

**Comment by sarah-halby** [comment]
Adding this to the discussion with Ben around UX enhancements.

**Comment by sarah-halby** [comment]
@podarok, Ben has approved these changes via Slack. @shelleygoetz can you please open a ticket in Jira maintenance and let's get this one assigned.

**Comment by llamarama** [comment]
Hey all, if you need my input here, please be sure to use my @llamarama handle so that I'm notified. Also, please add me to the participants' list. Thank you!

**Comment by shelleygoetz** [comment]
@sarah-halby Jira ticket created - https://openy.atlassian.net/browse/MAINTAIN-193

**Comment by froboy** [comment]
https://www.drupal.org/project/openy_carnation/issues/3270347 in addition to the linked PR above.

**Comment by podarok** [comment]
https://www.drupal.org/project/openy_carnation/releases/2.0.5 done
Thank you @froboy
