### ISSUE TITLE
Hide GroupEx Pro menu item if this integration is not enabled.

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2368]
In the Open Y menu, there is a menu item called GroupEx Pro which is always visible even if you don't use this integration.
![image](https://user-images.githubusercontent.com/6285570/104232629-add65d80-5461-11eb-9216-d6a3e566cc40.png)

 If you try to open it you will get a message `You do not have any administrative items`. 
![image](https://user-images.githubusercontent.com/6285570/104232192-0bb67580-5461-11eb-8c47-cba560cfeec3.png)

It makes sense to hide it from the menu.

**Comment by sarah-halby** [comment]
This is not in the module that is responsible for the settings. Story Point: 2.

**Comment by podarok** [comment]
This is fixed. Will be in next point release
