### ISSUE TITLE
Draggable icon appears 3 times 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2370]
**Test Environment:**
Environment: | https://sandboxes-d9.openy.org/
Drupal version | 9.0.10
Open Y version | 8.x-2.7.1
Open Y installation type | Custom
Open Y theme | Carnation

**Description:**
The issue is very similar to this one https://github.com/ymcatwincities/openy/issues/2363 however for the Grid Content paragraph this icon appears 3 times, see screenshot
![image](https://user-images.githubusercontent.com/6285570/104364528-c6a94680-5527-11eb-93a9-8cc9213b6eec.png)

**Comment by froboy** [comment]
I tested this and I'm not seeing the issue any longer. https://sandbox-carnation-cus-d9.openy.org/node/36/edit @podarok this might be ok to close.

**Comment by podarok** [comment]
Thank you @froboy 
Fixed by core
