### ISSUE TITLE
Missed alert nid in draggableviews

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#2377]
## Steps to reproduce

- Login as admin
- Go to `/admin/content/alerts-rearrange`
- Change order
- Go to `/node/add/alert`
- Create an alert in the header and assign it to the branch
- Go to the branch page and check that alert not displayed

## Issue reason

In `AlertsRestResource` we have DB select from the `draggableviews_structure` table, by default on sandbox result of this DB query empty because items not reordered - https://github.com/ymcatwincities/openy/blob/9.x-2.x/modules/openy_features/openy_node/modules/openy_node_alert/src/Plugin/rest/resource/AlertsRestResource.php#L201

When items were reordered new alerts will be missed in the `draggableviews_structure` table, so the result of this DB query not empty, and the next query will have a condition limit by `NID`

```php
$loadByProperties = ['type' => 'alert', 'nid' => $nids, 'status' => 1];
```

And the result will be without new alerts until we press save on `/admin/content/alerts-rearrange` page

## Possible solutions

1. Add alert 'NID' to `draggableviews_structure` table on the node create and write hook update to fix existing items
2. Remove condition by 'NID' from alerts DB query sort by `weight` if `draggableviews_structure` result not empty and merge array with missed items (We will have ordered items in the first place):

```php
    // Get data from draggableviews_structure table.
    $query = \Drupal::database()->select('draggableviews_structure', 'dvs');
    $query->fields('dvs', ['view_name', 'view_display', 'entity_id', 'weight']);
    $query->condition('dvs.view_name', 'alerts_rearrange');
    $query->condition('dvs.view_display', 'page_1');
    $query->orderBy('dvs.weight');
    $weights = $query->execute()->fetchAll();
    $loadByProperties = ['type' => 'alert', 'status' => 1];

    $alerts_entities = $this->entityTypeManager
      ->getStorage('node')
      ->loadByProperties($loadByProperties);

    $alerts = $alerts_entities;

    // Sort alert based on draggable_views data.
    if (!empty($weights)) {
      $alerts = [];
      foreach ($weights as $row) {
        if (!isset($alerts_entities[(int)$row->entity_id])) {
          continue;
        }
        $alerts[(int)$row->entity_id] = $alerts_entities[(int)$row->entity_id];
        unset($alerts_entities[(int)$row->entity_id]);
      }
    }

    $alerts = array_merge($alerts, $alerts_entities);
```

**Comment by podarok** [comment]
@danylevskyi @dmytrolavrinenko
The bug we had an issue with a while ago on Y North
