### ISSUE TITLE
GroupEx Pro -> PEF: GroupEx pro integration requires module "Open Y Mappings Feature"

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2384]
**Test Environment:**
Environment: | https://sandboxes-d9.openy.org/
Open Y version | 8.x-2.8.0 
Open Y installation type | Custom

**Description:**
If you wish to run GroupEx pro integration with PEF you need to install the module called "OpenY PEF GXP Sync", however, to configure integration itself you need to install the module "Open Y Mappings Feature" which will not be installed while enabling the main module responsible for the synchronization. The needed dependency is missing. 
![image](https://user-images.githubusercontent.com/6285570/105364813-a3a92180-5c0e-11eb-90c7-8334a4f0ea35.png)

**Comment by sarah-halby** [comment]
Storypoint: 1

**Comment by podarok** [comment]
This is fixed in the latest 9.x-2.x
