### ISSUE TITLE
GroupEx Pro -> PEF: All imported sessions are unpublished by default. 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2387]
**Test Environment:**
Environment: | https://sandboxes-d9.openy.org/
Open Y version | 8.x-2.8.0
Open Y installation type | Custom

**Description:**
According to the module logic, all newly created sessions are unpublished https://github.com/ymcatwincities/openy/blob/9.x-2.x/modules/custom/openy_pef_gxp_sync/src/syncer/Saver.php#L190 and due to this, they do not appear on the Schedules page. 

We have not found any logic that will change this status in the future. Given the situation, with the status, we would say the integration does no work fully. 

If there is a logic or steps that should be executed to change this status, then the module readme file https://github.com/ymcatwincities/openy/blob/9.x-2.x/modules/custom/openy_pef_gxp_sync/README.md should be updated to cover this.

**Comment by ddrozdik** [comment]
On one of Five Jars' projects we added a custom hook to publish sessions. The code looks like this 

```php
/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function ciymca_pef_gxp_sync_node_presave(EntityInterface $entity) {
  if (!in_array($entity->bundle(), ['session', 'class', 'activity'])) {
    return;
  }
  if (!$entity->isNew()) {
    return;
  }
  $entity->setPublished();

  if ($entity->hasField('moderation_state')) {
    $entity->set('moderation_state', 'published');
  }
}
```

**Comment by podarok** [comment]
See https://github.com/ymcatwincities/openy/issues/2388#issuecomment-768200715 @ddrozdik
