### ISSUE TITLE
GroupEx Pro -> PEF: Documentation on how to configure syncronization is not full

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2389]
Module https://github.com/ymcatwincities/openy/tree/9.x-2.x/modules/custom/openy_pef_gxp_sync provides a Readme file on how to configure and run synchronization. However, it does not contain the required steps on how to enable the sync method and configure mappings. 

The full instruction might look like this: 
1. Login as Admin 
2. Go to Extend (/admin/modules)
3. Install modules `OpenY PEF GXP Sync` and `Open Y Mappings Feature`  and all related (asked on the next step)
4. Go to Open Y -> Integrations -> GroupEx Pro -> GroupEx Pro settings (/admin/openy/integrations/groupex-pro/gxp)
5. Open URL https://www.groupexpro.com/gxp/api/openy/view/36/204 and verify there is a json response
5. Enter Client Id
6. Enter Activity (`Group Exercise Classes` (choose node of type Activity) Most likely ID will be 94 if this is a default demo content). 
7. Enter Locations Mapping, in the following format, see an example below: 
202,West YMCA
204,Downtown YMCA
203,East YMCA
3718,South YMCA
8. Save configuration 
9. Go to the page Configuration -> System -> YMCA Sync settings (/admin/config/system/ymca-sync)
10. Enable checkbox with the label `openy_pef_gxp_sync` and Save configuration
11. Go to the page Open Y -> Settings -> Mappings -> Mapping list (/admin/openy/settings/mappings/mapping)
12. Add mappings for every branch you would like to synchronize: 
- Enter the name of the mapping to easily identify it in the future, for instance, `West YMCA GXP sync mapping`
- Authored by keep as is
- Locations - choose Branch
- Groupex ID - Enter GroupEx ID
- Save
13. Run `drush openy-pef-gxp-sync` command from your project docroot.

Other than that I would like to bring another question, that potentially will direct us to create a separate issue: 
`Why does it require mapping configuration in two places?` There is a mapping on step 7 which should be added on the groupex settings page and creating mapping entities is also a required step (see step 11 and 12)

P.S. This instruction should be updated once these issues are fixed: 
https://github.com/ymcatwincities/openy/issues/2385
https://github.com/ymcatwincities/openy/issues/2384
https://github.com/ymcatwincities/openy/issues/2380
https://github.com/ymcatwincities/openy/issues/2386

**Comment by podarok** [comment]
Added to wiki and updated accordingly to Drush 10 support https://github.com/ymcatwincities/openy/wiki/GroupEx-PRO-quick-start

**Comment by podarok** [comment]
I guess we can close this one @sarah-halby 
@ddrozdik let us know if anything missed here

**Comment by ddrozdik** [comment]
Perfect. Thanks.

**Comment by sarah-halby** [comment]
Thanks, @podarok & @ddrozdik! Closing ticket.
