### ISSUE TITLE
Search: Enabling/disabling search in Carnation does not work

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#2391]
**Test Environment:**
Environment: | https://sandboxes-d9.openy.org/
Drupal version | 9.0.10
Open Y version | 9.x-2.8.0
Open Y installation type | Custom
Open Y theme | Carnation

**Steps to reproduce:**
1. log in as Admin 
2. Go to Appearance -> Installed themes 
3. Find "Open Y Carnation" (it should be default theme) and open settings 
4. Verify there is a collapsible search fieldset and "Display the search form" checkbox

![image](https://user-images.githubusercontent.com/6285570/105513343-3ca96c80-5ce3-11eb-8847-559fc41a170f.png)

5. Verify after enabling/disabling checkbox search icon and form appears/disappears from the header 

![image](https://user-images.githubusercontent.com/6285570/105513409-534fc380-5ce3-11eb-8b88-9fdc33499367.png)

**Current state:**
After disabling the checkbox and saving configuration, nothing happens, and the checkbox remains enabled. Search icon and form not hiding.

**Comment by sarah-halby** [comment]
Note for a future fix: need to also test on Lily & Rose themes to determine if the issue is replicated using the settings for those themes.

**Comment by sarah-halby** [comment]
Ticket in Jira: https://openy.atlassian.net/browse/PRODDEV-363
