### ISSUE TITLE
prgf_teaser image is too small

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2406]
![Health_and_Fitness](https://user-images.githubusercontent.com/238201/108743225-3125ad00-74fe-11eb-99e8-44bc924b9c3a.png)
https://github.com/ymcatwincities/openy/blob/0bd6ad954588c3f702c6e472dd705cf6de31fbd9/modules/openy_features/openy_prgf/modules/openy_prgf_teaser/config/install/crop.type.crop_260_220.yml#L10

In Carnation, the Teaser Paragraph can render the `prgf_teaser` image style at wider than its output dimensions, resulting in a blurry image. 

I'd recommending doubling the pixel dimensions in the above referenced file and providing an update hook.

**Comment by sarah-halby** [comment]
@froboy this is a duplicate for #2347 and this has been created in Jira in the Maintenance board: https://openy.atlassian.net/browse/MAINTAIN-35 - the 5Jars team is working on it and it should be completed by March 5th. If there is something we missed and this is not a duplicate, please let me know.

**Comment by froboy** [comment]
@sarah-halby ugh. not only a dupe but a self-dupe. 🤦  feel free to revoke my issue-creating privileges. Thanks for the catch.

**Comment by sarah-halby** [comment]
Consider this your final warning @froboy ;-)
