### ISSUE TITLE
Indicate that Membership Calculator will not work until Location settings are updated

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2410]
As per #2341, the Membership Calculator will not work until the **Open Y Location Filter Settings** are updated (I've documented this [on the message board](https://community.openymca.org/t/membership-calculator-paragraphs-open-y-user-docs/908#troubleshooting)). This results in what looks like "broken" functionality on the sandbox and Open Y "out-of-the-box" installs.

In order to reduce that confusion I propose two options:

1. Pre-populate the **Open Y Location Filter Settings** so that the Membership Calculator works out of the box.

OR

2. Add a help topic related to the Membership Calculator Paragraph (like the "Blogs..." and "Open Y Content Overview" on /content) that instruct users that they'll need to log in and edit the location settings in order for step 2 of the membership calculator to work.

**Comment by sarah-halby** [comment]
Story point 3 to update the documentation. @froboy, @podarok and I met today to discuss this and we are going to move forward with option 2. The membership framework is on the list to update for Q2 if approved by Y-USA.

**Comment by sarah-halby** [comment]
@froboy added to Jira with this ticket: https://openy.atlassian.net/browse/PRODDEV-246

**Comment by sarah-halby** [comment]
@froboy this will be in the 9.2.9.1 point release summer 2021.
