### ISSUE TITLE
News Posts only show "Image & Description" Fields in Content Area

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#2413]
**Issue Description:**
This issue was brought to my attention by ymcagreenville.org.  When adding any paragraph to the "Content Area" of a News Post, it doesn't actually display on the node.  The Image & Description fields show, but nothing else in the Content Area.

Using the sandbox website as an example: https://sandbox-carnation-cus.openy.org/news/learn-about-camp-terrys-history. I have only tested this in Carnation.

![image](https://user-images.githubusercontent.com/32372465/109038141-0cae0a00-7691-11eb-882b-c171043e9457.png)

**Proposed Solution:**
`/openy_carnation/templates/node/news/node--news--full.html.twig`
Update News Posts template to print out the contents `{{ content.field_content }}` on line 100, just below the description field.  

**Notes:**
In looking further, it appears that the Blog and Events content type templates also omit the contents of "Content Area" besides the defined field.  

`./openy_carnation/templates/node/event/node--event--full.html.twig`
`./openy_carnation/templates/node/blog/node--blog--full.html.twig`

So it's possible this is not an issue, but rather a feature request.  Which is why I'm submitting it here first.  Thanks!

**Comment by sarah-halby** [comment]
@podarok please review this ticket for us to talk through during our weekly review.

**Comment by sarah-halby** [comment]
@jwtechdesign - assigned this to @podarok to determine if it is a feature request or a bug fix. We've created a ticket in Jira to prioritize: https://openy.atlassian.net/browse/MAINTAIN-56

**Comment by podarok** [comment]
This is Carnation only issue. 
I'm not sure why this wasn't added to Carnation. I see this field was added 4 years ago. 

For Lily it was enabled 4 years ago during decoupling from YMCA of Long Island - back in 2018 https://github.com/ymcatwincities/openy/pull/920
For Rose it was done a bit earlier back in 2017 - https://github.com/ymcatwincities/openy/pull/79
Events were introduced in May 2018 https://github.com/ymcatwincities/openy/pull/1013 and seems like Carnation was not supported.

Seems like this was never needed for Carnation for CTs like News, Blogs, and Events

Here is a PR https://github.com/ymcatwincities/openy/pull/2419 , in testing now

**Comment by podarok** [comment]
@jwtechdesign please review https://github.com/ymcatwincities/openy/pull/2419
