### ISSUE TITLE
Possible issue with Repeat Manager (OpenY Repeat) and CLI mode

### ISSUE THREAD

**Issue by danylevskyi** [ymcatwincities/openy#2421]
We just faced an issue with Time Zone conversion in OpenY Repeat module while using CLI mode. Effectively, we are getting different timezones on repeat_event entity while creating session instance through the web interface and CLI.

**What's the actual impact?** Session nodes created by CLI scripts will not be shown in the Schedules interface if the session ends on the next day by UTC time.

### How to reproduce

Let's use session with next parameters:

- Date: 7 of March 2021
- Start time: 03:45pm
- End time: 08:45pm

1. Create session from UI and it will show as expected in Schedules.
2. Create session with the same parameters using custom Drush command and you'll get wrong  repeat event which will never show in Schedules.

In database we'll see repeat event with invalid timestamp.

1. Start: 21:45, 7 of March (UTC), End: 02:45 8 of March (UTC) 
2. Start: 21:45, 7 of March (UTC), End: 02:45 7 of March (UTC) 

We see that 2nd item has invalid date after conversion.

The patch below illustrates the issue. Looks like default timezone should get from Site Regional settings instead of environment.

Please, note the code below is not a solution.

```diff
diff --git a/docroot/modules/contrib/openy_repeat/src/RepeatManager.php b/docroot/modules/contrib/openy_repeat/src/RepeatManager.php
index 00043773cb..7a91ced4a7 100644
--- a/docroot/modules/contrib/openy_repeat/src/RepeatManager.php
+++ b/docroot/modules/contrib/openy_repeat/src/RepeatManager.php
@@ -263,6 +263,10 @@ public static function calcSessionInstancesBySchedule(array $session_schedule, $
       'saturday' => '6',
       'sunday' => '7',
     ];
+    if (PHP_SAPI === 'cli') {
+      $default_tz = date_default_timezone_get();
+      date_default_timezone_set('America/Chicago');
+    }
     foreach ($session_schedule['dates'] as $schedule_item) {
       foreach ($schedule_item['days'] as $weekDay) {
@@ -312,7 +316,9 @@ public static function calcSessionInstancesBySchedule(array $session_schedule, $
         }
       }
     }
-
+    if (PHP_SAPI === 'cli') {
+      date_default_timezone_set($default_tz);
+    }
     return $session_instances;
   }
@@ -455,9 +461,19 @@ public static function loadSessionSchedule(NodeInterface $node) {
       ];
       $_period = $date->field_session_time_date->getValue()[0];
+
+      if (PHP_SAPI === 'cli') {
+        $default_tz = date_default_timezone_get();
+        date_default_timezone_set('America/Chicago');
+      }
+
       $_from = DrupalDateTime::createFromTimestamp(strtotime($_period['value'] . 'Z'));
       $_to = DrupalDateTime::createFromTimestamp(strtotime($_period['end_value'] . 'Z'));
+      if (PHP_SAPI === 'cli') {
+        date_default_timezone_set($default_tz);
+      }
+
       $schedule_item['period']['from'] = $_from->format('Y-m-d');
       $schedule_item['period']['to'] = $_to->format('Y-m-d');
```

We are seeking a proper solution.

**Comment by sarah-halby** [comment]
Once Y North has a fix, @podarok will backport the fix into Open Y. The issue lies with issues in the old GroupExPro API.

**Comment by sarah-halby** [comment]
Update from Y North: ITCare will deploy fix to Y North on 3/18. Next week @podarok will backport to Open Y.

**Comment by podarok** [comment]
Deploy will happen tomorrow, 24 March. Backport afterwards

**Comment by sarah-halby** [comment]
This issue is still being fixed - scheduled to be fixed on April 1, 2021. After this is complete, this will be backported to Open Y.

**Comment by sarah-halby** [comment]
@podarok has this issue been backported after the fix in April? If so, was it included in the May release? If not, please add to the upcoming point release notes. cc @gianni-imagex

**Comment by podarok** [comment]
This is backported.

**Comment by sarah-halby** [comment]
@podarok was it included in the May release?

**Comment by podarok** [comment]
@sarah-halby yes, it was
