### ISSUE TITLE
openy_prgf_gallery and openy_prgf_banner get disabled due to entity_reference dependency (Drupal 9)

### ISSUE THREAD

**Issue by vitalii-stepaniuk** [ymcatwincities/openy#2424]
On upgrading of a site to Drupal 9, during run of system_post_update_uninstall_entity_reference_module(), where entity_reference is getting uninstalled, openy_prgf_gallery and openy_prgf_banner modules get disabled too, due to this dependency:

https://github.com/ymcatwincities/openy/blob/7f01e9a3d7438f1abd37b9568ce0e2e83469d053/modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.info.yml#L16

**Comment by podarok** [comment]
I'll work on getting this fixed soon
