### ISSUE TITLE
Small Banner Styling Issue for Button

### ISSUE THREAD

**Issue by sarah-halby** [ymcatwincities/openy#2430]
Issue reported by Silicon Valley Y, using Carnation Standard on 8.9.11

By using the icon within the WYSIWYG editor for a button that you could use to still feature a button in that paragraph type; however, the styling is off when you do so. The button link within small banner styling does not work as intended. 

Needs to be tested in D8 & D9. 

Original request reported by Amber R: 
If my memory serves, I could have sworn that the content type “small banner” used to have a link field that added a button to the banner, as we see on “banner” currently. However, it looks like that field is no longer part of the “small banner”. I’d appreciate it if you could tell me if that feature did exist in that content type, and if it did, was it removed during an update, or is this a bug we need to fix?

@podarok believes that it may be an issue with bootstrap.

**Comment by podarok** [comment]
Not clear how to reproduce the issue @sarah-halby 
Let's discuss on our scrum

**Comment by sarah-halby** [comment]
Ticket has been updated with additional details via conversation in scrum.

**Comment by sarah-halby** [comment]
Closing this issue as alternative solutions have been presented to Silicon Valley Y.
