### ISSUE TITLE
"Events Post Listing" and "Upcoming Events" Paragraph should filter out past events

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2438]
The views powering both of these don't have a filter to exclude events that have ended. I believe the proper filter is "End date >= today"

**Comment by sarah-halby** [comment]
Jira ticket for this issue: https://openy.atlassian.net/browse/MAINTAIN-64

**Comment by sarah-halby** [comment]
@froboy I believe this issue has been closed and added to the master test plan. @gianni-imagex please add this issue to the draft release notes if it has not been already. cc @podarok

**Comment by gianni-imagex** [comment]
@sarah-halby Added to draft release notes. cc @podarok
