### ISSUE TITLE
Contextual menu is not accessible on Lily main nav

### ISSUE THREAD

**Issue by kairamkondarajesh** [ymcatwincities/openy#2442]
**Repro Steps**

- Visit https://sandbox-rose-cus.openy.org/
- Disable one of the main nav items
- Go back to any page
- observe the quick edit link is not accessible (see attached gif)

  
**Expected Behavior**
While hovering over the main navigation, the pencil icon should display. Moving your cursor to the pencil icon should keep it accessible. Clicking the pencil icon reveals a small menu, with "Quick Edit" among the choices.

**Actual Behavior**
The quick-edit pencil icon is no longer visible to Site Owners.

**Acceptance Criteria**
While hovering over the Blog header or footer, the pencil icon displays for Site owners.
Clicking the pencil icon reveals a small menu, with "Quick Edit" among the choices.

**Comment by froboy** [comment]
@kairamkondarajesh please attempt to reproduce this on https://sandbox-rose-cus.openy.org and provide notes on how to reproduce.

**Comment by kairamkondarajesh** [comment]
@froboy We don't have site owner role on https://sandbox-rose-cus.openy.org So reproduced with admin user.
Steps :
After login with admin/site owner role, Hover on the header section and able to see the pencil icon display. When user try to click on pencil icon it disappear immediately. 
![image](https://user-images.githubusercontent.com/6428296/116354704-6d370000-a816-11eb-9a41-fcea59f39c3f.png)

**Comment by froboy** [comment]
![openy_menu_quick_edit](https://user-images.githubusercontent.com/238201/116699259-fbcc8e00-a98a-11eb-8325-d0a510218ab8.gif)

I was able to find the same when removing a link from the main nav menu

**Comment by kairamkondarajesh** [comment]
Raised PR : https://github.com/ymcatwincities/openy/pull/2448

**Comment by sarah-halby** [comment]
@podarok have you reviewed this PR and approved? If so, can this be added to the point release and this issue closed? cc @gianni-imagex

**Comment by podarok** [comment]
Yes, this is fixed
Thank you for the reminder @sarah-halby
