### ISSUE TITLE
[Carnation] Icons no longer appearing in Grid Content Paragraph

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#2443]
Steps to Recreate:

1) In Carnation theme, add a Grid Content paragraph to any page
2) Add an icon class in the "Icon Class" field (any free FontAwesome icon class should do)
3) Save the page.

The icon does not show.  It does not print out in the code under `div.inner > span.d-block`.  I've just noticed this after updating one of our Y sites to Open Y (openy-8.x-2.7.3).  However, it behaves the same on the D8 & D9 sandbox sites.

**Comment by podarok** [comment]
Not an issue in Lily
![image](https://user-images.githubusercontent.com/563412/116676158-4f50d300-a9af-11eb-9601-29c10e8d271d.png)

Not an issue in Rose
![image](https://user-images.githubusercontent.com/563412/116676299-7c9d8100-a9af-11eb-88b6-2f6522c71bf1.png)

**Comment by podarok** [comment]
Seems like a bug was introduced in https://openy.atlassian.net/browse/MAINTAIN-33 in PR #2414
