### ISSUE TITLE
Cloning a recurring event does not set the roles correctly.

### ISSUE THREAD

**Issue by TomScarboroughYMCA** [ymcatwincities/openy#2444]
**Repro Steps**

- Log into Virtual Y site as a Site Owner
- Edit an Event
- Click the Clone tab 
- After verifying form is complete, scroll to the bottom to observe no Virtual Y Permissions section present.
- Save the cloned event
- View the event in the Schedule
- Edit the cloned event, scroll down to view the Virtual Y Permissions. 
- Note that Virtual YMCA and Virtual YMCA Premium roles are not selected.
- Sign out, then log in as a Virtual YMCA member.
- Note the event is missing in the Schedule

**Expected Behavior**

Cloning events should carry over the Virtual Y Permissions already set in the source event.

**Actual Behavior**

Cloning events do not provide a UI for selecting Virtual YMCA roles, and those roles are not automatically carried over from the source event.

**Comment by froboy** [comment]
@TomScarboroughYMCA I believe this should be opened on ymcatwincities/openy_gated_content, not here.

**Comment by TomScarboroughYMCA** [comment]
Will move this - thanks
