### ISSUE TITLE
Open Y Location Filters Broken

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#2445]
"Step 2" of the built in Membership Calculator is populated by the following config page (/admin/config/content/location-filter-settings).  I believe this is meant to allow site owners to be able to include or exclude the branches / camps from the filtering system.

I'm working with a YMCA who has multiple branches that are not "full service membership" branches, and so, would only like to show a few of their branches in the membership calculator.  However, it seems you can only select All or None of the branches/camps.

Steps to recreate:

1) Visit [Sandbox](https://sandbox-carnation-cus.openy.org/admin/config/content/location-filter-settings) and Navigate to the Open Y Locations Filter Page (/admin/config/content/location-filter-settings).

2) Uncheck "All" and select any combination of the remaining options.  Click "Save".

3) The page will reload will all options checked.

Asking for advice or other ideas.  Thanks!!

**Comment by podarok** [comment]
By importing config with "selected" locations I was able to made system react 
![image](https://user-images.githubusercontent.com/563412/116693230-43244000-a9c6-11eb-910f-75716a017016.png)
So issue is with Form submit handler. For some reason it doesn't respect user's settings
