### ISSUE TITLE
Incorporate Drupal 9.1 core lazy loading and get rid of blazy subsystem

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2457]
Starting from 9.1 in Drupal core there is a lazy loading enabled https://www.drupal.org/node/3173719
In OpenY we have blazy, which had a bunch of issues and is contrib https://github.com/ymcatwincities/openy/blob/9.x-2.x/composer.json#L14

We should work towards sunsetting blazy in favor of core's solution.

Issue on drupal.org https://www.drupal.org/project/blazy/issues/3215769 -> https://www.drupal.org/project/blazy/issues/3213258

**Comment by anpolimus** [comment]
I'll be very happy to get rid of Blazy since it is usually our pain during each Open Y upgrade.
Can help with development and testing efforts.

**Comment by podarok** [comment]
https://www.drupal.org/project/blazy/issues/3213258
