### ISSUE TITLE
Group Exercises Locations to Group Exercises widget params transfer doesnt work with &

### ISSUE THREAD

**Issue by anpolimus** [ymcatwincities/openy#2512]
Hello.
During the investigation of the client's problem, I've noticed that param sending from the page with schedules locations select to schedules page doesn't work properly if there is & in the title of the branch.

Given
1. Group Exercises Locations widget with branches that have & in the title.
2. Group Exercises widget that cant properly set pre-defined locations from the previous widget.

Video: https://www.loom.com/share/b5e9f520f59e4740b82b2faf218b1cd5

**Comment by sarah-halby** [comment]
@anpolimus we've added this ticket to Jira for review: https://openy.atlassian.net/browse/MAINTAIN-121

**Comment by podarok** [comment]
This was fixed in August release
Thank you
