### ISSUE TITLE
Carnation: Images on blog posts overflow the page on mobile

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2534]
See https://sandbox-carnation-cus.openy.org/blog/mood-boosting-foods. I tested and this only applies to carnation.

![Mood-boosting_foods___Drush_Site-Install](https://user-images.githubusercontent.com/238201/129978203-c2c74edb-4227-4e54-8440-ea10a33b62b9.png)

Something like this should do the trick:

```
.field-blog-image img {
    width: 100%;
    height: auto;
}
```

**Comment by shelleygoetz** [comment]
Link to Jira ticket: https://openy.atlassian.net/browse/MAINTAIN-166
