### ISSUE TITLE
Subprogram listing item image style is too small

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2542]
To reproduce: 

- Visit https://sandbox-carnation-cus.openy.org/programs/kids-and-family-activities (or lily or rose)
- Observe `node_program_subcategory_teaser` images are rendered at 360x300 but displayed much wider depending on your screen size.
![Kids_and_Family_Activities___Drush_Site-Install](https://user-images.githubusercontent.com/238201/132054088-fa12a347-97b7-499c-9b05-887687791acb.png)

It looks like images could be up to 740px wide on Lily and Rose, so we might want to 3x the default size (1080×900) to be safe.

Those configs are in https://github.com/open-y-subprojects/openy_features/tree/main/openy_node/modules/openy_node_category

**Comment by sarah-halby** [comment]
@shelleygoetz could you please open a ticket in the jira maintenance board?

**Comment by shelleygoetz** [comment]
https://openy.atlassian.net/browse/MAINTAIN-171

**Comment by shelleygoetz** [comment]
Ticket has been marked as Done in Jira.

**Comment by froboy** [comment]
Was there a change made? I didn't see a link in JIRA to a PR.

**Comment by sarah-halby** [comment]
@shelleygoetz can you please provide the PR from testing for @froboy ?

**Comment by shelleygoetz** [comment]
@podarok need to locate PR

**Comment by podarok** [comment]
Seems like fixed in https://github.com/ymcatwincities/openy/pull/2411 https://openy.atlassian.net/browse/MAINTAIN-35

**Comment by sarah-halby** [comment]
Closing the issue per the above PR
