### ISSUE TITLE
1 Column paragraph body text looks awkward

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2557]
- Edit a Landing Page
- Add a `1 Column` Paragraph to the Content
- Add some text to the `Paragraph Description`
- Observe the text doesn't match the body text of the `Simple Content`  Paragraph

In screenshots, the top is "Simple Content" the bottom is "1 Column".

Here's Carnation:
![image](https://user-images.githubusercontent.com/238201/134583117-d0c935b0-83db-49f3-981d-b6428537f6f6.png)

Here's Lily:
![image](https://user-images.githubusercontent.com/238201/134583932-97761487-c05e-4a2f-9916-ebe9e7c4ee66.png)

Rose:
![image](https://user-images.githubusercontent.com/238201/134584155-5bf2d666-b6d4-4af8-9e7e-d5f9dc2a46ff.png)

**Comment by sarah-halby** [comment]
@shelleygoetz please open a ticket in Jira maintenance board.

**Comment by froboy** [comment]
@sarah-halby the YUSA team will be working on this and we'll have a PR shortly.

**Comment by sarah-halby** [comment]
Thanks @froboy ! We'll get it into Jira for review, testing, and QA. :-)

**Comment by Open-Y-Distro** [comment]
Sorry @sarah-halby @froboy  I seemed to have missed this one last week. Added to Jira here: https://openy.atlassian.net/browse/MAINTAIN-179

**Comment by shelleygoetz** [comment]
Sorry @sarah-halby @froboy  I seemed to have missed this one last week. Added to Jira here: https://openy.atlassian.net/browse/MAINTAIN-179

**Comment by sarah-halby** [comment]
@froboy is your team still working on this issue? I don't see a PR in the comments for this one so I wanted to confirm.
