### ISSUE TITLE
The Schedule pages stop working in some content conditions

### ISSUE THREAD

**Issue by AndreyMaximov** [ymcatwincities/openy#2565]
This is a cross-issue for https://github.com/ynorth-projects/openy_repeat/issues/12

---

In some situations, the Schedule pages stop working after the initial load and change in filters/date. The application simply freezes and there is an error in the console.
![image](https://user-images.githubusercontent.com/5453109/135062327-6209d6ce-cf61-4028-8463-4f7c96d7201d.png)

The cause of the issue relates to the `key` attribute of `v-for` constructions.
Whenever a `v-for` construction is used with the `key` attribute the attribute values must be unique (see https://vuejs.org/v2/guide/list.html#Maintaining-State).

The `openy_repeat` module does have at least one `v-for` construction with the `key` attribute
https://github.com/ynorth-projects/openy_repeat/blob/9.x-2.x/templates/openy-repeat-schedule-dashboard--table.html.twig#L36
The values used as keys are not guaranteed to be unique in this situation as Node IDs of session nodes are used. In order to reproduce the non-unique keys, just add a couple of session time paragraphs that will schedule that event more than once a day.

For production, the module uses the production build of the Vue.js (see https://github.com/ymcatwincities/openy/blob/9.x-2.x/modules/custom/openy_system/openy_system.libraries.yml#L14). The production build suppresses all the warnings.

The non-minified (non-production) build of the Vue.js (https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.js) will show warnings:
![image](https://user-images.githubusercontent.com/5453109/135059915-5ab51880-14f2-4c6b-bee7-d8d544de28e2.png)

For large schedules (with more than a single page of content a day), the error might occur:
| Production | Non-prouduction Vue.js |
|---|---|
|  ![image](https://user-images.githubusercontent.com/5453109/135062333-13b7da29-cce8-45a1-bae5-79b0fc4769e4.png)|  ![image](https://user-images.githubusercontent.com/5453109/135061875-be9a718b-23f5-49e1-801c-9e9f48899886.png)|
|   |   |

Interestingly, the issue is not reproduced in the Carnation. That's because the template is overridden :facepalm: :
https://github.com/ymcatwincities/openy/blob/9.x-2.x/themes/openy_themes/openy_carnation/templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig#L36
The `key` attribute is removed in that override.

---

The solution.

Technically, removing the `key` attribute should work just fine.

---

Error messages:

<details>
<summary>Production error message</summary>
<p>

```
 TypeError: Cannot read properties of undefined (reading 'key')   vue.min.js:6 
     at ir (vue.min.js:6)
     at vue.min.js:6
     at x (vue.min.js:6)
     at vue.min.js:6
     at x (vue.min.js:6)
     at a.__patch__ (vue.min.js:6)
     at a.e._update (vue.min.js:6)
     at a.r (vue.min.js:6)
     at fn.get (vue.min.js:6)
     at fn.run (vue.min.js:6)
```
</p>
</details> 

<details>
<summary>Non-production error messages</summary>
<p>

```
 [Vue warn]: Error in nextTick: "TypeError: Cannot read properties of undefined (reading 'key')"
 warn @ vue.js:634

 TypeError: Cannot read properties of undefined (reading 'key') 
     at sameVnode (vue.js:5818)
     at updateChildren (vue.js:6220)
     at patchVnode (vue.js:6320)
     at updateChildren (vue.js:6194)
     at patchVnode (vue.js:6320)
     at VueComponent.patch [as __patch__] (vue.js:6481)
     at VueComponent.Vue._update (vue.js:3949)
     at VueComponent.updateComponent (vue.js:4067)
     at Watcher.get (vue.js:4478)
     at Watcher.run (vue.js:4553)
```
</p>
</details>

**Comment by podarok** [comment]
@shelleygoetz @sarah-halby to add to Jira as a bug, please
Thank you @AndreyMaximov

**Comment by shelleygoetz** [comment]
@sarah-halby added to maintain: https://openy.atlassian.net/browse/MAINTAIN-176

**Comment by shelleygoetz** [comment]
Pending next openy release.

**Comment by sarah-halby** [comment]
This was completed for the 9.2.11 release in November. @AndreyMaximov
