### ISSUE TITLE
Activity Finder v.4: "Clear Filters" button doesn`t work

### ISSUE THREAD

**Issue by Juliazk** [ymcatwincities/openy#2566]
The "Clear Filters" button doesn`t work in Activity Finder v.4.

**Steps to reproduce:**
1. Go to Activity Finder version 4
2. Enter some query that would return no results (e.g. "TEMT")
3. Click on the "Clear Filters" button
![image](https://user-images.githubusercontent.com/41994470/135293028-db14cf1b-5220-4a6e-8b59-0883f45bd05e.png)

**Expected result:** The selection of filters is reset and users are able to view events.
**Actual result**: Nothing happens and the "Clear Filters" button is highlighted with the green border.
![image](https://user-images.githubusercontent.com/41994470/135293813-b3414a83-84b1-456e-b13c-9e508b41b348.png)

**Comment by sarah-halby** [comment]
@shelleygoetz can you please open a ticket in the maintain board backlog and tag to the activity finder epic?

**Comment by shelleygoetz** [comment]
@sarah-halby added to Jira: https://openy.atlassian.net/browse/MAINTAIN-177

**Comment by shelleygoetz** [comment]
Ready for testing, can close with next AF release.

**Comment by sarah-halby** [comment]
https://github.com/ymcatwincities/openy_activity_finder/pull/96 - This was fixed via this PR and will be released as a part of the Nov 2021 release. Closing this ticket.
