### ISSUE TITLE
Carnation compilation errors

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2577]
On attempting to compile CSS in Carnation I receive a number of errors and `npm run build` fails. I'm assuming there may be a specific version of node/npm/yarn that's required, but I can't figure it out. We should specify this in the readme.

Tested with:
- node v14.18.1 (npm v6.14.15)
- node v17.0.1 (npm v8.1.0)

Old version throws... lots of errors. New version throws this. I've also tried `npm rebuild`.

```
npm run build

> Carnation@1.0.0 build
> webpack --config webpack.build.js --debug --output-pathinfo

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/.../Projects/openy/themes/openy_themes/openy_carnation/node_modules/webpack/lib/util/createHash.js:135:53)
...
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
```

**Comment by shelleygoetz** [comment]
@podarok to verify if fixed.

**Comment by shelleygoetz** [comment]
Added to Jira: https://openy.atlassian.net/browse/MAINTAIN-185

**Comment by podarok** [comment]
Here is a doc https://github.com/ymcatwincities/openy/wiki/How-to-develop-themes-in-Open-Y

I've checked - all 3 themes are working well when follow README.md tutorials on full Open Y tree

Let us know if you have any specific issues still @froboy

**Comment by sarah-halby** [comment]
I'm going to close this issue and send it directly to Tom as well.
