### ISSUE TITLE
Two images plugins WYSIWYG

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#260]
We need to have one images plugin for CKEditor instead of two. I believe we are going to go with the one coming from Media.

https://monosnap.com/file/taOPQHp2mrwrJrpVvmIYvPioUN5yEL

Also currently in Media plugin we have three image displays. We need instructions how to add more. Shame on me, but I was not able to find these settings from UI. https://monosnap.com/file/RR3H8WX6LrRDWArQdOa1Qai0zLaQYe

**Comment by ivan-berezhnov** [comment]
This issue resolved
PR https://github.com/ymcatwincities/openy/pull/310 merged.
