### ISSUE TITLE
Open Y Alerts: not found errors for Slick fonts

### ISSUE THREAD

**Issue by dchubar-fj** [ymcatwincities/openy#2600]
CSS related to Open Y Alerts uses the absolute path to include Slick fonts, like `/static/media/slick.ced611da.eot` or `/static/media/slick.b7c9e1e4.woff`
https://github.com/open-y-subprojects/openy_node_alert/blob/411f4bda4343477fe99be916f7246083708338fd/js/openy-alerts/build/static/css/main.css#L133

It's a wrong absolute path, fonts are not available by https://sandbox-carnation-cus.openy.org/static/media/slick.ced611da.eot because located inside the `openy_node_alert` module. This results in 404 errors that can affect SEO.

**Comment by sarah-halby** [comment]
@shelleygoetz please open a ticket in Jira.

**Comment by shelleygoetz** [comment]
@sarah-halby Jira ticket created: https://openy.atlassian.net/browse/MAINTAIN-223

**Comment by podarok** [comment]
It's not anymore a case
All paths are relative without leading slash 
![image](https://user-images.githubusercontent.com/563412/150791415-812b5ad6-5cb2-4ab2-a5ad-5f23bdc81470.png)

Could you verify on the latest Alerts? @dchubar-fj 

https://github.com/open-y-subprojects/openy_node_alert/releases/tag/1.1.5

**Comment by podarok** [comment]
THis is done
