### ISSUE TITLE
Ensure decoupled theme users understand requirements

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2628]
- Update drupal.org project pages for Carnation, Rose, Lily to recommend that they be installed with openy-project instead of directly
- Add [composer suggest](https://getcomposer.org/doc/04-schema.md#suggest) to themes saying same

**Comment by froboy** [comment]
https://www.drupal.org/project/openy_carnation/issues/3249623 is related to this issue.

**Comment by froboy** [comment]
https://www.drupal.org/project/openy_carnation/issues/3268214
https://www.drupal.org/project/openy_lily/issues/3268253
https://www.drupal.org/project/openy_rose/issues/3268258

![Cursor_and_composer_json_—_DrupalPod_—_Gitpod_Code](https://user-images.githubusercontent.com/238201/157121807-43ee87da-74c5-4576-920b-32aa5c77cf04.png)

**Comment by podarok** [comment]
@froboy you should have access to all 3 themes on d.org

**Comment by podarok** [comment]
https://www.drupal.org/project/openy_carnation/releases/2.0.4

**Comment by podarok** [comment]
https://www.drupal.org/project/openy_lily/releases/1.1.5

**Comment by podarok** [comment]
https://www.drupal.org/project/openy_rose/releases/1.1.2

**Comment by podarok** [comment]
This is done @froboy @KylieAldridge 
Closing
