### ISSUE TITLE
Alerts: empty space after closing the second alert

### ISSUE THREAD

**Issue by Juliazk** [ymcatwincities/openy#2630]
**Issue description**: If a user clicks the arrow to see the second Alert and clicks "Close", empty space will be displayed in place of Alert.

**Steps to reproduce**: 
1. Go to the page with Alerts (there should be at least 2 Alerts to view); 
2. Click the arrow to swipe the first Alert and view the second one;
3. Click "Close" to hide alerts.

**Actual result**: When a user closes the second alert, empty space gets displayed.
![image](https://user-images.githubusercontent.com/41994470/159037989-180fc1a5-f24e-495e-ac8f-aa7ed0d77bbb.png)
**Expected result:** The header should fill in empty space.

**Comment by Juliazk** [comment]
@KylieAldridge Hello! We can backport the solution for the issue. I will keep you posted.

**Comment by manachynskyi** [comment]
Fixed there https://github.com/open-y-subprojects/openy_node_alert/pull/64 , steps for review in the PR.

cc @podarok @froboy @KylieAldridge

**Comment by podarok** [comment]
merged, compiled and tagged in https://github.com/open-y-subprojects/openy_node_alert/releases/tag/1.1.11
Thanks
