### ISSUE TITLE
Location pages WSOD

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2632]
- Visit a location page on any of the sandboxes, like https://sandbox-lily-cus.openy.org/locations/south-ymca
- Observe WSOD and an error in the logs:

> InvalidArgumentException: The date cannot be created from a format. in Drupal\Component\Datetime\DateTimePlus::createFromFormat() (line 253 of /home/jenkins/workspace/SANDBOX_LILY_CUSTOM/build/docroot/core/lib/Drupal/Component/Datetime/DateTimePlus.php).

This seems to be happening in d9 and php8 sandboxes. Prior notices in the logs point to `groupexpro` module but it doesn't look like that's been updated in a while.

**Comment by podarok** [comment]
Fixed
