### ISSUE TITLE
Update CSS Editor to resolve saving issue

### ISSUE THREAD

**Issue by froboy** [ymcatwincities/openy#2637]
`drupal/css_editor:1.3` had a major issue that prevented saving the form: https://www.drupal.org/project/css_editor/issues/3203706

Let's bump the version to ensure folks don't run into that any more. https://www.drupal.org/project/css_editor/releases/2.0.1 seems fine and just requires a composer update.

**Comment by podarok** [comment]
https://github.com/ymcatwincities/openy/pull/2639

**Comment by podarok** [comment]
Solved https://github.com/ymcatwincities/openy/pull/2639

Thank you @froboy
