### ISSUE TITLE
Backport openy_socrates from YGH

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#282]
https://raw.githubusercontent.com/propeoplemd/ymcahouston/master/docroot/modules/custom/openy_socrates/src/OpenyRepositoryTrait.php?token=AAiY1EjpAEFU0Z3t_yE_qOl494TAv_TDks5Y7LCawA%3D%3D

**Comment by podarok** [comment]
And backport cron service https://github.com/propeoplemd/ymcahouston/blob/master/docroot/modules/custom/openy_socrates/src/ExampleSocratesCronService.php

**Comment by YMCA-GTC** [comment]
@podarok Can I please get some help writing a user story for this so I can add it to the roadmap? I am a little bit familiar on Socrates, but could use help writing the user story for the abstraction layer backporting.

**Comment by podarok** [comment]
@YMCA-GTC no need to add to roadmap - OpenY Socrates was backported already https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/custom/openy_socrates
