### ISSUE TITLE
Move footer blocks from theme to module

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#289]
On YGS project I have issue with enabling openy_rose theme from openy.
```
Performing ygs_master_update_8161                                    [ok]
Failed: 'block' entity with ID 'footermenucenter' already exists.    [error]
```
This blocks already exist on our project. It would be great to move this blocks configs to separate module (openy_menu_footer for example):
- openy/config/optional/block.block.openy_rose_fmenu_center.yml
- openy/config/optional/block.block.openy_rose_fmenu_left.yml
- openy/config/optional/block.block.openy_rose_fmenu_right.yml

Also we can check other block configs, I think we can remove configs related to bartik and seven themes from `openy/config/optional`

**Comment by YMCA-GTC** [comment]
@Sanchiz @podarok Can I get some help writing a user story for this to be added to the roadmap?

**Comment by podarok** [comment]
@Sanchiz great module to test with decouple CI scripts which are in progress

Added to decouple first milestone to track.

**Comment by podarok** [comment]
@YMCA-GTC 
user story
as a developer, I want to be able to use part of the OpenY enabled on currently existing site without issues with conflicts of configs. This is a blocker for YGTC/YMCA of Brandywine/YMCA of Greater Houston when they are not initially created as OpenY instances and by following lazy migration delivery team decided to go with per component enabling flow.

**Comment by podarok** [comment]
@YMCA-GTC added to roadmap with Planning status

**Comment by ddrozdik** [comment]
Closing this as not relevant anymore. We introduced new themes with different footer blocks, so blocks are located in themes and theme defines what blocks should be created by default during enabling a theme.
