### ISSUE TITLE
Make /user/register so that user registration disabled in default installs of Open Y

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#315]
As a YMCA team member, when I install Open Y I want registration at /user/register to be disabled by default so that I don't have spam accounts appearing on my new Open Y site.

Done when: Using the Open Y install bash script results in an install of Open Y that has user registration disabled by default. A site administrator can always re-enable this feature in the future if desired.

**Comment by xcf33** [comment]
https://github.com/ymcatwincities/openy/pull/320
