### ISSUE TITLE
This site can’t be reached occasional error.

### ISSUE THREAD

**Issue by alexandar87** [ymcatwincities/openy#316]
As i developer using Mac im getting occasional problems opening a website. 

It usually happens around 2 times per hour, and i need to refresh page until it starts working again. Downtime lasts anywhere between 1min and 10min. 

Is anyone else experiencing same issues, is there any solution?

First i thought it happens when i do **drush cr** but its not actually correct, i did not found exact trigger for that yet.

![screen shot 2017-04-26 at 13 14 06](https://cloud.githubusercontent.com/assets/3238879/25433080/71c8a490-2a87-11e7-8053-5cb3e2b35cec.png)

Thanks
Alex

**Comment by alexschedrov** [comment]
hi @alexandar87,

Are you using CIBox VM? If yes, this probably happens because of collisions between two different instances. Would be great if you can file issue to https://github.com/cibox/cibox.

Thanks!

**Comment by ddrozdik** [comment]
this is an issue for https://github.com/cibox/cibox project - https://github.com/cibox/cibox/issues/576

**Comment by podarok** [comment]
This is not related to OpenY
This is related to partial instability of xip.io service
Please add host to /etc/hosts file to get it stable, as described in CIBox docs
