### ISSUE TITLE
Remove search bar

### ISSUE THREAD

**Issue by xcf33** [ymcatwincities/openy#324]
On mobile and tablet viewpoint, there is the search bar which we should remove completely. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/253281/25544838/588fb974-2c2a-11e7-97aa-20fcfbdaa4e3.png)

![image](https://cloud.githubusercontent.com/assets/253281/25544851/67a0679c-2c2a-11e7-875a-6734b6c88f3b.png)

**Comment by ivan-berezhnov** [comment]
PR https://github.com/ymcatwincities/openy/pull/353
