### ISSUE TITLE
CIBox VM and upgrade path + install steps environment

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#340]
Let's check and adjust if needed.

**Comment by hamrant** [comment]
Also we need this for docksal

**Comment by hamrant** [comment]
Upgrade path command for docksal was implemented here - https://github.com/ymcatwincities/openy-docksal/pull/5

**Comment by hamrant** [comment]
Install steps command for docksal was implemented here - https://github.com/ymcatwincities/openy-docksal/pull/5

**Comment by hamrant** [comment]
I think no need to implement this for vagrant, so we can close current issue.

cc @Sanchiz @podarok

**Comment by alexschedrov** [comment]
@hamrant @podarok those installation types should be already in place in the CIBox.
https://github.com/ymcatwincities/openy-cibox-build/blob/master/reinstall.sh
https://github.com/ymcatwincities/openy-cibox-build/blob/master/reinstall_install.sh
https://github.com/ymcatwincities/openy-cibox-build/blob/master/reinstall_upgrade.sh

So, issue can be closed.
