### ISSUE TITLE
views_block_filter_block remove patch 2790505

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#341]
Remove https://www.drupal.org/files/issues/empty_exposed_forms-2790505-10.patch patch from composer file as it has been committed already.

Currently, composer throws a warning https://monosnap.com/file/3W9rOeiR9P1lYtp5JhndQd6bx2wp5b

**Comment by alexschedrov** [comment]
Thank you!

Fixed in #342.
