### ISSUE TITLE
Taxonomy page design fixes

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#347]
1. Let's update styles for the taxonomy page pager. Should be like here http://www.seattleymca.org/search?query=test.
![image](https://cloud.githubusercontent.com/assets/1316234/25901961/e453a72a-35a0-11e7-92d1-3dc87b0ea55c.png)
![image](https://cloud.githubusercontent.com/assets/1316234/25901998/f4eda220-35a0-11e7-9cbf-e9161865a0eb.png)

2. Too small padding from top
![image](https://cloud.githubusercontent.com/assets/1316234/25901920/d26d2ae0-35a0-11e7-83a2-9b5d7b6633ba.png)

Example: http://sandbox.openymca.org/blog/category/community-outreach

**Comment by ivan-berezhnov** [comment]
PR #367 merged
