### ISSUE TITLE
Add some basic styles for the 404 and 403 pages

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#354]
404 and 403 pages view should be improved.
![image](https://cloud.githubusercontent.com/assets/1316234/25990556/d42cf310-3708-11e7-8298-c7fe2dc9f4ba.png)
![image](https://cloud.githubusercontent.com/assets/1316234/25990571/e333616e-3708-11e7-9c74-ce30867baf7c.png)

**Comment by ivan-berezhnov** [comment]
@Sanchiz what do you like see on 403 and 404 page?
Maybe you have some example?

**Comment by alexschedrov** [comment]
404
![image](https://cloud.githubusercontent.com/assets/1316234/26104495/c5e865aa-3a46-11e7-9d31-b65184def5a0.png)

403
![image](https://cloud.githubusercontent.com/assets/1316234/26104519/e10469ec-3a46-11e7-87d4-623c9b9788ab.png)

**Comment by ivan-berezhnov** [comment]
PR #368
