### ISSUE TITLE
Add textfield to the "Small Banner"

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#366]
Currently, there is a block "Small banner" which provides the possibility to enter a title, select an image and color scheme. 
I suggest adding an extra field for description, which will provide the possibility enter a few lines of text.
An example of such a banner:
![openy 2017-05-16 15-08-02](https://cloud.githubusercontent.com/assets/6285570/26105127/7d14faca-3a49-11e7-959c-1f6b8d1ce6b5.png)

This could be a checkbox which will be adding a field to the form when it enabled.

**Comment by ivan-berezhnov** [comment]
@ddrozdik @Sanchiz 
Please look:
https://monosnap.com/file/SAxpPbXXKT2XDmKnzFGcju0DqMCwwp
Could you please explain:
> This could be a checkbox which will be adding a field to the form when it enabled.

Checkbox must be in admin and when we click on "Show description" checkbox:
1. Show Description textarea in the form when we edit and in the template show description
or
2. Show Description in the template but Description textarea always shows in form when we edit.
What should be?

**Comment by alexschedrov** [comment]
@ddrozdik @ivan-berezhnov I would add only description field like on your screenshot. It could have help text - "Leave empty to hide".
- When it's poppulated - display description
- When it's empty - don't display description

What do you think?

**Comment by ddrozdik** [comment]
@ivan-berezhnov , @Sanchiz I think would be better to add a checkbox "I want to add a description", and when this checkbox is checked then a user can see a field and fill something it. But when the checkbox is not checked then we can't see a field and nothing will be displayed on the page. 
Using this approach we will display the field only when it should be displayed and it will be easier control displaying it on a page. 
What do you think guys?

**Comment by ivan-berezhnov** [comment]
I think both variants good, but:
- https://github.com/ymcatwincities/openy/issues/366#issuecomment-303686907 - More functional and my estimate ~20 m
- https://github.com/ymcatwincities/openy/issues/366#issuecomment-303688351 - More beautiful for the user and my estimate 1~2h
@ddrozdik @Sanchiz

**Comment by alexschedrov** [comment]
@ddrozdik well, we the logic of optional(not required) fields in the same. For me this field seems redundant. I'm fine with both solutions @ddrozdik @ivan-berezhnov
