### ISSUE TITLE
Cleanup location_finder

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#374]
Check usage of openy/modules/custom/location_finder/js/location_finder.js and location_finder_element
it seems that it is not being used (instead we use openy/modules/custom/openy_map/js/map.js)

**TODO** delete this files if location_finder_element from this module not used:
-  openy/modules/custom/location_finder/js/location_finder.js
-  openy/modules/custom/location_finder/img
-  openy/modules/custom/location_finder/src/Element
-  openy/modules/custom/location_finder/src/LocationFinderDataWrapper.php
-  openy/modules/custom/location_finder/location_finder.services.yml
-  openy/modules/custom/location_finder/location_finder.module
-  openy/modules/custom/location_finder/templates

**Comment by rotator** [comment]
To test and merge to dev branch
