### ISSUE TITLE
Groupex Calendar paragraph issues

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#375]
further improvements to be more usable.
Given I have specified id:3 for Twin Cities.
1) By default I can see too much entries. That are loading pretty long time.
I think that we should allow to see only one location at once. And only one day by default. We need to came up with wise limitations.
2) For empty results I still can see the grid without any explanations

![image](https://cloud.githubusercontent.com/assets/4558228/26250068/96c17d1c-3cb1-11e7-8663-cc688972bfde.png)

3) Duplicated '.ics' 
![image](https://cloud.githubusercontent.com/assets/4558228/26250082/9f5ea45e-3cb1-11e7-837b-9243c34be417.png)

Note: On mobile it's looking fine - responsive tables are used.
![image](https://cloud.githubusercontent.com/assets/4558228/26250096/a9d7a138-3cb1-11e7-884c-284441e18ae0.png)

**Comment by YMCA-GTC** [comment]
@Sanchiz With the recent GroupEx integration, can this be closed?

**Comment by podarok** [comment]
This is a GroupEx PRO issue @YMCA-GTC 
Not related to OpenY - we just embed their HTML
