### ISSUE TITLE
Close access to the taxonomy pages

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#378]
Please close access to following taxonomy pages:
![image](https://cloud.githubusercontent.com/assets/1316234/26252297/8d1d2250-3cb8-11e7-988f-46f8b27ba92c.png)

**Comment by yasik78** [comment]
patch is ready for review https://github.com/ymcatwincities/openy/pull/616

**Comment by alexschedrov** [comment]
Duplicate of #634.
