### ISSUE TITLE
Sidebar area in tour

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#379]
Seems sidebar area is not accesible by default when tour is triggered, because layout is not selected. Let's find a workaround how to fix that.
![image](https://cloud.githubusercontent.com/assets/1316234/26301890/32159fe2-3eeb-11e7-86e8-18a8b455a6c4.png)

**Comment by ivan-berezhnov** [comment]
@Sanchiz I think we can improve module openy_tour and add action select which click on a specific option in select.

**Comment by YMCA-GTC** [comment]
Added to Open Y trello roadmap

**Comment by paige-kiecker** [comment]
This enhancement is on our roadmap (https://trello.com/c/3MJhsjZX/101-sandbox-tour-enhancements-for-sidebar-content-score-8) closing here to reduce redundancy
