### ISSUE TITLE
Menu icons are lost in subfolder until cache is rebuilt

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#380]
Menu icons are not displayed when website is installed in subfolder because folder prefix is lost until cache is rebuilt.
![image](https://cloud.githubusercontent.com/assets/1316234/26302131/ec832b9c-3eeb-11e7-8e00-233f68ce02c7.png)

**Comment by anprok** [comment]
This issue is fixed for builds by updating cache rebuild drush command  https://github.com/ymcatwincities/openy-cibox-build/pull/4
For installed site this problem is not relevant so can be closed.
