### ISSUE TITLE
The theme implementations may not be rendered until all modules are loaded

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#388]
Please try to apply patch or update `simple_menu_icons` module if patch has bee commited.
drupal.org issue - https://www.drupal.org/node/2880544#comment-12098527

**Comment by YMCA-GTC** [comment]
@Sanchiz Can you please help me write a user story for this one so I can add it to the roadmap? Thanks!

**Comment by podarok** [comment]
@YMCA-GTC 
User story - 
Update simple_menu_icons module to version 8.x-2.0 to fix menu icons caching bugs

**Comment by YMCA-GTC** [comment]
Let's address this as part of the technical debt that we take on with each release. I'll change the type to bug.

**Comment by YMCA-GTC** [comment]
@podarok Can this be closed, or is it still a known bug?

**Comment by podarok** [comment]
@YMCA-GTC @Sanchiz we have this already in place https://github.com/ymcatwincities/openy/blob/8.x-2.x/composer.json#L133
