### ISSUE TITLE
Documentation: Hide paragraph from the list in content types 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#389]
We need to describe how to "correctly/better" alter list of paragraphs which should not be available in regions of content types. For example currently, there is a config file https://github.com/ymcatwincities/openy/blob/8.x-1.x/modules/openy_features/openy_prgf/config/install/openy_prgf.settings.yml which has a list of paragraphs which should not be available. 
And there is a `hook_form_alter` https://github.com/ymcatwincities/openy/blob/8.x-1.x/modules/openy_features/openy_prgf/openy_prgf.module#L13  where this config is using. 

As we discussed with @Sanchiz, we suggest creating a `hook_update_N` and update config. Using this approach during OpenY update there will be easy to find changes in configs via `openy_upgrade_tool`

**Comment by podarok** [comment]
Let me add my 2 kopecks
I guess as a distribution we should keep everything enabled by default for the sake of accessibility
But I agree we should add some sort of documentation - user and developer levels - to help instances to find out how to limit the number of paragraphs per reference field.

So I would start from creating tour to help site builders understand how to limit list
For the developers - it is fine to create README.md with steps, explaining how-to.

**Comment by podarok** [comment]
I guess having Standard, Extended, and Custom OpenY installation types we fixed this issue. There is no large list of paragraphs when you are using Standard. For the edge cases let's keep this decision to respective OpenY adopters with Extended and Custom
