### ISSUE TITLE
Edit text of the 403 and 404 pages

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#390]
We would like to have the ability manage text shown on the 404 and 403 pages. 
Currently, we have text in the templates `page--system--404` and `page--system--403` .
But I think it would be great to have the ability manage text from admin panel.

**Comment by alexschedrov** [comment]
@ddrozdik I think you can manage this from the content editing workflow.
1. Create two landing pages
2. Go to "/admin/config/system/site-information" and specify them as 404 and 403 pages
![image](https://cloud.githubusercontent.com/assets/1316234/26357157/1c4af26a-3fd7-11e7-8c58-25c5ace625a0.png)

**Comment by ivan-berezhnov** [comment]
I can do it when I finish assigned issues.
For me it interesting and I thought about it.
@ddrozdik @Sanchiz

**Comment by alexschedrov** [comment]
@ivan-berezhnov I don't think that this should be part of the OpenY out of the box. It's just default Drupal feature that may be used.

**Comment by ddrozdik** [comment]
Thanks, I will double-check why we did not use this approach, seems there were some issues.

**Comment by alexschedrov** [comment]
@ddrozdik there may be issues if you're using page manager as a page renderer. Andriy Maximov fixed this for Seattle, so reach out to him to check this.
