### ISSUE TITLE
Backport autologin module from YD

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#404]
@danylevskyi

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
@podarok Can you please help me draft a user story for this for the roadmap?

**Comment by podarok** [comment]
Added to roadmap

**Comment by podarok** [comment]
This module should be kept as disabled for security reasons.

**Comment by YMCA-GTC** [comment]
Agreed with @podarok on Jan 4, 2018

**Comment by podarok** [comment]
I don't think we need this now. This is mostly related to DevOps and hardly dependent from the in company culture. So I'm closing this for now.
