### ISSUE TITLE
Backport Houston paragraphs

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#406]

**Comment by podarok** [comment]
![image](https://cloud.githubusercontent.com/assets/563412/26555371/5e3321e6-449d-11e7-99c7-9d04fd34b37f.png)

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by podarok** [comment]
Source https://github.com/propeoplemd/ymcahouston/tree/master/docroot/modules/features/openy_prgf/modules
Destination https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/openy_features/openy_prgf/modules

**Comment by atiupa** [comment]
skip next prgfs, need to check latest version:
#openy_prgf_camp_menu
#openy_prgf_loc_finder
#openy_prgf_simple_content
#openy_prgf_small_banner

**Comment by podarok** [comment]
https://github.com/ymcatwincities/openy/pull/506

**Comment by YMCA-GTC** [comment]
@Sanchiz @podarok Did this get integrated recently, or is this still something on our to-do list? If it's on our to-do list, can one of you please help me write the user story for this?

**Comment by podarok** [comment]
Work in progress. 
Basically - we should get a full list of not yet ported Houston features and add them to the roadmap one per item with later prioritization.

**Comment by YMCA-GTC** [comment]
Given org changes and the hurricane last year it may be a few months before we get a list of not-yet-ported features from Houston to integrate into Open Y, unless anyone reading this can supply a list here.

**Comment by podarok** [comment]
@YMCA-GTC 
As per our agreement with Houston I have an access to their codebase so will do provide a full list. Added to my todo items

**Comment by YMCA-GTC** [comment]
@Sanchiz @ygerasimov If either of you end up helping Houston migrate at some point in the future, this would be a good place to start.

**Comment by paige-kiecker** [comment]
Given low demand and other priorities, this backport was never completed and the platform has since evolved beyond what these paragraph types offer
