### ISSUE TITLE
Backport Facebook Events sync + Event CT from Houston

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#407]

**Comment by podarok** [comment]
and from Dayton

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
Added to roadmap

**Comment by ddrozdik** [comment]
Open Y already has Events content type. Closing this issue. 
Please create a new issue if something is still missed.
