### ISSUE TITLE
Backport Testimonials CT from Houston

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#408]

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
Added to roadmap

**Comment by paige-kiecker** [comment]
This has been added to the roadmap (https://trello.com/c/JflkPrvj/54-testimonial-score-8) closing here until the project begins dev.
