### ISSUE TITLE
Backport Panoramas from Houston

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#409]

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
Added to roadmap

**Comment by paige-kiecker** [comment]
This is on the roadmap (https://trello.com/c/6CSTiiCj/53-panorama-score-8) closing out here until we begin to develop the enhancement.
