### ISSUE TITLE
Backport SVG formatter

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#410]
https://github.com/propeoplemd/ymcahouston/tree/master/docroot/modules/custom/openy_svg_formatter

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
@podarok Can you please help me write a user story for this so I can add it to the roadmap? The link above goes to a 404 for me.

**Comment by podarok** [comment]
This was done already https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/custom/openy_svg_formatter
Closing
