### ISSUE TITLE
Backport EMMA integration

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#411]
https://github.com/propeoplemd/ymcahouston/tree/master/docroot/modules/custom/emma_block

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
I'm not clear on what Emma is - we need more information on this to understand impact and add to the roadmap.

**Comment by podarok** [comment]
@YMCA-GTC https://myemma.com/
It is an email marketing platform

**Comment by YMCA-GTC** [comment]
@podarok Did this ever get backported?

**Comment by paige-kiecker** [comment]
This enhancement will be integrated within a larger email integration feature that is compatible with a variety of email platforms
