### ISSUE TITLE
Backport openy_tour

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#412]
https://github.com/propeoplemd/ymcahouston/tree/master/docroot/modules/custom/openy_tour

**Comment by ymcagtc** [comment]
URL above goes to 404

**Comment by podarok** [comment]
@ymcagtc fixed

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
@podarok Can you give me more info on why this is Critical please? Otherwise, can we change this to important if it's still needed? I'm cleaning up our backlog.

**Comment by podarok** [comment]
This is critical because without improved openy_tour makes no sense to use tours in OpenY

**Comment by podarok** [comment]
This is done
