### ISSUE TITLE
[Experimental Feature] News Content type

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#415]
We would like to see a new content type News as part of openY. This could be an optional module, which will be enabled only if a client wants to have News on their website. 
The module should provide next features:
- News content types, similar to Blog but without Style options. 
- Paragraph to list all news
- Paragraph to show the latest news
- Paragraph to show the latest news by a branch
- Paragraph to show the latest news by a camp
- Featured News
- News Taxonomy vocabulary
- Demo content

The module should have a label `experimental`.

**Comment by podarok** [comment]
YMCAs decided to use Blog for news. Having additional content type could be overengineering

**Comment by ddrozdik** [comment]
@podarok, @Sanchiz let's discuss, I want to hear your thoughts because YLI really wants to have it as a separate thing.
And as I mentioned in the description, this could be an optional module and disabled by default.

**Comment by ddrozdik** [comment]
All pull requests related to this issue should go to a repository **8.x-1.x-exp-news**

**Comment by dimb** [comment]
News content types, similar to Blog but without Style options - done
New Taxonomy vocabulary - done

**Comment by dimb** [comment]
News content types, similar to Blog but without Style options. - done
Paragraph to list all news - done 
Paragraph to show the latest news - done
Featured News - done
New Taxonomy vocabulary - done

**Comment by ddrozdik** [comment]
- **[fixed]** Paragraph "Latest news posts (branch)" - title should be changed, see screenshot https://monosnap.com/file/MEOdjN4dgutyfNgvu1qxJiQ1U1E8pl
- **[fixed]** Paragraph "Latest news posts (camp)" - title should be changed, see screenshot https://monosnap.com/file/PD6a23nm9Icp9ro6IcUsvPLQPeYUKo

**Comment by ddrozdik** [comment]
@YMCA-GTC this issue has not merged yet. It is in the separate branch, we want to complete it soon.

**Comment by ddrozdik** [comment]
news content type has been added as an experimental content type.
