### ISSUE TITLE
Location popup default value

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#419]
Whenever you see location popup - 1st branch is default option. Even when you're viewing all branches.

![image](https://cloud.githubusercontent.com/assets/1316234/26640963/ea5d8ba8-4631-11e7-82ee-405eaed9305a.png)

**Comment by YMCA-GTC** [comment]
Good catch - added to roadmap

**Comment by podarok** [comment]
Already fixed in last release http://sandbox.openymca.org/schedules
