### ISSUE TITLE
Backport google translation block from Dallas

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#424]
https://github.com/propeoplemd/yd/pull/113

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
In roadmap

**Comment by YMCA-GTC** [comment]
Launched in 1.11
