### ISSUE TITLE
Create Event Paragraph for addtocalendar feature for all site pages

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#427]
Add ability to create icon with Dropdown for addtocalendar service from YGTC site
![_999 235](https://cloud.githubusercontent.com/assets/563412/26688378/253b494e-46fb-11e7-9ca8-dd7904910d34.png)
This is requested by Houston.

Architecture
Create paragraph to the reusable block with list of fields needed for iCal format

**Comment by podarok** [comment]
![_999 236](https://cloud.githubusercontent.com/assets/563412/26688625/dab139a0-46fb-11e7-8741-2217be0bdc72.png)

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
We have this in the roadmap

**Comment by podarok** [comment]
This intended to be a WYSIWYG button

**Comment by podarok** [comment]
@YMCA-GTC @ymcagtc I think this is a backlog task for the future. Nobody requested this since Houston team mentioned as a wish on some call in the past. Low demand.

**Comment by sarah-halby** [comment]
Closing due to low demand and length of time passed since the original request. cc @danylevskyi
