### ISSUE TITLE
Backport + Refactoring YMCA Retention module from Twin Cities

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#428]
https://github.com/propeoplemd/ymca/tree/master/docroot/modules/custom/ymca_retention
Currently, module is not ready to just copy and use.

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
This is currently being worked on by @ygerasimov 's team, I believe.

**Comment by paige-kiecker** [comment]
This was resolved in https://github.com/ymcatwincities/openy/pull/1355. Closing the ticket.
