### ISSUE TITLE
Backport timeline from Houston instance

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#431]
https://github.com/propeoplemd/ymcahouston/pull/544

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
We have this in the Open Y roadmap. The severity is reduced to normal.

**Comment by paige-kiecker** [comment]
No demand for this feature.
