### ISSUE TITLE
Backport microsites menu component from YGH

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#435]
https://github.com/propeoplemd/ymcahouston/tree/master/docroot/modules/features/openy_prgf/modules/openy_prgf_microsites_menu

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
@podarok @Sanchiz Can this one be closed now?

**Comment by podarok** [comment]
Yes
