### ISSUE TITLE
How to make sprint work possible for closed source projects

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#437]
We have a bunch of tasks, created with ["Backport"](https://github.com/ymcatwincities/openy/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20Backport) in the title by FFW team and most of them lead to closed repositories.
For the ability to work on them for non-FFW guys we should follow the steps:
 * AGENCY guy should pull the code without any changes with saving attributions from closed project to OpenY as a PR
 * PM/TL to create a to-do list of tasks to be done for the created PR's branch (feature_$name branch)
 * Subtasks assigned to the non-AGENCY guys should be fixed as PRs to the feature_$name branch to be tested/approved
 * when all subtasks are fixed feature_$branch should be reviewed by OpenY team

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
@podarok @Sanchiz How do we make this a standard best practice?

**Comment by podarok** [comment]
@YMCA-GTC I've updated the description a little bit
This should land as a documentation. And we have to test this approach on one of the sprints.

**Comment by YMCA-GTC** [comment]
@podarok Makes sense to me, thank you!

**Comment by podarok** [comment]
Due to low activity in regards of external sprints I believe description and the title of the issue enough for now. We'll extend this once needed.
