### ISSUE TITLE
Backport generic migrations from Dallas to be reused as demo content for paragraphs

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#438]
Related https://github.com/ymcatwincities/openy/issues/406

![image](https://cloud.githubusercontent.com/assets/563412/26788454/e066f5de-4a15-11e7-918c-9124f45542cb.png)

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
@podarok Can you please help me write a user story for this one to be added to the roadmap?

**Comment by podarok** [comment]
added

**Comment by YMCA-GTC** [comment]
Closing this one as it was specific to a single proprietary CMS used by two Y associations that have already migrated to Open Y. In the future, we should look at a 'site migration' module to easily migrate content into Open Y from other CMS systems such as Word Press.

**Comment by podarok** [comment]
This was already implemented. I'm not sure we backported from Dallas, but we definitely leveraged an idea to have DEMO content in Open Y via Drupal core migrations
