### ISSUE TITLE
Backport SOLR search from YGH

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#439]

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
@podarok You have the severity on this set to Critical. Can you tell me more info on why this is critical, or can I change it to important?

**Comment by podarok** [comment]
Added critical by accident. This is important, but definitely not critical

**Comment by YMCA-GTC** [comment]
@podarok Sounds good - thank you - added to roadmap.

**Comment by podarok** [comment]
This was fixed in different manner - Activity FInder provides us SOLR integration out of the box
