### ISSUE TITLE
Error: Config core.entity_view_display.paragraph.membership_info.default does not exist.

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#441]
Add core.entity_view_display.paragraph.membership_info.default  config to openy_node_mbrshp:
https://github.com/ymcatwincities/openy/tree/8.x-1.x/modules/openy_features/openy_node/modules/openy_node_mbrshp/config/install

**Comment by podarok** [comment]
Membership part will be fully overhaul - I don't think we need to spend time for small fixes
