### ISSUE TITLE
Blog teaser Image - Rendered as node_program_subcategory_teaser

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#442]
In this case openy_node_blog dependence on node_program_subcategory module.

TODO: 
- [ ] create separate media view mode and image style for Blog teaser Image
- [ ] put new configs to openy_node_blog feature

**Comment by podarok** [comment]
@hamrant could you add a bit more business need to this change. Maintenance/Design wise - having same image style for different places makes a lot of sense. I don't think adding additional style improves somehow a flow.

**Comment by hamrant** [comment]
@podarok as far as I remember this related to decoupling, ideally, we can't have a dependency to program subcategory in blog feature. According to [installation_types](https://github.com/ymcatwincities/openy/blob/8.x-2.x/openy.installation_types.yml) programs and blog located in 'complete' type, therefore, it is not very critical, but if we want to enable blog without programs in 'standard' or 'extended' - this dependency won't let us do it.

Anyway looks like this was already fixed [here](https://github.com/ymcatwincities/openy/blob/8.x-2.x/modules/openy_features/openy_node/modules/openy_node_blog/config/install/core.entity_view_display.node.blog.teaser.yml#L48 ) - so we can close this issue.
