### ISSUE TITLE
[Backport] YLI - Add style button to wysiwyg editor 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#444]
The code for this should come from YMCA twin cities

*Additional requirements*

* Add inline member icon
* add inline calendar icon 

See image
https://api.monosnap.com/rpc/file/download?id=I93Q06a3IYtbKb4s7L0qdf882kabVu

https://www.ymcamn.org/about/volunteer

https://propeople-us.atlassian.net/browse/YLI-197

**Comment by ddrozdik** [comment]
@goranmiric Here is what we need:
1. Create a module openy_wysiwyg
2. Move configs to the module 
- https://github.com/ymcatwincities/openy/blob/8.x-1.x/config/install/editor.editor.full_html.yml
- https://github.com/ymcatwincities/openy/blob/8.x-1.x/config/install/filter.format.full_html.yml
3. Add module as a dependency to openY
4. Add hook_update_N to enable module
5. Update configs to add needed styles from YMCA twin cities
6. Add hook_update_N to apply a new config
7. Copy styles from YMCA twin cities and place them in the module.

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by ygerasimov** [comment]
Lets build this feature using CKEditor plugin http://ckeditor.com/addon/glyphicons. It allows to add icons (any icons from bootstrap) with ability to choose the color and size.

**Comment by podarok** [comment]
I'd suggest to build glyphicons as additional feature. Because it is not simple, but we need YLI approach landed asap @ygerasimov @ddrozdik

**Comment by ddrozdik** [comment]
@podarok there is a PR for Open Y https://github.com/ymcatwincities/openy/pull/464 but there is a problem with glyphicons:
@ddrozdik: We will not be able to use glyphicons as part of the open Y, there is a conflict with licenses: https://www.drupal.org/node/2889944#comment-12145655

> GLYPHICONS FREE license
are released under the Creative Commons Attribution 3.0 Unported (CC BY 3.0). The GLYPHICONS FREE can be used both commercially and for personal use, but you must always add a link to GLYPHICONS.com in a prominent place (e.g. the footer of a website), include the CC-BY license and the reference to GLYPHICONS.com on every page using icons.

But for your project you can safely reuse this PR https://github.com/propeoplemd/ymcali-openy/pull/185

**Comment by YMCA-GTC** [comment]
@ddrozdik @ygerasimov @podarok @Sanchiz Can I please get some help turning this into a user story for the roadmap? Thanks!

**Comment by podarok** [comment]
Hi, all
At this point we shouldn't use glyphicons packed into OpenY distribution because it creates a lot of complexity and licensing issues. 
Initial issue was created for adding style button, which already exists in YGTC codebase and also highly extended by adding bootstrap button https://www.drupal.org/project/ckeditor_bootstrap_buttons module in Dallas project.
So, the user story for OpenY should be


> as a content manager, I should be able to have WYSIWYG button with predefined button styles. Leverage https://www.drupal.org/project/ckeditor_bootstrap_buttons module with a fix from Dallas project.

**Comment by podarok** [comment]
Added to roadmap

**Comment by paige-kiecker** [comment]
Completed in 2019
