### ISSUE TITLE
Add views_block_filter_block to openy_prgf_classes_listing dependencies

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#448]
Please add views_block_filter_block to module dependencies in openy/modules/openy_features/openy_prgf/modules/openy_prgf_classes_listing/openy_prgf_classes_listing.info.yml
This module used in views.view.classes_listing.yml:
``` 
   display_options:
      display_extenders: {  }
      exposed_block: true
```

**Comment by yasik78** [comment]
Fix https://github.com/ymcatwincities/openy/pull/540/
