### ISSUE TITLE
[Backport] Incorrect spacing on locations page section titles

### ISSUE THREAD

**Issue by alexandar87** [ymcatwincities/openy#457]
Steps to reproduce:

- As a user i visit `/locations` page, by default all filters are off and first section title is YMCA
- Turn on Camps filters only, now only visible title is Camps, but its lower on the page than initially YMCA
- Turn off Camps and turn on Facilities, now Facilities title is even more lower on the page than Camps

![locations site-install 2017-06-07 12-16-14](https://user-images.githubusercontent.com/3238879/26873760-43d01b62-4b7b-11e7-8432-f24e07a7ec94.jpg)

The issue is with padding on element `views-element-container` as its wrapper and it has to be on child element.

I will make PR with solution as soon as i setup site on local.

**Comment by ddrozdik** [comment]
Backport fix from https://github.com/propeoplemd/ymcali-openy/pull/129

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/master/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by AlexNetman** [comment]
Fixed. And related css code refactored.
