### ISSUE TITLE
Backport openy_latest_news paragraph from Houston

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#459]
https://github.com/propeoplemd/ymcahouston/tree/master/docroot/modules/features/openy_latest_news

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
@podarok Can you please help me write a user story for this one to be added to the roadmap? The links above are 404 for me. Thanks!

**Comment by podarok** [comment]
This depends on ```SOLR Program Search Integration``` item in the roadmap. Added link there.
Also added as dedicated ```OpenY Latest News``` in case if we decide to break SOLR dependency

**Comment by ddrozdik** [comment]
Distro already has OpenY Latest News paragraph. I think since we do not have any movement on this issue we can close it. Right?
