### ISSUE TITLE
Write PHP sniffer rule to scan .yml files for wrong style

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#461]
In case if there is a ```description: ''``` within yml - ping developer with an error

**Comment by YMCA-GTC** [comment]
@podarok Can you please help me turn this into a user story for the roadmap if applicable? Further, is this critical, or should it be changed to important?

**Comment by podarok** [comment]
This issue is a big deal. I guess we need to postpone it and work on drupal.org with the community to bring best practices into some tool, like ```PHP Sniffer``` for scanning missed best practices. 
As you might recall we were doing a lot of issues for adding descriptions to fields in the past. Because usually, top-notch developers are too lazy to add descriptions which are - better UX.

I've removed Critical, because we can live without it, but in order to bring UX to OpenY - having default checkers on every build with showing missed parts in configs could be a great improvement.

**Comment by podarok** [comment]
No need to make this because we have builds. Once yml files are good - site is working. Once broken - site is not working. Having additional checkers is overkill which makes no sense
