### ISSUE TITLE
Change URL alias for classes

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#462]
Open Y build alias for classes based on the whole hierarchy `Program -> Program Subcategory -> Activity -> Class` but in this hierarchy content type `Activity` does not have own page. 
In result, we can have URL alias like this `http://openy-dev.ffwua.com/demo/programs/youth-programs/academic-success/academic-success/academic-success`

As you can see part of the URL `academic-success` present three times. 

Suggestions:
1. Remove Activity from the URL, because when use breadcrumbs it links to a closed page for an anonymous user. 
2. Change last part of the alias to something like `list` or `schedule` or `class-times`, etc. 

If apply these suggestions URL can look like `http://openy-dev.ffwua.com/demo/programs/youth-programs/academic-success/class-times`

**Comment by alexschedrov** [comment]
@ddrozdik good catch!

> Remove Activity from the URL, because when use breadcrumbs it links to a closed page for an anonymous user.

Totally agree.

> Change last part of the alias to something like `list` or `schedule` or `class-times`, etc.

I like `class-times` at the end of URL.

**Comment by ddrozdik** [comment]
We have tested the solution from PR on YMCA Long Island and found that we have to leave a class name in URL to avoid creating aliases like `/programs/youth-programs/academic-success/class-times-0`, `/programs/youth-programs/academic-success/class-times-1`, `...`.

based on our tests we can say that pattern should have a class name until we change the content hierarchy.
