### ISSUE TITLE
Composer didn't apply patches from OpenY

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#466]
When added OpenY as a dependencies to require section - no patches, described in https://github.com/ymcatwincities/openy/blob/8.x-1.x/composer.json#L134 extra section aren't applied

**Comment by atiupa** [comment]
```
"require-dev": {
  "ymcatwincities/openy": "dev-8.x-1.x"
},
```

**Comment by podarok** [comment]
This was fixed already. Bad composer config on our end
