### ISSUE TITLE
Create docs about how to add OpenY to existing project

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#467]
Starting point https://github.com/propeoplemd/ymca/pull/2368

**Comment by ddrozdik** [comment]
@podarok already started based on YLI experience

**Comment by alexschedrov** [comment]
Plugin that should allow to keep repositories for libraries on one place https://github.com/wikimedia/composer-merge-plugin.

**Comment by ddrozdik** [comment]
@Sanchiz I tried to use https://github.com/wikimedia/composer-merge-plugin, but it works only when you have different `composer.json` files in your project structure. It does not work with `composer.json` added as a requirement.

**Comment by YMCA-GTC** [comment]
@podarok @Sanchiz @ddrozdik Can someone please help me turn this into a user story for the roadmap if applicable?

**Comment by podarok** [comment]
I believe this is too early.
I'd like to get feedback from @atiupa about how it was done on YGTC
Also, I have a bit of information in my head
Basically - after making possible https://github.com/ymcatwincities/openy/issues/468 and https://github.com/ymcatwincities/openy/issues/567 the documentation will happen

**Comment by podarok** [comment]
Initial documentation
=====

If you have your Drupal 8 site with a bunch of custom and contrib modules down below please find initial steps you'd need to make to migrate from vanilla Drupal to OpenY distribution

- update your site - Drupal core to same version, used in OpenY, as well as respective contrib modules.
- Create inventory of custom modules and copy them into some folder like store/modules/custom for later usage
- Create inventory of contrib modules and copy them to store/modules/contrib
- Decide what to do with your theme/design. If you want to keep it - prepare resources for theming OpenY components to fit your design. There could be an option to make your design as a child of one of the themes you chosen from OpenY as a base. OpenY recommends to switch from your legacy design to one of the existing in OpenY to minimize migration effort and to leverage OpenY as much as you can
- proceed with OpenY installation using composer. ( this is needed only for generating settings.php )
- restore DB of your site from backup into DB, created during OpenY installation
- copy everything from store/modules into docroot/modules of freshly created OpenY
- enable openy_system module
- follow upgrade document from step https://github.com/ymcatwincities/openy/wiki/OpenY-upgrade-how-to-for-Developers#enable-openy-introduced-modules-in-case-if-you-are-updating-from-very-old-version-or-if-they-are-disabled-intentionally
- once upgraded, visit admin/openy to enable needed components from OpenY

@Sanchiz @ddrozdik @ygerasimov needs your review before putting into wiki

**Comment by alexschedrov** [comment]
@AndreyMaximov @hamrant @afi13 please review and provide your feedback on the suggested plan above ^^. You've updated many non-Open Y websites to the latest versions of Open Y.

**Comment by ddrozdik** [comment]
@podarok   you created many docs during the last year. Please review this issue which may be outdated already.

**Comment by sarah-halby** [comment]
@podarok let's review this item and see if we need to update it for the move to Drupal 9 or if this should be closed out as an outdated item.

**Comment by sarah-halby** [comment]
@ddrozdik we are closing this item based on current documentation and recommendations for migration as we are moving to Drupal 9.
