### ISSUE TITLE
Tests to test decoupling

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#468]
Let's generate approach how we can test decoupling.

**Comment by YMCA-GTC** [comment]
@podarok @Sanchiz Can I get some help creating a user story for this one? I'm trying to figure out how to best add it to the roadmap.

**Comment by podarok** [comment]
@YMCA-GTC 
As a OpenY core team developer, I want to be able to get protected by automated tests showing dependencies for all modules in OpenY build. This will help me to build decoupled features and make OpenY easy to be adopted

**Comment by sarah-halby** [comment]
@Sanchiz we are going to close this due to the change in approach to Open Y. If you have questions about this, let's connect via Slack. Instead of decoupling, we are creating products already decoupled.
