### ISSUE TITLE
Backport classes listing search from YGS version

### ISSUE THREAD

**Issue by hamrant** [ymcatwincities/openy#469]
Example on YGS https://www.seattleymca.org/programs/swimming/swim-lessons?location=16

Upgrade from 
![example1](https://user-images.githubusercontent.com/13733670/26937548-5880c3cc-4c7a-11e7-99f9-0e22e342fdf3.png)

TO

![example2](https://user-images.githubusercontent.com/13733670/26937554-5e73e872-4c7a-11e7-9519-68231c8a0846.png)

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by paige-kiecker** [comment]
This approach has been replaced by enhancements to Program Event Framework
