### ISSUE TITLE
Backport mass media_upload module from YGH

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#472]
We've fixed https://github.com/propeoplemd/ymcahouston/tree/master/docroot/modules/patched/media_upload with
patches
Let's have it for OpenY
Sometimes users need to bulk import assets without migrating content.

**Comment by podarok** [comment]
Use https://github.com/cibox/cibox/blob/decouple_script/core/cibox-project-builder/files/drupal8/scripts/decouple.yml to save log

**Comment by YMCA-GTC** [comment]
Added to roadmap

**Comment by paige-kiecker** [comment]
This modal has been abandoned by the platform, other media enhancements will be delivered in the February 2020 release
