### ISSUE TITLE
Blog CT hide fields in styles

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#492]
Currently, there are settings in the content type `Blog Post` which allow specifying how a card should look on the listing. 
Fields `Background color` and `Text color` should be displayed only when option `Color Card` is selected otherwise they should be hidden. 

Please use `#states` for this. 
![edit blog post start training now for the y run 7c site-install 2017-06-11 12-57-15](https://user-images.githubusercontent.com/6285570/27010096-96a7e86a-4ea5-11e7-9575-121d502e8ecd.png)

**Comment by vasilyyaremchuk** [comment]
It doesn't work due to incorrect hook name :-)

I'm going to fix it in the scope of bug 517

**Comment by ddrozdik** [comment]
this issue has been fixed already.
