### ISSUE TITLE
Handshake ico too close to title

### ISSUE THREAD

**Issue by alex-poletaev** [ymcatwincities/openy#505]
Media ~1017<. “Volunteers nedeed!” title.
Link: http://sandbox.openymca.org
![screenshot from 2017-06-11 13 48 46](https://user-images.githubusercontent.com/29352405/27010428-d1c1345e-4eac-11e7-9fa3-4fc0a453dcc8.png)

**Comment by SanyokMedved** [comment]
PR is here https://github.com/ymcatwincities/openy/pull/538
