### ISSUE TITLE
Fix description in the module openy_node_mbrshp

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#515]
There is a module `openy_node_mbrshp`. This module has an empty description in configuration files(7 files). 

We need to add a description. 

See for details 
https://github.com/ymcatwincities/openy/blob/8.x-1.x/modules/openy_features/openy_node/modules/openy_node_mbrshp/config/install/field.field.node.membership.field_mbrshp_info.yml#L15

and documentation 
https://github.com/ymcatwincities/openy/blob/8.x-1.x/docs/Content%20structure/Content%20Types/Membership.md

Steps to find the content type:
1. Open openY
2. Login as admin
3. Go to Administration -> Structure -> Content types -> Membership

**Comment by ddrozdik** [comment]
part of the fix - https://github.com/ymcatwincities/openy/pull/531

**Comment by hamrant** [comment]
Fix - #546
