### ISSUE TITLE
Blog CT - turn off the color options after blog style change.   

### ISSUE THREAD

**Issue by idsem** [ymcatwincities/openy#517]
**Actual behavior.** 

Steps to reproduce: 

1. Go for Blogpost node editing page (example /node/11/edit)
2. Pick the Style type "Color card" (https://monosnap.com/file/FIVsytzHEW9juhItORFNcOJVAdoMtk)
3.  Save the changes. 
4. Change Style type to any other from the list and hit save. (But don't change the color options)
5. Color options values will be available for any other Style type  

**Expected behavior**

After step 4, Color options values should not be available for all the Style types expect "Color card"

**Comment by vasilyyaremchuk** [comment]
https://github.com/ymcatwincities/openy/pull/549
