### ISSUE TITLE
Improve Image Embed within WYSIWYG with resize functionality.

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#561]
Houston team is not happy with impossibility to have resize for the media images, embedded to WYSIWYG.
At this moment we have opportunity to add view modes to images, like Half or Full, but it is not possible to resize embedded image to the size, required by Content Manager.
Let's investigate this and create an approach to resize images in place without overloading content managers with additional work to resize images before uploading them.

**Comment by YMCA-GTC** [comment]
Unfortunately this is not actually a bug, but a very good enhancement request. It is in the roadmap. I am also changing the severity from Critical to Important as the work-around is to resize the image in an image editor prior to uploading. I agree this is important, but not critical given other priorities. I, too, would like us to have this feature.

**Comment by paige-kiecker** [comment]
This will be resolved with https://github.com/ymcatwincities/openy/issues/1706 so closing this ticket
