### ISSUE TITLE
Hybrid Docker SQL + profile flow

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#567]
Andriy Podanenko
[11:38] 
not experimental if
- there is a tour for user
- dependencies are not tough and checked on clean drupal install
- some behat tests
- theming decoupled into the module

Andriy Podanenko
[11:56] 
Introduce modules
- openy_stable - > empty module for adding dependencie to not experimental OpenY modules
- openy_contribs -> all dependencies to contribs live here
- openy_experimental -> all in progress OpenY modules

For Docker SQL flow
image should contain SQL dump with profile + openy_stable and openy_contribs enabled
openy_experimental enabled on PR builder to test on builds (edited)

**Comment by YMCA-GTC** [comment]
@podarok Can you please help me draft a user story for this to add to the roadmap? Thank you!

**Comment by podarok** [comment]
This is mostly the CI approach for https://github.com/ymcatwincities/openy/issues/468 issue
I believe it is in progress by @Sanchiz, but we need to regroup to understand the effort to be done.

**Comment by podarok** [comment]
Oh. This is CIBox issue
No need to keep it here.
