### ISSUE TITLE
Join page

### ISSUE THREAD

**Issue by goranmiric** [ymcatwincities/openy#570]
If you are on the `/join` page and you select something and click `Next` then `Prev` and then `Next` you get infinite js errors related to `maps.googleapis.com`.
![screen shot 2017-06-15 at 10 06 53](https://user-images.githubusercontent.com/1763492/27180373-7bc07e46-51d3-11e7-89b4-ace0738e67b6.png)

**Comment by YMCA-GTC** [comment]
Unable to reproduce
