### ISSUE TITLE
Backport global_nav paragraph from YD

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#573]
https://github.com/propeoplemd/yd/pull/143

ATM it is not yet themed, but the idea is that when ```global_nav``` added to header field (rename field name during backporting, because YGH is not OpenY) - block global_navigation, which is placed by layout_plugin, skipped from rendering.

**Comment by YMCA-GTC** [comment]
@podarok Can you help me write a user story for this one so I can add it to the roadmap? I'm not sure I understand exactly what is happening and how this will benefit a user. Thanks!

**Comment by podarok** [comment]
Added to roadmap

**Comment by paige-kiecker** [comment]
Introduced alternative sub-menu in 2018 that solves for this
