### ISSUE TITLE
Add Class, Program Subcategory to sitemap

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#582]
Please add Class CT and Program Subcategory CT to sitemap.

**Comment by ivan-berezhnov** [comment]
@Sanchiz This issue fixed in PR https://github.com/ymcatwincities/openy/pull/589
Probably we should close it, what do you think?

**Comment by YMCA-GTC** [comment]
@Sanchiz Can we close this per @ivan-berezhnov 's comment above?
