### ISSUE TITLE
[Backport] YLI - FAQ paragraph

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#588]
Backport FAQ paragraph from YLI - https://github.com/propeoplemd/ymcali-openy/pull/138

https://propeople-us.atlassian.net/browse/YLI-237

**Comment by YMCA-GTC** [comment]
@ddrozdik  Can we get more details on this please? I can't access the links above. Depending on the details, I can add it to the roadmap.

**Comment by ddrozdik** [comment]
@YMCA-GTC and @podarok, FAQ paragraph looks so:
![faq-frontend](https://user-images.githubusercontent.com/6285570/31933177-0f7fc828-b8b1-11e7-9cc7-73951229f869.png)

And on the backend 
![faq-backend](https://user-images.githubusercontent.com/6285570/31933224-336b71ce-b8b1-11e7-88ca-246c45af70ff.png)

**Comment by podarok** [comment]
@ddrozdik could you add my account as read-only to ymcali github repo?
I'd like to see the code to get more precise roadmap ranking

**Comment by ddrozdik** [comment]
@podarok I've sent you an invite.

**Comment by podarok** [comment]
Component looks pretty simple to be added to OpenY
See https://trello.com/c/g3SsyK4t/96-faq-component-from-ymcali-score-9 in roadmap
@YMCA-GTC

**Comment by YMCA-GTC** [comment]
Thanks guys - it's in the roadmap!

**Comment by podarok** [comment]
WiP https://github.com/ymcatwincities/openy/pull/1202

**Comment by podarok** [comment]
done https://github.com/ymcatwincities/openy/pull/1202#pullrequestreview-144803465
