### ISSUE TITLE
Include error while indexing solr

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#593]
```include_once(/mnt/www/html/yhouston/docroot/modules/custom/openy_webform/modules/contrib/webform/includes/webform.theme.inc):  [warning]\nfailed to open stream: No such file or directory ThemeManager.php:263```

**Comment by YMCA-GTC** [comment]
@podarok Can you please help me understand the severity of this issue? What happens after the error occurs, and how does it impact the experience for an end user?

**Comment by podarok** [comment]
As you can see - this is Houston related issues where SOLR searching service is used. 
So this bug should be fixed whether by Houston team prior to backporting openy_webform module to OpenY or after Solr search backported to OpenY - recheck if it still exists

**Comment by podarok** [comment]
Closing this for now
