### ISSUE TITLE
Allow logo to be updated in admin interface

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#594]
When I updated footer logo in theme setting
Also alt text is saying YMCA when I hover over.
![image](https://user-images.githubusercontent.com/4558228/27377823-c093ed14-567e-11e7-838c-55a9c26cc927.png)

Let's put alt text as "Site-logo" by default. To make it more universal and clear in accessibility terms.

**Comment by ivan-berezhnov** [comment]
@AlexNetman We have some functionality for change logo in the header and footer.
Please look: https://monosnap.com/file/Qa77Vk52nPDntZvNBX0YxBZ5TDKX0b

Steps to change logo in the header:
- [ ] go to [sitename]/admin/appearance/settings/openy_rose
- [ ] find section "LOGO IMAGE"
- [ ] uncheck "Use the logo supplied by the theme"
Please look https://monosnap.com/file/qaNjsOn1buMRRRu5pAj0kyDCAgHBha
- [ ] for you will be apper "Upload logo image"
- [ ] select your image and save settings 
- [ ] go to front page and verify logo in the header changed

**Comment by AlexNetman** [comment]
@ivan-berezhnov  OK. So we need only to update alt text for footer logo.
