### ISSUE TITLE
Backport video player paragraph from YD

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#595]
https://github.com/propeoplemd/yd/pull/156

**Comment by YMCA-GTC** [comment]
@podarok Can we get more details on this please? The above is a 404. Depending on the details, I can add it to the roadmap.

**Comment by podarok** [comment]
Added ```Local video assets player component``` to roadmap

**Comment by ddrozdik** [comment]
The original idea is good, but I suggest to avoid creating new paragraphs and instead follow the way we do for images and links to videos. Currently, a content editor can add an image or video using the icon in the WYSIWYG and we do not have independent paragraphs for these things. 
I believe it would be better to add an icon to WYSIWYG that will work in the same way like images and links to videos, so the content editor could use the same approach. 
Using the paragraph Simple Content + icon in WYSIWYG will do the same thing as the independent paragraph for local videos.

@podarok we already discussed this, just confirm that you agree with this approach.

**Comment by podarok** [comment]
Confirmed. Let's avoid an additional paragraph in this case. A self-video hosting feature is mostly for backward compatibility in terms of Y, not widely requested. So the more consistent it is, the less confusion and complexity we are creating for end users

**Comment by AlexNetman** [comment]
Video Paragraph was ported. And modified into WYSIWYG button.
![image](https://user-images.githubusercontent.com/4558228/36205823-214c25da-11a1-11e8-9245-e27e237e64a3.png)
