### ISSUE TITLE
Backport Reusable simple content component from YD

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#597]
https://github.com/propeoplemd/yd/pull/121/files

**Comment by YMCA-GTC** [comment]
@podarok Can we get more details on this please? The above is a 404. Depending on the details, I can add it to the roadmap.

**Comment by podarok** [comment]
It is already in the roadmap. Linked there

**Comment by paige-kiecker** [comment]
Reusable content now exists for multiple paragraph types
