### ISSUE TITLE
Daxko: hide default paragraph fields

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#599]
Please hide following fields:
- Program registration block
- Block description
- Title
- Display title

![image](https://user-images.githubusercontent.com/1316234/27427585-31242a52-5748-11e7-90d7-c1beef61e6eb.png)

**Comment by YMCA-GTC** [comment]
In roadmap - thanks!

**Comment by paige-kiecker** [comment]
This is on the roadmap. Closing out here until development begins https://trello.com/c/RnVvm3Zk/62-daxko-integration-hide-unused-page-elements-when-editing-content-programs-that-are-coming-in-dynamically-from-the-daxko-api-scor
