### ISSUE TITLE
Backport Expander from YD

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#603]
https://github.com/propeoplemd/yd/pull/55

**Comment by YMCA-GTC** [comment]
@podarok Can we get more details on this, please? The above returns a 404 for me.

**Comment by podarok** [comment]
This is in progress on me. During backporting, we are going to change theming architecture for OpenY - from theme based to component based

**Comment by paige-kiecker** [comment]
@podarok look into backport of YGTC version

**Comment by sarah-halby** [comment]
@paige-kiecker we will close this ticket as a Y can use the FAQ functionality to achieve the same result.
