### ISSUE TITLE
Close access to view Taxonomy term page

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#634]
We need to close access to view taxonomy term pages for vocabularies:
- Area
- Color
- Facility Type
- Media Tags

Example of the page http://sandbox.openymca.org/taxonomy/term/2

**Comment by AlexNetman** [comment]
@ddrozdik  
Let's find some more details on requirements here.
If we just close the access to terms that will lead to some problems:
1) Go to http://ci.openymca.org/build1846/locations  and click on name of Facility.
For example: BELLEVUE .
You will get 404 page at http://ci.openymca.org/build1846/area/bellevue
2) On homepage click on Category name in Blog teaser.
