### ISSUE TITLE
Errors while saving a new alert

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#635]
```
User error: "target_id" is an invalid render array key in Drupal\Core\Render\Element::children() (line 97 of core/lib/Drupal/Core/Render/Element.php).
User error: "_loaded" is an invalid render array key in Drupal\Core\Render\Element::children() (line 97 of core/lib/Drupal/Core/Render/Element.php).
User error: "_accessCacheability" is an invalid render array key in Drupal\Core\Render\Element::children() (line 97 of core/lib/Drupal/Core/Render/Element.php).
```
![openy distribution site-install 2017-06-29 20-55-01](https://user-images.githubusercontent.com/6285570/27702602-441122a8-5d0d-11e7-85e1-c0b09f4ae90d.png)

Steps to reproduce:
1. create a new alert
2. Specify in the field `Reference` reference to an internal page
3. Save

**Comment by YMCA-GTC** [comment]
Upgrading the severity to Critical on this.

**Comment by podarok** [comment]
Just checked on today's sandbox and looks like all good, see no issues with saving or editing alert
Could you be more specific in which page should be referenced, @ddrozdik ?
![_999 235](https://user-images.githubusercontent.com/563412/30550356-e17a4c64-9c9f-11e7-91fb-ca6854445fe9.png)

**Comment by podarok** [comment]
Please reopen if this is still an issue
