### ISSUE TITLE
Hero Area component

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#636]
![_999 088](https://user-images.githubusercontent.com/563412/27732689-1cbc255c-5d9b-11e7-83d4-30ddbb6f75ec.png)

We need to have Hero Image component which will serve extended behaviour
- keep working hours as a field (we need it for teasers as well)
- Add component to be added to header area only with fields: hero image, hero link
- when Component is placed to page - design overrides standard output of working hours field and Contact info field and gather them to design attached above

**Comment by YMCA-GTC** [comment]
Added to roadmap

**Comment by ivan-berezhnov** [comment]
Hi, @podarok could you please clarify next:
the component should be for a specific content type with fields contact info field and etc...
or the component like a reference to the same node?

**Comment by podarok** [comment]
@ivan-berezhnov the way it was developed for Dallas - if I recall it right, - this is a component(custom paragraph) which displays fields from Content Type in a specific region, where the component was added.

**Comment by podarok** [comment]
There were no requests for demand of this feature.
Closing for now. Let's open once Dallas team decided to decouple and backport it into OpenY or when demand increased
