### ISSUE TITLE
UX improvement. Collapsible paragraphs

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#640]
Current, when on Landing Page I have multiple paragraphs added it is very hard to reorder them. Suggestion is to make them collapsible, so I could see the summary (type of the block). Then I would be able to reorder / delete them effectively.

Here is how it is done on distribution of boston.gov (it is drupal 7 but uses paragraphs as well).
![boston-collapsed-paragraphs](https://user-images.githubusercontent.com/294265/27755094-80ad17b8-5da2-11e7-8e93-6091bdd75f06.png)

**Comment by YMCA-GTC** [comment]
@podarok @Sanchiz Did this get added to the distro already, or is it just something we have discussed backporting from Dallas or Houston? If it needs backporting I will add it to the roadmap.

**Comment by podarok** [comment]
No, this is not yet in the roadmap.

**Comment by podarok** [comment]
Added user story there

**Comment by YMCA-GTC** [comment]
Added to roadmap thus closing this issue
