### ISSUE TITLE
Membership CT Link field

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#650]
When I am editing Link field on Membership content type I can't see what is affected?

Where is this field used?

![openy-membership-link](https://user-images.githubusercontent.com/294265/27838739-5cf05824-60a1-11e7-8b37-46508dd7f97b.png)

**Comment by alexschedrov** [comment]
@ygerasimov this link is displayed at the end of Membership form and depends on the selected membership type and branch.

In most cases this link leads to 3rd party CRM(e.g. ActiveNet, Daxko etc). Would be great if we can add description to this field.

![image](https://user-images.githubusercontent.com/1316234/27854290-efd99970-616e-11e7-939e-35d5ef546fc4.png)
