### ISSUE TITLE
Branch. Directions link

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#651]
There is a field Directions on Branch form. But I can't figure out where we display it. Please advise.

![openy-branch-directions](https://user-images.githubusercontent.com/294265/27839205-68dd8f82-60a4-11e7-81c5-ad24e5d96660.png)

**Comment by alexschedrov** [comment]
It suppose to be displayed in 2 places.

**Branch teaser**
![image](https://user-images.githubusercontent.com/1316234/27854375-46d0cde8-616f-11e7-9ad2-fc43c880a4a5.png)

**Branch info**
Seems this link is missed from branch info block, should be fixed. Added separate issue to fix this #655.
![image](https://user-images.githubusercontent.com/1316234/27854855-ff450910-6170-11e7-93f5-aca6f0694c00.png)
