### ISSUE TITLE
Camp. Fax, Direction link

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#652]
Please advise where Fax number and Direction Link is displayed on Camp page?

http://sandbox.openymca.org/camps/camp-colman has these fields populated. But these are not displayed.

![openy-camp-fax](https://user-images.githubusercontent.com/294265/27839944-fae846ec-60a9-11e7-9098-f8bbad51088c.png)

**Comment by alexschedrov** [comment]
For directions link - https://github.com/ymcatwincities/openy/issues/651#issuecomment-313030634.

**Comment by alexschedrov** [comment]
For fax added issue - #656.
