### ISSUE TITLE
Facility. How to use?

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy#654]
There is a content type Facility. That as I understand should display all the facilities in the branch.

http://sandbox.openymca.org/facility/magnuson-park

What is the best way to put links to it? Do we just build some content block with listing of all facilities of the branch?

Please provide couple of examples.

**Comment by alexschedrov** [comment]
Currently facilities are displayed on following pages:

**Location finder** - http://sandbox.openymca.org/locations
![image](https://user-images.githubusercontent.com/1316234/27855062-bafbb1d6-6171-11e7-8f28-929f9eb21d13.png)

**Facility page** - http://sandbox.openymca.org/facility/fauntleroy-ymca


I think you're right. We need new component that will display all facilities that are associated with the branch. Currently we don't have this component.
