### ISSUE TITLE
Directions link on branch and camp pages

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#655]
Please make sure, when Directions link is specified, it's display on branch page in branch info header.
![image](https://user-images.githubusercontent.com/1316234/27854824-dd264f4c-6170-11e7-93c7-3fd7f424f1f0.png)
![image](https://user-images.githubusercontent.com/1316234/27854863-052adc06-6171-11e7-8f1e-296796d85e48.png)

**Comment by ivan-berezhnov** [comment]
PR https://github.com/ymcatwincities/openy/pull/670

**Comment by ivan-berezhnov** [comment]
Fixed in the PR #670

**Comment by alexschedrov** [comment]
Upgrade path is not working.
![image](https://user-images.githubusercontent.com/1316234/28614558-ea777876-71fe-11e7-9dca-9ddf48a6c277.png)

**Comment by alexschedrov** [comment]
Plus make sure it is displayed on facility page - #717.
