### ISSUE TITLE
Fax on branch and camp pages

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#656]
Please make sure that we display fax number when it's specified below phone.

![image](https://user-images.githubusercontent.com/1316234/27855002-812f90a8-6171-11e7-9426-bc16c50685b3.png)

**Comment by ivan-berezhnov** [comment]
PR https://github.com/ymcatwincities/openy/pull/670

**Comment by ivan-berezhnov** [comment]
Fixed in the PR #670

**Comment by alexschedrov** [comment]
Upgrade path is not working.
![image](https://user-images.githubusercontent.com/1316234/28614565-f346b782-71fe-11e7-8288-4f20f75552b4.png)
