### ISSUE TITLE
openy_upgrade_tool does not show information correctly. 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#675]
After updating openY to the latest version using `openy_upgrade_tool` dashboard I can see a list of conflicts. For example, I have a conflict with the config `views.view.classes_listing`. And I see that conflict with property `display.search_form.cache_metadata.tags` but when I open diff I can see that there are much more conflicts in different places. So using service `openy_upgrade_tool.param_updater` I can't resolve conflicts, I have to specify a property for each place where I have a conflict or import the whole config. 

I guess we should not display a value in the `UPDATE PROPERTY` column on the page at all, or display it for each changed property in a config.

**Comment by podarok** [comment]
@hamrant could you please ensure this bug is not exists in your update tool, decoupled to drupal.org?

@ddrozdik is it possible to share more details about 
- post configs from active and file storage to compare on a sandbox environment

**Comment by YMCA-GTC** [comment]
@ddrozdik @Sanchiz @podarok Hey friends, could we please get an update on this? It feels like this should get resolved sooner rather than later. Thanks!

**Comment by podarok** [comment]
OpenY Upgrade tool is inapropriate at this moment
See https://github.com/ymcatwincities/openy/pull/1084 , team
Let's go from there

**Comment by YMCA-GTC** [comment]
@podarok and 5J are working on this one for a near-term bug-fix release.

**Comment by hamrant** [comment]
Field `config_property` from ` openy_config_upgrade_logs` used for storing last updated property during OpenY update, it's not related to any conflict and only provides information what exactly should have been updated.

Anyway in new openy_upgrade_tool version this field will be removed, so this issue can be closed.

cc @podarok @ddrozdik
