### ISSUE TITLE
openy_upgrade_tool Allow to resolve conflicts via UI

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#676]
I would like to have an option to resolve conflicts with configs using UI. Currently, there is no way to do this.

**Comment by YMCA-GTC** [comment]
Agreed - this would be nice. I have added it to the roadmap.

**Comment by podarok** [comment]
This is done
![image](https://user-images.githubusercontent.com/563412/54908507-bbb79900-4ef0-11e9-97e2-3b5d0d0be51c.png)
