### ISSUE TITLE
openy_upgrade_tool Skip some changes

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#677]
The module should skip configs if there the only change inside is a `uuid` or `_core` property. 

![openy upgrade dashboard 7c ymca of long island f0 9f 94 8a 2017-07-10 14-51-28](https://user-images.githubusercontent.com/6285570/28016936-4eafb5a6-657f-11e7-8689-4f41861d3860.png)
`

**Comment by podarok** [comment]
@hamrant any input from your end?

**Comment by hamrant** [comment]
@podarok this issue can be closed. `uuid` and `_core` params now ignored by upgrade tool.

**Comment by podarok** [comment]
Thanks
