### ISSUE TITLE
Warning while saving session node

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#678]
> Notice: Undefined offset: 0 in Drupal\openy_session_instance\SessionInstanceManager::loadSessionSchedule() (line 292 of profiles/contrib/openy/modules/custom/openy_session_instance/src/SessionInstanceManager.php).

Appears when I save a new node type of session.

Steps to reproduce:
1. create a new session
2. add session time
3. add the second fieldset for the session time and leave it empty
4. save

**Comment by paige-kiecker** [comment]
This has been resolved
