### ISSUE TITLE
Update from OpenY 8.1.2 to OpenY 8.1.3 is failed due to content_moderation

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#686]
stderr: Drupal\Core\Entity\EntityStorageException: Exception thrown while    [error]
performing a schema update. SQLSTATE[42000]: Syntax error or access
violation: 1071 Specified key was too long; max key length is 767
bytes: ALTER TABLE {content_moderation_state_field_data} ADD UNIQUE
KEY `content_moderation_state__lookup` (`content_entity_type_id`,
`content_entity_id`, `content_entity_revision_id`, `workflow`,
`langcode`); Array() in Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException()
(line 1485 of
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
Failed: Drupal\Core\Entity\EntityStorageException: !message in       [error]
Drupal\Core\Entity\Sql\SqlContentEntityStorage-&gt;wrapSchemaException()
(line 1485 of
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

This is happening because we did not use the patch provided by the community - https://www.drupal.org/node/2846618

**Comment by podarok** [comment]
@ddrozdik As far as I remember you managed to fix this issue. Please confirm we can close it
