### ISSUE TITLE
OpenY 8.1.3: Module openy_programs_search requires Symfony component

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#687]
After update to OpenY 8.1.3 I see that there is a new module added `openy_programs_search`. This module fails because symfony component is absent:
`
Fatal error: Class 'Symfony\Component\DomCrawler\Crawler' not found in /var/www/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 264
`

After investigating, I did not find that this component was added.

**Comment by YMCA-GTC** [comment]
@ddrozdik @Sanchiz @podarok Can I get some help setting the severity on this one? I don't understand the customer impact, or if it's a blocker on a site install/upgrade. Thanks!

**Comment by podarok** [comment]
@ddrozdik I believe you had to run ```composer update``` to get all newly added vendors downloaded before using any module from a new OpenY release. Could you please confirm the issue exists or already fixed?

**Comment by ddrozdik** [comment]
@podarok I had done `composer update` and then could see that issue. But as far as I know, that issue has been fixed already. I will check one more time in a couple of weeks when I will be doing next update.

**Comment by podarok** [comment]
@ddrozdik thanks for the update
Looking forward to getting from you this is not anymore a bug

**Comment by alexschedrov** [comment]
I was able to reproduce this error.
`symfony/dom-crawler` is not being installed when we install the distro without development dependencies, e.g. `--no-dev` option for composer command.

This library blocks overall installation, because it's required for demo content step.

**Comment by YMCA-GTC** [comment]
Assigning to IXM for resolution

**Comment by podarok** [comment]
Fixed in dev
