### ISSUE TITLE
Notice in the module openy_schedules

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#689]
`
Notice: Undefined index: tags in Drupal\openy_schedules\Form\SchedulesSearchForm->buildResults() (line 869 of profiles/contrib/openy/modules/custom/openy_schedules/src/Form/SchedulesSearchForm.php).
`

**Comment by ivan-berezhnov** [comment]
@ddrozdik Could you please explain how to it reproduce.

**Comment by YMCA-GTC** [comment]
Closing as we never heard an update on this
