### ISSUE TITLE
Use "Link text" as a title for "Directions" link on camps/branches

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#690]
If create a camp/branch and specify a link in the field `Directions`, for example, a link to an internal page 
![edit camp camp orkila 7c site-install 2017-07-11 19-58-32](https://user-images.githubusercontent.com/6285570/28080103-67d56e8c-6673-11e7-9961-10522c9c8e06.png)
then on the Locations(`/locations`) page, you will see this url in the block
![locations 7c site-install 2017-07-11 23-09-33](https://user-images.githubusercontent.com/6285570/28088368-1fcb0d66-668e-11e7-971d-e3d2f06f96dd.png)

I suggest using `Link text` to allow modify text instead of hard coded text `Directions`.
Example like we did this for YLI: https://github.com/propeoplemd/ymcali-openy/pull/207/files#diff-3cc7f2f18ff447c809589a75d05f2f63R492

**Comment by rotator** [comment]
It looks like it was fixed already.
Facilities [https://monosnap.com/file/pWUbUOlNxxhe7yKhbcTbI3AY496eUR](https://monosnap.com/file/pWUbUOlNxxhe7yKhbcTbI3AY496eUR)
Camp [https://monosnap.com/file/hAUkp4KMdjT8ZKgqnWIt5fnAFOCjq9](https://monosnap.com/file/hAUkp4KMdjT8ZKgqnWIt5fnAFOCjq9)
Branch [https://monosnap.com/file/cIOsVqYB0zfbOtWSOBxHxd55KFe9Xd](https://monosnap.com/file/cIOsVqYB0zfbOtWSOBxHxd55KFe9Xd)
@podarok please, close it.
