### ISSUE TITLE
OpenY installation is failing in case of unavailability of any library. 

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#696]
12:24:38 Unable to download panelbutton from                                  [error]
12:24:38 http://download.ckeditor.com/panelbutton/releases/panelbutton_4.7.0.zip.
12:24:38 Unable to download colorbutton from                                  [error]
12:24:38 http://download.ckeditor.com/colorbutton/releases/colorbutton_4.7.0.zip.

this happened due to maintenance on http://ckeditor.com/
![down for maintenance 2017-07-15 16-57-03](https://user-images.githubusercontent.com/6285570/28239879-af81864a-697e-11e7-8240-3580506a04f0.png)

**Comment by YMCA-GTC** [comment]
@ddrozdik @Sanchiz @podarok What's the level of effort on this one, and is there anything we can really do about it beyond a more friendly error message, if these are libraries that are required?

**Comment by podarok** [comment]
I don't think we can do anything in regards to keep our external dependencies up and running
Making mirror is an option, but there could be licensing issues.
I'd like to close this issue.
Feel free to reopen it in case if external dependencies are unstable. We may discuss to drop their support or to replace with more stable ones
