### ISSUE TITLE
Fatal error on edit field_prgf_block field.

### ISSUE THREAD

**Issue by dimb** [ymcatwincities/openy#698]
Fatal error on edit field_prgf_block field.
Error message says:  "_TypeError: Argument 2 passed to Drupal\groupex_form_cache\GroupexFormCacheManager::setCache() must be of the type array, null given, called in /var/www/docroot/profiles/contrib/openy/modules/custom/openy_group_schedules/src/GroupexRequestTrait.php on line 94 in Drupal\groupex_form_cache\GroupexFormCacheManager->setCache()_."

Steps to reproduce: 
1. go to /admin/reports/fields 
2. find field_prgf_block
3. go to any entity that uses this field
4. click on Edit button.

**Comment by ddrozdik** [comment]
fixed here https://github.com/ymcatwincities/openy/pull/700
