### ISSUE TITLE
Move demo authentication details to separate module

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#716]
We should move credentials, authentication details for 3rd party services to separate module.

Example: https://github.com/ymcatwincities/openy/pull/668/files#diff-21dae246523ef3a57efc15d2751bf649R9

**Comment by YMCA-GTC** [comment]
Good idea - added this to the roadmap.

**Comment by paige-kiecker** [comment]
This is on the roadmap (https://trello.com/c/4fzmVb7Z/64-move-sandbox-demo-credentials-to-a-3rd-party-service-rather-than-manually-changing-the-password-frequently-score-9) closing here until the project begins development
