### ISSUE TITLE
Bootstrap glyphicons fonts not found.

### ISSUE THREAD

**Issue by artemdotsenko** [ymcatwincities/openy#718]
https://github.com/ymcatwincities/openy/blob/8.x-1.x/themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap.css#L313

bootstrap.css has wrong path to glyphicons font files, which makes impossible to use it with open_rose theme.

**Comment by YMCA-GTC** [comment]
Updated severity and level
