### ISSUE TITLE
[Backport YLI] Location Filter settings form

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#719]
We added a form in the admin panel which allows specifying what branches and what camps should be displayed in filters and popups. This could be useful in case client wants to hide some of them. 
See for details:  https://github.com/propeoplemd/ymcali-openy/pull/266

**Comment by paige-kiecker** [comment]
We will revive this ticket for the May 2020 release

**Comment by sarah-halby** [comment]
@AndreyMaximov @paige-kiecker this is complete & works in Drupal 8 & Drupal 9 per discussion with @podarok today.
