### ISSUE TITLE
Filter Sub-Program does not work

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#722]
http://sandbox.openymca.org/schedules
Try to filter by different options, if using filter `Sub-Program` you can see that nothing changes on the page.

**Comment by alexschedrov** [comment]
![screen shot 2017-07-28 at 11 33 03 am](https://user-images.githubusercontent.com/1316234/28709332-8c3b88b6-7388-11e7-9125-07d7d452422f.png)
