### ISSUE TITLE
[Backport YLI] Paragraph Featured Highlights

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#726]
For YMCA Long Island we developed a new paragraph `Featured Highlights`.

The paragraph provides next fields:
- Title of the paragraph
- Style "Select list with following values: 2:2 items per row, 3:3 items per row, 4:4 items per row"
- Ability to add custom block or select existing(like in the paragraph Microsites menu from Houston)
- Each block has next fields:
-- Link and link text
-- Image
-- Description 

https://github.com/propeoplemd/ymcali-openy/tree/master/docroot/modules/custom/ymcali_features/ymcali_prgf_featured_highlights

**Comment by YMCA-GTC** [comment]
This has been added to the roadmap.

**Comment by paige-kiecker** [comment]
This task was completed and is available in OY core distro
