### ISSUE TITLE
Better widget for long select lists

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#729]
We've faced with issue when there is a long list in select widget and it is not that convenient to work with
Consider to add Select2 or competitor to the OpenY to get better UX

**Comment by alexschedrov** [comment]
Let's add choosen module - https://github.com/propeoplemd/ymcaseattle/pull/281/files.

**Comment by YMCA-GTC** [comment]
@Sanchiz @podarok this has now been added to the roadmap.

**Comment by YMCA-GTC** [comment]
Closing as this has been added to the roadmap
