### ISSUE TITLE
Revisions are not working

### ISSUE THREAD

**Issue by fandm** [ymcatwincities/openy#739]
Try to open some node's revision in view mode. You will get the error message:

> The website encountered an unexpected error. Please try again later.

In the log you will see the message:
`Error: Call to a member function getType() on string in Drupal\openy_popups\Plugin\Block\LocationPopupLink->build() (line 115 of /var/www/sandbox/profiles/contrib/openy/modules/custom/openy_popups/src/Plugin/Block/LocationPopupLink.php)...`
To fix this issue and other issues with access to the node attribute on the revision pages you need to apply this [patch](https://www.drupal.org/files/issues/2730631-13.patch) from this [issue](https://www.drupal.org/node/2730631).

**Comment by AlexNetman** [comment]
Fixed.
