### ISSUE TITLE
add image to the image editot screen in the cms so a user can see the image they have uploaded.

### ISSUE THREAD

**Issue by Robert201-zz** [ymcatwincities/openy#752]
add image to the image editot screen in the cms so a user can see the image they have uploaded. See screen shot for details.
![gfcrggc](https://user-images.githubusercontent.com/25036221/29403912-941c20a0-8331-11e7-8bf0-cf4438396dce.png)

**Comment by alexschedrov** [comment]
Fixed in #770.

**Comment by AlexNetman** [comment]
**Comment with Minor staff that we are not going to fix this time:**
Thumbnail on blog node is not aligned on the right as displayed in ticket description.
![image](https://user-images.githubusercontent.com/4558228/32595165-d0496704-c53f-11e7-8e83-dd29279902e2.png)
But that's making consistent behavior with other fields. And save spacing. For example in Slideshow paragraph when multiple images uploaded:
![image](https://user-images.githubusercontent.com/4558228/32595262-4760c9ae-c540-11e7-8fa3-fd98602adf19.png)

Also we have no preview for Menu items 
![image](https://user-images.githubusercontent.com/4558228/32596517-9a2b8e72-c544-11e7-92f3-36267520ea15.png)

And for amenity 
![image](https://user-images.githubusercontent.com/4558228/32596423-4ee87b1e-c544-11e7-8cd0-c956771b1ae0.png)
But they are SVG and would required custom formatter that we don't have. So probably we can left those as is

**Comment by AlexNetman** [comment]
*Nice to fix* this "Simple Block" which is only one that has no thumbnail 
![image](https://user-images.githubusercontent.com/4558228/32596025-f67801bc-c542-11e7-9050-50948a502bd1.png)
