### ISSUE TITLE
Groupex Schedules: View by Trainer:  Unexpected result for substitutes

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#757]
URL: http://ci.openymca.org/demo/schedules/group-schedules?location=204

![image](https://user-images.githubusercontent.com/4558228/29427137-9931b1c6-8391-11e7-8c31-d668a0cb518a.png)
Given I have substitutes trainer for some class
When I click on that trainer name
Then I see only class were Lucy is main trainer
But not where it work as substitute

![image](https://user-images.githubusercontent.com/4558228/29427222-ddfb81c4-8391-11e7-9a21-f84b18bc6c61.png)

**Comment by YMCA-GTC** [comment]
Reducing severity as we are overhauling the entire schedules experience in Q3 and Q4 2018 and this issue may be resolved at that time.

**Comment by paige-kiecker** [comment]
This was resolved in new version of the schedules experience.
