### ISSUE TITLE
[Backport YLI] Fix for images inserted via text editor in a half mode

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#760]
We fixed issue with stretched images here 
https://github.com/propeoplemd/ymcali-openy/pull/326/files

**Comment by YMCA-GTC** [comment]
@ddrozdik Is this issue still valid?

**Comment by ddrozdik** [comment]
@YMCA-GTC I will check, as far as I remember it is still valid.

**Comment by YMCA-GTC** [comment]
Assigned to IXM to resolve

**Comment by podarok** [comment]
Looks like this not anymore issue or was already backported
![image](https://user-images.githubusercontent.com/563412/65253331-209c2680-db03-11e9-873a-08537581baec.png)
