### ISSUE TITLE
[Backport YLI] Add a template for a media page

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#761]
By default, Media page does not have a template and everything looks broken. 
We added a template for our theme, but idea could be used the same as we did here https://github.com/propeoplemd/ymcali-openy/pull/327/files

**Comment by YMCA-GTC** [comment]
@ddrozdik URL above gives me a 404. Can you provide more information and I'll add this to the roadmap?

**Comment by ddrozdik** [comment]
@YMCA-GTC this issue is related to https://github.com/ymcatwincities/openy/issues/762 , and I see that PR for that issue already has needed template. Let's close this issue.
