### ISSUE TITLE
Configure Default View mode for Media bundles Video and Document

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#762]
For video: 
- hide everything and display the only name and rendered video, see example:
![newsday performing arts camp 2015 great south bay ymca 7c ymca of long island f0 9f 94 8a 2017-08-24 14-29-48](https://user-images.githubusercontent.com/6285570/29664563-bd61ebbe-88d8-11e7-935d-bb2d69baafc5.png)

For Document:
- hide everything and display the only name, mime type, and embedded document.

**Comment by YMCA-GTC** [comment]
This is now added to the roadmap

**Comment by alexschedrov** [comment]
Merged in #788.
