### ISSUE TITLE
Social Sharing icons no longer showing on blog posts

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#790]
The social sharing icons (Facebook, etc) no longer display on blog posts.

Reproduction steps:
1) Sign in to http://sandbox.openymca.org as admin
2) Create blog post
3) Click "Social Share" icons
4) Ensure the checkbox under Social Share icons is checked
5) Save the blog
6) View the blog and note that the social sharing icons do not appear

See: https://ibb.co/kWBwwv and https://ibb.co/d5MPia

**Comment by Robert201-zz** [comment]
![pasted image at 2017_09_12 08_49 am](https://user-images.githubusercontent.com/25036221/30327906-a455c22a-97c5-11e7-95d0-d3b5412ffcd4.png)
  just tested this and had no issue will it be possible to test again

**Comment by Robert201-zz** [comment]
http://sandbox.openymca.org/blog/test

**Comment by YMCA-GTC** [comment]
Re-tested, issue persists on Chrome Version 61.0.3163.79 (Official Build) (64-bit) Windows 10

The icons do appear in Firefox and some other browsers, however.

**Comment by YMCA-GTC** [comment]
This issue is likely related to ad-block extensions which prevent these buttons from appearing.  More info here: https://www.addthis.com/blog/2013/04/09/honey-i-lost-the-buttons/

Longer term we will want to transition to a self-hosted social sharing component to avoid this and other related issues. For now, this will be closed and archived for anyone else experiencing the issue.
