### ISSUE TITLE
Blog Category Pages are not rendering properly

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#791]
Steps to reproduce:

1. - Go to http://sandbox.openymca.org/
2. - Scroll down to blog posts
3. - Click on the Category Name, such as "Community Outreach"
4. - Note that the blog category page such as http://sandbox.openymca.org/blog/category/community-outreach is not rendering properly.

![screen shot 2017-09-17 at 4 25 36 pm](https://user-images.githubusercontent.com/17653329/30525065-e2bdd478-9bc4-11e7-97ce-cb57a0ec6c2a.png)

**Comment by podarok** [comment]
Confirmed. This is an issues with theming of taxonomy term page. Looks like some sort of regression. Probably missed template or something similar

**Comment by AlexNetman** [comment]
Not reproduced anymore. May be was fixed with something else.
