### ISSUE TITLE
Make OpenY working on Simplytest.me

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#793]

**Comment by podarok** [comment]
Still there
![image](https://user-images.githubusercontent.com/563412/34561927-c7f0a324-f154-11e7-9fa7-3d712e466821.png)

**Comment by YMCA-GTC** [comment]
Assigned to IXM for resolution

**Comment by anpolimus** [comment]
@podarok that is common problems for all latest profiles that are compiling using composer.
There are some issue at d.org that needs to be fixed first.

**Comment by anpolimus** [comment]
I've reviewed issue queue of simpletest.me and want to notice that last year its development is very low.
Efforts for fixing this issue could be higher alternative variants.
As possible variant, we could use another services for online build.

**Comment by podarok** [comment]
Yup, we use CIBox for getting builds

**Comment by anpolimus** [comment]
In this case, we have to update homepage of project at d.org and show link for created build at cibox instance.

**Comment by paige-kiecker** [comment]
@podarok is this enhancement outdated? can we close?

**Comment by podarok** [comment]
We can close. This is known issue for the environment and not only openy impacted...
