### ISSUE TITLE
Landing Page Template: wrong classes in attributes.

### ISSUE THREAD

**Issue by artemdotsenko** [ymcatwincities/openy#796]
In `node--landing-page--full.html.twig` file in header area to attributes added `header_classes`
`<div{{ attributes.addClass(header_classes) }}>` [#L91](https://github.com/ymcatwincities/openy/blob/8.x-1.x/themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig#L91)
next in content area to attributes in addition to `header_classes` added `content_classes`
`<div{{ attributes.addClass(content_classes) }}>` [#L110](https://github.com/ymcatwincities/openy/blob/8.x-1.x/themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig#L110)
and in sidebar area added `sidebar_classes`
`<aside{{ attributes.addClass(sidebar_classes) }}>` [#L124](https://github.com/ymcatwincities/openy/blob/8.x-1.x/themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig#L124)

In a result content area has header + content classes, sidebar area has header + content + sidebar classes. Same issue might be present in other template files.
![extra_classes](https://user-images.githubusercontent.com/4688363/30693706-c33bf9cc-9e9e-11e7-9313-2c394fc89af3.png)

**Comment by YMCA-GTC** [comment]
@Sanchiz @podarok Can I please get help determining the severity of this?

**Comment by podarok** [comment]
@artemdotsenko 
Good catch
Basically, we shouldn't merge classes walking from the top to the bottom of template
We should use https://www.drupal.org/node/2818293 create_attribute for every section of template to be merged with respective header_classes, content_classes, and sidebar_classes 

Severity is pretty high, not critical though

**Comment by YMCA-GTC** [comment]
In progress for next release per IXM

**Comment by paige-kiecker** [comment]
Resolved in https://github.com/ymcatwincities/openy/pull/1062. Closing this out.
