### ISSUE TITLE
Demo Content throwing error during Installation

### ISSUE THREAD

**Issue by jwtechdesign** [ymcatwincities/openy#798]
When installing the distribution using Composer, everything seems to be working great right up to the demo content installation script.  The install script stops and throws the following error:

> AJAX HTTP error occurred. 
> HTTP Result Code: 200
> Debugging information follows.
> Path: /core/install.php?rewrite=ok&profile=openy&langcode=en&continue=1&id=2&op=do_nojs&op=do
> StatusText: OK
> ResponseText: Error: Class 'Symfony\Component\DomCrawler\Crawler' not found in Drupal\Component\DependencyInjection\Container->createService() (line 264 of ~/sites/winonaymca/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php)`

The result is a 404 on the home page of the newly installed site, most likely because the landing page is not created.  Let me know if I need to manually configure anything in Symfony prior to running the install.

**Comment by jwtechdesign** [comment]
I believe I found a solution that may work for other devs that may run into this during installation... I had a feeling it may be due to out of date dependencies in Composer.  Just navigate to the root folder of the project where "composer.json" is found and run:

`composer update` to all dependencies to latest versions, or `composer outdated` if you want to see what may have updates.  This also assumes you have composer installed globally.

Seemed to do the trick for me - fully loaded demo content and the theme is populated correctly with that content.

**Comment by YMCA-GTC** [comment]
@Sanchiz FYI ^^^

**Comment by podarok** [comment]
This is more like Docs. Closing for now
