### ISSUE TITLE
Join page: Issues in special cases

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#813]
**Scenario 1:** Empty Destination URL
Given I Create a membership type and haven't specified URL destanation
When I go to /join
And I select that membership type 
And click Next
And I try to select that location which not have destination URL (West YMCA)
And click "Next"
Then I am not redirected to the next step 
And Ajax error appear in console
But I should be able to go the the final step and see the Membership type
And "complete registration" button should navigate to homepage

**Scenario 2**: Section without Location in membership type
Given I have added some empty section into some membership type (Example: Couple)
And I go to select membership type (Couple)
Then no links on second step are working even if they have Location and redirect Url specified
And Ajax error appear in console

**Comment by AlexNetman** [comment]
We have faced similar issue on YGH
when some membership type has come from API with no location one of the section
and whole membership type has stopped working.

**Comment by YMCA-GTC** [comment]
Increasing the severity to ensure this one is resolved and closed

**Comment by YMCA-GTC** [comment]
In progress for next release per IXM

**Comment by paige-kiecker** [comment]
Resolved in https://github.com/ymcatwincities/openy/pull/1061. Closing this out
