### ISSUE TITLE
Feature Request: Daxko API configurable limit argument.

### ISSUE THREAD

**Issue by artemdotsenko** [ymcatwincities/openy#829]
All Daxko requests can have limit argument (e.g. https://dev.daxko.com/docs#Association@Association Branches). By default this value is equal to 100 and currently there is no way to change it other than to patch module from the platform. After facing with issue then limit=100 is not enough, proposing to make this argument configurable. Globally for all kinds of Daxko calls or per each call.

E.g. how it was fixed in my case:
![daxko_call_limit](https://user-images.githubusercontent.com/4688363/31987081-a799d4dc-b938-11e7-96d9-cd7b5d8a7730.png)

**Comment by paige-kiecker** [comment]
This has been resolved; limit set to 10,000.
