### ISSUE TITLE
Open Media Document tries to import not existing video configs.

### ISSUE THREAD

**Issue by artemdotsenko** [ymcatwincities/openy#831]
https://github.com/ymcatwincities/openy/blob/8.1.5/modules/openy_features/openy_media/modules/openy_media_document/openy_media_document.install#L96

`openy_media_document_update_8003` looking for file `core.entity_view_display.media.video.default.yml` inside it's own config/install folder, where this file doesn't exists.

![file_not_exist](https://user-images.githubusercontent.com/4688363/32047508-23a6d170-ba14-11e7-95d7-2e00852da816.png)

P.S. Brace on a new line https://github.com/ymcatwincities/openy/blob/8.1.5/modules/openy_features/openy_media/modules/openy_media_document/openy_media_document.install#L93

**Comment by Sanchiz** [comment]
There was open PR to fix this error https://github.com/ymcatwincities/openy/pull/578, but it was never finished.
