### ISSUE TITLE
Breadcrumbs component

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#846]
https://www.drupal.org/project/easy_breadcrumb module is a great tool to generate bradcrumbs.

We should intall and configure it. In addition each CT should have an ability show/hide breadcrumbs if necessary. We can leverage same approach as we are using for Social Share Icons.

1. Install and configure module
2. Create Paragraph that will render breaadcrumbs
3. Each CT should have global settings whether they should render breadcrumbs or not
![image](https://user-images.githubusercontent.com/1316234/32550037-47f2b8c0-c494-11e7-90db-8e56118200f6.png)

**Comment by ddrozdik** [comment]
**Note:** 
Using easy_breadcrumb there is an issue with breadcrumbs on the `Class Times` page. For example URL to the `Class Times` page looks so: 
`/programs/health-fitness/weight-loss/lose-weight-feel-great/class-times`
where the part `/lose-weight-feel-great/`is activity which does not have own page. 
This part should be removed from breadcrumbs on the `Class Times` pages.

**Comment by anprok** [comment]
I don't think we need to add that checkbox with settings to toggle breadcrumbs render when using breadcrumbs paragraph. Just remove breadcrumbs paragraph to disable breadcrumbs on appropriate page

**Comment by anprok** [comment]
PR merged. Issue can be closed
