### ISSUE TITLE
Image is not visible in WYSIWYG

### ISSUE THREAD

**Issue by fandm** [ymcatwincities/openy#857]
1. Open any node with Content field.
2. Add image. The image is not visible in WYSIWYG.
![1wusl](https://user-images.githubusercontent.com/4036323/32773416-c97dac14-c931-11e7-9d73-fa80fb77a5d9.png)

**Comment by artemdotsenko** [comment]
Quick temporary solution/workaround to change view mode from Blazy to Image for image media "Full" and "Half" view modes.

**Comment by fandm** [comment]
@artemdotsenko Yes, that's true. But in this case you will not have Blazy functionality for the image for which you applied the view mode Image instead Blazy in the node view mode. If it's ok, sure you can use this temporary solution.
