### ISSUE TITLE
Dropdowns are having Double arrows in Firefox

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#865]
All Examples are in FIREFOX

Example URL: http://ci.openymca.org/demo/schedules?location=3
![image](https://user-images.githubusercontent.com/4558228/33075726-8161cd0c-cedb-11e7-8bc2-005b5d14bfb1.png)

Example of working fine dropdowns:   /blog
![image](https://user-images.githubusercontent.com/4558228/33075944-3513ea9c-cedc-11e7-83a5-b6d5ca246910.png)

Other pages has different styles for dropdowns. But those issues are minor and can be fixed with lower priority:
/locations
![image](https://user-images.githubusercontent.com/4558228/33075992-616eb270-cedc-11e7-9f5f-93db4a977bf0.png)

Groups schedules:  schedules/group-schedules?location=204
![image](https://user-images.githubusercontent.com/4558228/33076209-2806f532-cedd-11e7-8ad4-f80cc717fdd4.png)

**Comment by ivan-berezhnov** [comment]
@AlexNetman  I checked on my laptop and with browserstack 
All show correct. 

![dashboard 2017-11-25 08-08-24](https://user-images.githubusercontent.com/10132087/33227978-660fd9ba-d1b8-11e7-94af-4ab9f107d8db.png)

**Comment by podarok** [comment]
![image](https://user-images.githubusercontent.com/563412/36584460-6db7d4b8-1882-11e8-9b04-377570a27d13.png)
