### ISSUE TITLE
Alert set cookie issue

### ISSUE THREAD

**Issue by Fant0m771** [ymcatwincities/openy#881]
Alert set cookie issue for site path like /program/{some-alias}, /program/test/{some-alias}, cookies works relative for page arguments. If cookie has been set on page like {site}/program/{path-alias} it will not work for path like {site}/{path-alias}. Need specify 'path' in cookies set functionality to '/' . 
To avoid multiple cookies like - https://monosnap.com/file/ZrxtRC1eNF2L8dVCusyjS4UtSX2mo7#

**Comment by ddrozdik** [comment]
this issue has been fixed.
