### ISSUE TITLE
[Backport YLI] Migrate openy_lily theme to open Y

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#889]
YMCA of Long Island developed a new theme openy_lily that should be backported to Open Y as an independent theme.

**Comment by YMCA-GTC** [comment]
@ddrozdik Should we close this one out, or are you waiting till we're out of Beta with Lily? Thanks!

**Comment by ddrozdik** [comment]
I think we can close this. All related issues with the theme should be addressed separately.

**Comment by YMCA-GTC** [comment]
Awesome! Thank you @ddrozdik !!
