### ISSUE TITLE
Make outline solid on Windows Chrome

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#897]
Outline is hardly visible in some places when using Windows Chrome
Please *make outline solid in Chrome*  (or may be dotted will be asked by Accessibility testing team)
![image](https://user-images.githubusercontent.com/1316234/33821296-ff345422-de5b-11e7-9ebc-3051add9d85d.png)

Other browsers are seem to be fine:
MacOS Chrome has those borders solid enough already.
Firefox has them solid.
IE 11 has dotted black&white outline that has good contrast too.
![image](https://user-images.githubusercontent.com/1316234/33821300-058e6952-de5c-11e7-9adf-4911f0c46f1b.png)

**Comment by podarok** [comment]
You are perfection nazi, my friend )))) @Sanchiz

**Comment by paige-kiecker** [comment]
@AndreyMaximov @Sanchiz is this still an active issue? We know you did some work enhancing these types of styling in 2019

**Comment by alexschedrov** [comment]
hi @paige-kiecker! I do not think that the issue is relevant anymore.

**Comment by paige-kiecker** [comment]
Okay, I will close it out then thanks!
