### ISSUE TITLE
Groupex Schedules: "Add to calendar" icon-link is not announced

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#898]
Example URL: http://ci.openymca.org/demo/schedules/group-schedules?location=202

Given I have VoiceOver enabled
When I follow to the icon 
Screen reader just say "Link"
But should say "Add to calendar, Link"

Anyway I click on that link  -  nothing happening
I can't hear or get into that popup with options

![image](https://user-images.githubusercontent.com/1316234/33821368-3b77f0b0-de5c-11e7-98fd-37d1fca351dc.png)

If we can't make this link working for screen readers - let's set it as Aria-hidden.  (So that will not appear for screen-readers at all)

**Comment by YMCA-GTC** [comment]
Nice find, Alex! I'm actually going to change the type from Enhancement to bug.

**Comment by kolesnikoff** [comment]
Hi @Sanchiz,

I tried to reproduce this issue on the latest code base using ChromeVox plugin and the link was announced as expected: [https://youtu.be/1Dqvxgacs40](https://youtu.be/1Dqvxgacs40).

What screen reader do you use?

**Comment by AlexNetman** [comment]
I have rechecked - now link is announced well.
But I am not able to select items there.
When I press Сtrl+Option+Space  then Calendar file is not downloaded, and I'm not redirected to service
![image](https://user-images.githubusercontent.com/4558228/36546252-00e2342c-17fc-11e8-8560-3ce9aef3273b.png)

**Comment by taras-tsiuper** [comment]
@podarok 
Just have checked if this is still reproducible. Google Calendar link redirects me to Calendar page with new event. So works well for me. Here is video
http://monosnap.com/file/gthwAV9kLCt6R0jabVL0ssP8pOeJf5

**Comment by paige-kiecker** [comment]
@podarok please review if this is still an open item

**Comment by sarah-halby** [comment]
@paige-kiecker confirming that this is still an open item as an accessibility issue.

**Comment by podarok** [comment]
THis one is fixed, will be tagged in upcoming point release
