### ISSUE TITLE
Upgrade path bettween 2 or more versions

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#899]
In order to prevent probme during updates between more than 2 versions(e.g. from 1.1 to 1.5), we need to setup additional environment, that will perform updates from 1.0 to current master.

In case if update on this environment has been failed, we have to fix it.

**Comment by YMCA-GTC** [comment]
Agree - added to roadmap

**Comment by podarok** [comment]
I guess latest version of upgrading OpenY for developers includes all generic needed steps https://github.com/ymcatwincities/openy/wiki/OpenY-upgrade-how-to-for-Developers#upgrade-to-open-y-2x-version
There is a document how to upgrade from 0.2 to 1.14 and then to decent OpenY 2.0
Closing the ticket. Open if you want to continue working on it as an improvement.
