### ISSUE TITLE
Sandbox rebuilding friendly message

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#900]
When http://sandbox.openymca.org is in the process of rebuilding, would be great to display friendly message that site will be up and running soon.

We can place `index.html` in the sandbox folder and remove it once build is finished.

**Comment by YMCA-GTC** [comment]
Agree. Added to roadmap.

**Comment by podarok** [comment]
Well
We just need to change the way sandbox is created - build should happen in background and when it is ready - replace the current one. So this is 100% availability approach instead of showing boring "Under construction"

**Comment by YMCA-GTC** [comment]
Assigned to @podarok

**Comment by paige-kiecker** [comment]
Sandbox rebuild has been optimized to sub 10 sec rebuild time. Closing out.
