### ISSUE TITLE
Code sniffers on builds

### ISSUE THREAD

**Issue by alexschedrov** [ymcatwincities/openy#901]
It seems that code sniffers are no longer works on CI builds. We need to research and fix the issue.

**Comment by YMCA-GTC** [comment]
Assigned to IXM for resolution

**Comment by paige-kiecker** [comment]
@podarok @Sanchiz is this still an issue?

**Comment by alexschedrov** [comment]
@paige-kiecker As far as I see the sniffers are disabled now.

Would be great if overall CI experience will be enhanced to show Green indicator when PR is successful. Right now all PRs, event those which were merged have Red indicator (e.g. something went wrong).

![image](https://user-images.githubusercontent.com/1316234/60956604-d41aba80-a30b-11e9-90ac-c03fbd8a294a.png)

**Comment by ddrozdik** [comment]
@podarok We would like to bring this topic up and discuss how we can help with adding code sniffer to Open Y builds. Our team noticed some PRs are creating with small issues that could be found by code sniffer.

**Comment by podarok** [comment]
@ddrozdik we are rebuilding CI, so let's return to this topic in Q3 2020
Thank you

**Comment by sarah-halby** [comment]
Confirming that this is still an issue - pushing out this discussion topic due to ongoing global pandemic and the prioritization of other priorities - pushing out to Q1 2021 @ddrozdik

**Comment by podarok** [comment]
This is fixed now
