### ISSUE TITLE
Unpublished content is still visible to users

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#913]
We created a new three Program -> Program Subcategories -> Activities -> Classes -> Sessions

Some of the Program Subcategories and Classes we unpublished, but they are still visible on the site for everyone.

**Comment by david-hernandez** [comment]
This looks to be an issue with the VERF module not the view itself. It does not do any kind of access check, which seems to be a known issue, and has not been fixed. The module seems to be abandoned. We'll need to probably patch it.

**Comment by david-hernandez** [comment]
In the previous comment I'm specifically talking about the category still appearing in the exposed filter of the program search.

**Comment by AlexNetman** [comment]
Now unpublished nodes are not present in the list of filters. But as we discussed we need to adjust process of changing node status, to unpublish all nodes(program subcategories/activities/classes/sessions) associated with the unpublished parent.

**Comment by YMCA-GTC** [comment]
In progress for next release per IXM

**Comment by SanyokMedved** [comment]
Works as expected. 
For example - I unpublished 1 node - activity - Weight Loss (node/121). In this case other nodes were unpublished too. 
- session - Swim Lessons - Youth Stage 5: Stroke Devel. (node/217)
- class - Lose to Win - Weight Loss Program (node/189)
- class - Lose to Win for Men - Weight Loss Program (node/188)

On the activity page I can't see unpublished nodes. 

Please test again.

**Comment by kolesnikoff** [comment]
@ddrozdik could you confirm that the issue is reproducible still?

**Comment by ddrozdik** [comment]
@kolesnikoff looks good now. I close this issue.
