### ISSUE TITLE
Support fonts with licences

### ISSUE THREAD

**Issue by ddrozdik** [ymcatwincities/openy#918]
Currently, Open Y has a form to upload Cachet font in the only one format ttf, using the admin interface. But for a better support of all possible browsers, it's recommended to upload other formats as well. 

Also, we faced a problem that Open Y Lily theme requires a set of Cachet fonts, that should be added outside of the theme to avoid hacking theme. Currently, there is no way to do this. 

I suggest installing a module https://www.drupal.org/project/fontyourface that will help handle this.

**Comment by YMCA-GTC** [comment]
Good points - I'm adding this to the roadmap.

**Comment by rotator** [comment]
This module supports custom fonts only in WOFF format. You can use online converter to transform your font (for example https://transfonter.org/). 
1. Navigate to Appearance -> font-your-face -> Custom Fonts  /admin/appearance/font/local_font_config_entity
2. Add needed custom fonts (Cachet Medium, Cachet Bold, Cachet Book) and enable it.
@podarok Please, review.

**Comment by podarok** [comment]
@rotator see my comment there

**Comment by kolesnikoff** [comment]
@podarok the requested functionality is deployed. Can we close the issue?
