### ISSUE TITLE
Adjust font sizes and refactor related styles

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#931]
1) Theme code Refactoring: remove usage of `px` and replace with `%` 

base font for paragraphs should be specified in `pt` not in `px`. Because `pt` is resulting into inches. While `px` in pixels. So `pt` should be showing more correct on range of devices.
Second that - other element (titles, menu items)  would better have font size in  `em` or in `%`

2) Need to find base font size with maximum readability. Example: browser default font size is 12pt. But we are having some paragraphs with font 9pt.
Note: Cachet font is looking smaller then default OpenY Verdana.
So once you upload Cachet - some elements becoming less readable.

**Comment by podarok** [comment]
@AlexNetman which best practices you are following by suggesting these changes?
I'd like to rely on some technology standards here

**Comment by paige-kiecker** [comment]
@AlexNetman we will be adding the ability to change font size in the WYSIWYG editor, which I believe will address your request. Closing this one. You can follow the progress on https://github.com/ymcatwincities/openy/issues/1707
