### ISSUE TITLE
Apply core patch for performance

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#934]
When there is a number of content blocks in database any Drupal 8 site performance is affected because of core bug
Backport https://github.com/propeoplemd/ymca/commit/ee49d732befa3369e2558b96a8e7a3e7bcfd9ff1 from YGTC site at a time when drupal.org issue created

**Comment by YMCA-GTC** [comment]
@podarok Can we get an update on this one, please? It's marked as Critical so I'd like to make sure it's resolved if it hasn't been already. Thanks!

**Comment by podarok** [comment]
This one is fixed by OpenY 2.0 core 8.6+
