### ISSUE TITLE
Unable to 'close' or 'dismiss' the top alert site banner

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#947]
Steps to reproduce: Open Y v1.7

Edge or Chrome - Win 10

1. Go to http://sandbox.openymca.org
2. See the top yellow banner that says Open Y distribution.
3. Click on the "X" to close the banner - note it does NOT close
4. Scroll down to the bottom alert banner in light blue - click on the "X" to close this banner - note that the bottom banner DOES close. 

Thus this is something specific to the top alert banner.

**Comment by AlexNetman** [comment]
That was fixed in https://github.com/ymcatwincities/openy/pull/940

Fix will be included into nearest release.
