### ISSUE TITLE
Unknown errors preventing page save

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#948]
There are some usual content errors that are blocking page save.
Need to adjust system to prevent those errors:

1) Landing page: Make field "Layout" set to One Column by default.
![image](https://user-images.githubusercontent.com/4558228/35975256-21fa56e0-0ced-11e8-8425-926b8ffed2b6.png)

2) Node add blog :  Make field "Locations" not required.
![image](https://user-images.githubusercontent.com/4558228/35975236-0e7a75c8-0ced-11e8-9b1d-3b6d4824815c.png)

2) Update demo content for Latest Blog post paragraphs. To contain title.
Example /node/1
![image](https://user-images.githubusercontent.com/4558228/35976147-3afc4538-0cf0-11e8-92ad-cdccb33b62e2.png)

**Comment by kolesnikoff** [comment]
@ddrozdik an issue with a missed title for the Latest Blog posts is fixed into #972.
But should I fix issues 1 and 2? Seems like everything works as expected.

**Comment by AlexNetman** [comment]
@kolesnikoff  I guess you meant that 1,2 are related to demo content?
No, they are for new pages when user creates them.
1) /node/add/landing_page    - make life easier and set a default value
2) /node/add/blog_post     - assiciation with location should not be required

**Comment by YMCA-GTC** [comment]
Changing from enhancement to bug to ensure this gets addressed

**Comment by YMCA-GTC** [comment]
Assigned to IXM for resolution

**Comment by paige-kiecker** [comment]
Resolved via https://github.com/ymcatwincities/openy/pull/972. Closing here.
