### ISSUE TITLE
Image in Banner is cut in unexpected manner

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#950]
Image is cut in unexpected manner. 

![image](https://user-images.githubusercontent.com/4558228/36375973-7da1652c-1582-11e8-9e45-dfc304bfa187.png)

**Suggestions:** Probably we would better make height of text area fixed. And restrict number of chars in banner title and description.
Another issue is that now image is resized to wide desktop while text block stay with fixed width. Let's make reverse logic - image always to have fixed proportions and text block to have floating width. See example: https://www.dropbox.com/sh/6gk3xfi3egixg9n/AADRa3Gvw08OtgPQ42h7uGZSa?dl=0

Use same approach for fixing Node Program Header and  Small Header Paragraph.

**Comment by YMCA-GTC** [comment]
@AlexNetman Have you tried using the focal point feature to see if you can change the focus point of this image? Just checking. If that didn't work for you, please let us know.

**Comment by YMCA-GTC** [comment]
Changing from Important to Normal until we hear above

**Comment by paige-kiecker** [comment]
This has been resolved with the introduction of the Focal Point tool
