### ISSUE TITLE
PHP Notice: Undefined offset on every page load

### ISSUE THREAD

**Issue by mattshoaf** [ymcatwincities/openy#952]
I'm seeing the following notice in watchdog on every page load, I haven't been able to track it down and can't find another issue opened that addresses it.
`Undefined offset: 1 in Drupal\Core\Render\HtmlResponseAttachmentsProcessor->processHtmlHead() `
It is 18 deep with lots of references to Symphony HttpFoundation, I can post the whole thing if needed, but I figured everybody is seeing it as well. My first thought was that the project just needs to update a dependency, but maybe we're missing a catch somewhere.

Anybody have any ideas?

**Comment by ddrozdik** [comment]
Fix for this issue is ready, @mattshoaf join to test

**Comment by AlexNetman** [comment]
Tested.
