### ISSUE TITLE
Active Communities API Integration

### ISSUE THREAD

**Issue by mattshoaf** [ymcatwincities/openy#955]
I know that integration with Active Communities API has been discussed within the Y community. I'm working with Kansas City and we should be getting API access soon now that Active has officially released the new API. Has anybody with Beta access to the API made any progress, or should I assume I'm starting from scratch?

**Comment by YMCA-GTC** [comment]
@podarok Please respond to this one when you have a moment. Thanks!

**Comment by podarok** [comment]
@mattshoaf Hi
Thanks for being part of OpenY community
There are 3 options for you
1 - we have YMCA of Greater Seattle and YMCA of Brandywine who are working with Active Net
There is some work already happening in terms of getting access to Beta.
2 - @ygerasimov from ImageX agency is working on CRM integrations MVP for OpenY after Daxko was merged into core. You can ask him about any progress to merge efforts
3 - I have access to a lot of codebases from different Ys so in case if you need understand more in depth what was done and above 2 options are blocking you - ping me via email to discuss

**Comment by mattshoaf** [comment]
Thanks for the info, sounds like with 1 they're in the preliminary stages as well, and with 2 I don't think we're going to need any CRM integrations at this time, but that's very interesting and I'll ask if they have something they're using one that I just don't know about.

I took a look at the Daxko module, looks clean so I plan on using that as a model for an Active.net module. When we get ours done if there hasn't been any other progress here in that respect, I'll create a pull request.

**Comment by podarok** [comment]
Thanks, Matt
Appreciate any updates from your side, docs, complains, insights, code.
Do not hesitate to reach me out if any issues.
And good luck with updated ActiveNet API
