### ISSUE TITLE
Lily theme issues

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#964]
Given I switched to Lily Theme 
Then I see following issues:

1) Homepage banner is not properly aligned on ipad landscape.
Also button "Find Y" should be aligned with title. [image](https://user-images.githubusercontent.com/4558228/36592454-ebfb0c0e-18a6-11e8-9e74-0e55239ea23b.png)
2) Homepage section  "What's happening at the Y?"  one of the blog posts is having just one arrow wrapped to the next line. (Good if it could stay on the same line. ) And the next card in the row is having empty white area. [image](https://user-images.githubusercontent.com/4558228/36592852-7721ab34-18a8-11e8-9fc6-d2c57350d22f.png)
3) See comments about colors that can not be adjusted in theme settings https://github.com/ymcatwincities/openy/pull/959

**Comment by YMCA-GTC** [comment]
In addition to these, the header image is obscured on mobile. 
![image](https://user-images.githubusercontent.com/17653329/36695836-0b2e6f68-1b08-11e8-9493-d8331a01f8d7.png)

**Comment by YMCA-GTC** [comment]
These should be addressed with the next release.

**Comment by YMCA-GTC** [comment]
@podarok and the YGTC team are addressing these

**Comment by YMCA-GTC** [comment]
Fixed with 1.11
