### ISSUE TITLE
Fix Lily Theme to be compliant with Behat tests

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#969]
Following tests are failing
![image](https://user-images.githubusercontent.com/4558228/36607709-781753e2-18d8-11e8-8274-aa70e4e6105f.png)

1) Breadcrumbs- add class so that ".breadcrumbs" work again.
2) Image on blog should work with selector ".field-blog-image .field-media-image img" 
3) The text "Save as preferred branch"  is missing on branch. Add that feature.
4) Scenario: I see appropriate sessions content on class                                                       # tests/features/content_types/class.feature:99
The text 'Monday, 12:00PM - 1:00PM, Apr 20, 2037' was not found in the element '.class-page-other-sessions.row .days' on the page 
5) Scenario: I see appropriate content on landing page # tests/features/content_types/landing_page.feature:35
The text "BEHAT BANNER 02" was not found anywhere in the text of the current page.

6) Scenario: Create basic program and subcategory and check fields                                 # tests/features/content_types/program_and_subcategory.feature:41
When I go to "/programs/behat-fitness"
And I should see the link "Open category" 
But those links are currently named "Read More" in Lily.

**Comment by YMCA-GTC** [comment]
I'd like to see us resolve these by the next release, please. I also have found a few other issues I'll post in a separate ticket.

**Comment by YMCA-GTC** [comment]
@podarok Can you please verify that these were fixed? If they were not fixed, I will add them to our backlog. Thank you!

**Comment by YMCA-GTC** [comment]
Next steps: @podarok will investigate further

**Comment by podarok** [comment]
We gave up with Behat in favor of Cypress.
Closing
