### ISSUE TITLE
Ensure we have no errors about basic_html filter doesn't exist after OpenY install

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#974]
There are 3 errors after admin logged into freshly installed OpenY (8.1.8+)
![image](https://user-images.githubusercontent.com/563412/36787402-b66d4724-1c92-11e8-8f2c-370d1f317305.png)

We have to ensure we are not getting these errors.
I believe this is pretty complicated to find, we just need to keep it in our backlog and work when a time is right (Light Core is in higher priority)

**Comment by kolesnikoff** [comment]
@podarok I've just tested clean installation of the development branch and haven't received these errors. Is this bug still actual?

**Comment by YMCA-GTC** [comment]
@podarok See above - if this is fixed, please mark as closed. Thank you!
