### ISSUE TITLE
Groupex Schedules has error on Sandbox

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#981]
http://sandbox.openymca.org/schedules/group-schedules
![image](https://user-images.githubusercontent.com/4558228/36984903-f269233e-20a6-11e8-99f3-38e91562f83d.png)

Error: Call to undefined function Drupal\language\language_get_default_langcode() in Drupal\language\DefaultLanguageItem->getDefaultLangcode() (line 46 of /var/lib/jenkins/jobs/SANDBOX_FAST/workspace/build/docroot/core/modules/language/src/DefaultLanguageItem.php) #0

**Comment by podarok** [comment]
Can't reproduce @AlexNetman 
Could you ensure how-to reproduce step by step?

Thanks

**Comment by AlexNetman** [comment]
Now it's working for me as well.
Please, just check related logs in scope of this issue. They are happening periodically and related to groupex form cache.
![image](https://user-images.githubusercontent.com/4558228/36986754-b1607180-20ab-11e8-88b7-9af31e661550.png)
![image](https://user-images.githubusercontent.com/4558228/36986793-c59f6804-20ab-11e8-9067-d07169bc10ce.png)

**Comment by podarok** [comment]
Let's keep monitoring  to catch exact state to be able to reproduce

**Comment by YMCA-GTC** [comment]
This is happening again as of 5/21. I've asked @kolesnikoff to investigate

**Comment by taras-tsiuper** [comment]
Is this bug still reproducible ?

**Comment by YMCA-GTC** [comment]
Resolved
