### ISSUE TITLE
City is not displayed in the location name, even though it's a required field

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#987]
On the Open Y Rose Theme location landing page, and individual Branch/Camp landing pages, the current display is State, ZIP Code. It should instead be "City, State, Zip Code" in a format such as "Minneapolis, MN 55403"

See attached for examples of where this occurs.

![image](https://user-images.githubusercontent.com/17653329/37679010-b56bbdb8-2c4d-11e8-959e-f189ee58d8d8.png)

![image](https://user-images.githubusercontent.com/17653329/37679035-ca666c18-2c4d-11e8-9c16-346b1a203c3a.png)

![image](https://user-images.githubusercontent.com/17653329/37679070-ded7b9b8-2c4d-11e8-99fb-6725ba0e0470.png)

**Comment by kolesnikoff** [comment]
@podarok the requested functionality is deployed. Can we close the issue?

**Comment by podarok** [comment]
@kolesnikoff yes https://ymca-twin-cities.slack.com/archives/G99KZCYHH/p1524735047000524
