### ISSUE TITLE
Node breadcrumbs do not quickly update to reflect changes made when logged in as admin/content manager

### ISSUE THREAD

**Issue by YMCA-GTC** [ymcatwincities/openy#988]
When I am an admin user/content manager, and I change the title of a node, I should be able to see the changes reflected in the breadcrumb within the Drupal admin interface.

**Comment by YMCA-GTC** [comment]
@podarok When you have time, can you please help me write up the reproduction steps for this one so we can ensure anyone working on it can be able to quickly direct their efforts to the fix? Thank you!

**Comment by kolesnikoff** [comment]
@YMCA-GTC this issue is fixed.
