### ISSUE TITLE
Groupex Schedules are not displaying correct schedule for today

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#992]
Example URL at sandbox with Groupex Schedules paragraph:
http://sandbox.openymca.org/schedules/group-schedules

Given todays "class X" is cancelled
While next week "class X" is still accessible
When I go to see Group Schedules for today
Then I see that "class X" is accessible
But it should not be listed

**Comment by atiupa** [comment]
#993

**Comment by YMCA-GTC** [comment]
@podarok Can you please check if this one is still valid? Thanks!

**Comment by ddrozdik** [comment]
@AlexNetman Can you please check if this one is still valid? Thanks!

**Comment by podarok** [comment]
Fixed
