### ISSUE TITLE
Too many blocks are causing Ajax error

### ISSUE THREAD

**Issue by AlexNetman** [ymcatwincities/openy#994]
Given I have a lot of blocks in the system (example >1500)
When I insert paragraph Groupex Schedules to the page
![image](https://user-images.githubusercontent.com/4558228/37843257-7863809c-2ed5-11e8-9eda-d5a45070987c.png)
Then I can't edit and save blocks in other paragraphs
And getting 500 error from `inline_entity_form` module in console
![image](https://user-images.githubusercontent.com/4558228/37843462-0598998e-2ed6-11e8-9e2c-8e9538f55eaf.png)

**Expected solution:**
we should hide this block from settings cause it's never expected to be changed

**Comment by AlexNetman** [comment]
Useful link:
https://www.drupal.org/docs/8/creating-custom-modules/create-a-custom-field-widget

**Comment by ddrozdik** [comment]
hi @AlexNetman. Seems this issue could be  related to this one https://github.com/ymcatwincities/openy/issues/983

**Comment by podarok** [comment]
@kolesnikoff 
Could you please spend 1-2 hours to check if mentioned drop-down widget could be replaced with autocomplete? 
 - check if the module itself contains the autocomplete widget for a form view
 - check module's drupal.org issue queue if there are patches or discussions there


If nothing from above -> add patch to replace drop-down with autocomplete, post if to drupal.org as feature/bug request to the respective module issue queue and add patch to composer.json within OpenY

Thank you in advance

**Comment by YMCA-GTC** [comment]
This will go into the Q2 2018 release planned for May 8

**Comment by kolesnikoff** [comment]
The solution is built into https://github.com/ymcatwincities/openy/pull/1025

**Comment by YMCA-GTC** [comment]
@kolesnikoff @podarok Did this make it into the May 8 release? If not, we'll make it for Q3 in August.

**Comment by YMCA-GTC** [comment]
Assigned to IXM for resolution

**Comment by kolesnikoff** [comment]
@AlexNetman could you confirm that this issue is reproducible still?

**Comment by YMCA-GTC** [comment]
Resolved with 1.12
